local _, ns = ...

-- Item IDs for every consumable, enchant and gem the shipped guides name in
-- their `consumables` blocks (Data/Guides_*.lua). The guides carry the IDs
-- themselves (each entry's `items` list) and the Codex's Consumables tab
-- draws those as hoverable, clickable chips; this table is the name each
-- ID falls back to before the client has the item cached, and lets the
-- prose scanner below find items in a line that names them without an
-- `items` list (a third-party guide pack, or the older shape).
--
-- GENERATED by tools/gen_consumables.py from its catalogue - edit the
-- catalogue and rerun rather than editing this table. Every ID was looked
-- up on Wowhead (name, ID, tooltip) on 2026-09-05; crafted items are the
-- rank-2 version and gems the Flawless tier.
ns.ConsumableItems = {
    ["Arcanoweave Spellthread"] = 240155,
    ["Blood Knight's Armor Kit"] = 244643,
    ["Concentrated Silvermoon Health Potion"] = 271884,
    ["Crystallized Augment Rune"] = 224572,
    ["Enchant Boots - Farstrider's Hunt"] = 244009,
    ["Enchant Boots - Lynx's Dexterity"] = 243953,
    ["Enchant Boots - Shaladrassil's Roots"] = 243983,
    ["Enchant Chest - Mark of Nalorakk"] = 243947,
    ["Enchant Chest - Mark of the Magister"] = 244003,
    ["Enchant Chest - Mark of the Rootwarden"] = 243975,
    ["Enchant Chest - Mark of the Worldsoul"] = 243977,
    ["Enchant Helm - Blessing of Speed"] = 243979,
    ["Enchant Helm - Hex of Leeching"] = 243949,
    ["Enchant Helm - Rune of Avoidance"] = 244005,
    ["Enchant Ring - Nature's Fury"] = 243987,
    ["Enchant Ring - Silvermoon's Alacrity"] = 244015,
    ["Enchant Ring - Silvermoon's Tenacity"] = 244017,
    ["Enchant Ring - Zul'jin's Mastery"] = 243959,
    ["Enchant Shoulders - Akil'zon's Swiftness"] = 243963,
    ["Enchant Shoulders - Amirdrassil's Grace"] = 243991,
    ["Enchant Shoulders - Silvermoon's Mending"] = 244021,
    ["Enchant Weapon - Acuity of the Ren'dorei"] = 244029,
    ["Enchant Weapon - Arcane Mastery"] = 244031,
    ["Enchant Weapon - Berserker's Rage"] = 243973,
    ["Enchant Weapon - Jan'alai's Precision"] = 243971,
    ["Enchant Weapon - Worldsoul Aegis"] = 243999,
    ["Enchant Weapon - Worldsoul Cradle"] = 243997,
    ["Enchant Weapon - Worldsoul Tenacity"] = 244001,
    ["Feast of Knowledge"] = 275266,
    ["Flask of Thalassian Resistance"] = 241321,
    ["Flask of the Blood Knights"] = 241325,
    ["Flask of the Magisters"] = 241323,
    ["Flask of the Shattered Sun"] = 241327,
    ["Flawless Deadly Amethyst"] = 240898,
    ["Flawless Deadly Garnet"] = 240904,
    ["Flawless Deadly Lapis"] = 240914,
    ["Flawless Deadly Peridot"] = 240890,
    ["Flawless Masterful Amethyst"] = 240896,
    ["Flawless Masterful Garnet"] = 240908,
    ["Flawless Masterful Lapis"] = 240918,
    ["Flawless Masterful Peridot"] = 240892,
    ["Flawless Quick Amethyst"] = 240900,
    ["Flawless Quick Garnet"] = 240906,
    ["Flawless Quick Lapis"] = 240916,
    ["Flawless Quick Peridot"] = 240888,
    ["Flawless Versatile Amethyst"] = 240902,
    ["Flawless Versatile Garnet"] = 240910,
    ["Flawless Versatile Lapis"] = 240912,
    ["Flawless Versatile Peridot"] = 240894,
    ["Forest Hunter's Armor Kit"] = 244641,
    ["Harandar Celebration"] = 255846,
    ["Hearty Null and Void Plate"] = 242754,
    ["Hearty Puffer Plate"] = 275262,
    ["Hearty Sun-Seared Lumifin"] = 242755,
    ["Hearty Venom-Spiced Cutlets"] = 275259,
    ["Hearty Void-Kissed Fish Rolls"] = 242756,
    ["Hearty Warped Wise Wings"] = 242757,
    ["Light's Potential"] = 241309,
    ["Light's Preservation"] = 241287,
    ["Lightfused Mana Potion"] = 241301,
    ["Liquid Luster"] = 271887,
    ["Loa's Gathering"] = 275265,
    ["Oil of Dawn"] = 243736,
    ["Potion of Devoured Dreams"] = 241295,
    ["Potion of Recklessness"] = 241289,
    ["Powerful Eversong Diamond"] = 240967,
    ["Refulgent Weightstone"] = 237369,
    ["Refulgent Whetstone"] = 237371,
    ["Silvermoon Parade"] = 255845,
    ["Smuggler's Enchanted Edge"] = 243738,
    ["Soulgorged Augment Rune"] = 246492,
    ["Stoic Eversong Diamond"] = 240971,
    ["Sunfire Silk Spellthread"] = 240133,
    ["Telluric Eversong Diamond"] = 240969,
    ["Thalassian Phoenix Oil"] = 243734,
    ["Void-Touched Augment Rune"] = 259085,
}

-- ID -> name, for a chip whose item the client has not cached yet.
ns.ConsumableNames = {}
for name, itemID in pairs(ns.ConsumableItems) do ns.ConsumableNames[itemID] = name end

-- Names sorted longest first, built once.
local ordered
local function OrderedNames()
    if ordered then return ordered end
    ordered = {}
    for name in pairs(ns.ConsumableItems) do ordered[#ordered + 1] = name end
    table.sort(ordered, function(a, b)
        if #a ~= #b then return #a > #b end
        return a < b
    end)
    return ordered
end

-- The consumables a line of guide prose names, in the order they appear,
-- each once: { { name = ..., itemID = ... }, ... }. Plain (non-pattern)
-- find, so apostrophes and hyphens in names are safe.
function ns.FindConsumableItems(text)
    local found = {}
    if type(text) ~= "string" or text == "" then return found end
    local claimed = {}
    for _, name in ipairs(OrderedNames()) do
        local start = text:find(name, 1, true)
        while start do
            local finish = start + #name - 1
            local overlaps = false
            for _, span in ipairs(claimed) do
                if start <= span[2] and finish >= span[1] then overlaps = true break end
            end
            if not overlaps then
                claimed[#claimed + 1] = { start, finish, name }
            end
            start = text:find(name, finish + 1, true)
        end
    end
    table.sort(claimed, function(a, b) return a[1] < b[1] end)
    local seen = {}
    for _, span in ipairs(claimed) do
        local name = span[3]
        if not seen[name] then
            seen[name] = true
            found[#found + 1] = { name = name, itemID = ns.ConsumableItems[name] }
        end
    end
    return found
end
