local ADDON, ns = ...

-- SpecSage guide data: Druid
-- Content targets The War Within. This is community-maintained, conventional
-- guidance (keep-it-simple stat priorities, long-standing rotation patterns)
-- and is NOT a claim of sim-perfect or bleeding-edge optimal play.
-- To edit: find the RegisterSpec(...) block for the spec you want to change
-- and edit the table in place. To add a new tip/step, insert a new entry in
-- the relevant array. Keep this file data-only — no logic beyond the calls
-- below. See DESIGN.md "Guide data schema" for the full table shape.

if not ns.GuideStore then return end

-- Balance ------------------------------------------------------------------
ns.GuideStore:RegisterSpec("DRUID", 102, {
  specName = "Balance",
  role = "DAMAGER",
  overview = {
    "Balance Druid is a ranged caster spec that oscillates between Solar and Lunar states (the Eclipse cycle), alternating Wrath and Starfire to shift between them while building Astral Power to spend on Starsurge and Starfall.",
    "The core mechanic is Astral Power, generated by Wrath/Starfire and eclipse procs, spent on Starsurge (single target burst) and Starfall (AoE). Celestial Alignment and Incarnation: Chosen of Elune are periodic burst windows that empower the whole kit.",
    "Bring Balance when you want a spec with strong sustained ranged damage, good AoE via Starfall/Wild Mushroom setups, and burst windows that scale well with raid cooldowns, at the cost of some setup time before damage ramps up.",
  },
  statPriority = {
    { stat = "primary" },
    { stat = "haste" },
    { stat = "mastery" },
    { stat = "crit" },
    { stat = "versatility" },
  },
  rotation = {
    { title = "Opener", steps = {
        { text = "Wrath / Starfire to begin building toward an Eclipse" },
        { text = "Sunfire and Moonfire to apply dots to the target before committing to burst" },
        { spellID = 194223, text = "Celestial Alignment once dots are up, to open a strong burst window" },
        { spellID = 78674, text = "Starsurge to spend Astral Power during the burst window" },
    }},
    { title = "Single Target", steps = {
        { text = "Keep Sunfire and Moonfire active on the target at all times" },
        { text = "Alternate Wrath/Starfire to shift between Solar and Lunar Eclipse" },
        { spellID = 78674, text = "Starsurge on cooldown once Astral Power allows" },
        { text = "Spend excess Astral Power rather than letting it float near cap" },
        { text = "Weave in Force of Nature / Fury of Elune (talent-dependent) as available" },
    }},
    { title = "AoE", steps = {
        { text = "Sunfire and Moonfire to apply dots across as many targets as practical" },
        { spellID = 191034, text = "Starfall as your primary AoE Astral Power spender" },
        { text = "Wild Mushroom / Fury of Elune (talent-dependent) for extra AoE burst" },
        { text = "Use Typhoon/stuns to control adds if needed for the encounter" },
        { text = "Time Celestial Alignment/Incarnation for when the full pack is dotted and engaged" },
    }},
  },
  cooldowns = {
    { spellID = 194223, text = "Celestial Alignment — merges both Eclipse states for a strong burst window" },
    { text = "Incarnation: Chosen of Elune (talent, alternative to Celestial Alignment) — extended burst with mobility" },
    { text = "Fury of Elune (talent) — burst AoE/cleave cooldown, use inside your main burst window" },
    { spellID = 22812, text = "Barkskin — defensive, reduces damage taken" },
    { spellID = 61336, text = "Survival Instincts — major defensive cooldown for heavy incoming damage" },
  },
  consumables = {
    { slot = "Flask", text = "Flask of Alchemical Chaos (Intellect)" },
    { slot = "Food", text = "A feast or personal Intellect food for the encounter" },
    { slot = "Potion", text = "Tempered Potion, used during Celestial Alignment" },
    { slot = "Weapon", text = "Not applicable" },
    { slot = "Enchants", text = "Max-rank Intellect enchants on cloak and rings" },
    { slot = "Gems", text = "Intellect/secondary stat gems in available sockets" },
  },
  gear = {
    { slot = "Head", text = "One of your tier-set slots — the four-piece bonus reinforces your Eclipse/Astral Power engine, worth prioritizing" },
    { slot = "Chest", text = "A large stat budget and often your other tier piece — lean Haste first for a faster Eclipse cycle" },
    { slot = "Neck", text = "Usually carries a socket — favor Haste, then Mastery" },
    { slot = "Ring", text = "No set bonus attached — use rings to round out Haste and Mastery" },
    { slot = "Trinket", text = "One on-use trinket timed with Celestial Alignment/Incarnation so its burst overlaps your merged-Eclipse window" },
    { slot = "Trinket", text = "A passive secondary-stat trinket to hold sustained dot-and-filler damage between burst windows" },
    { slot = "Weapon", text = "Take the highest weapon damage staff or one-hand-plus-off-hand — Balance's damage scales off spellpower and stats, not weapon type" },
    { slot = "Off-hand", text = "A caster off-hand leaning Haste keeps your Eclipse cycling and Astral Power flowing" },
  },
  tips = {
    "Never let Sunfire or Moonfire fall off — dot uptime is a large share of Balance's total damage.",
    "Don't sit at capped Astral Power; spend it on Starsurge/Starfall before it overflows.",
    "Line Celestial Alignment/Incarnation up with dots already applied so the burst window isn't wasted ramping up.",
    "Use your mobility and root/stun kit (Typhoon, Mass Entanglement) proactively on movement-heavy fights.",
  },
})

-- Feral ----------------------------------------------------------------
ns.GuideStore:RegisterSpec("DRUID", 103, {
  specName = "Feral",
  role = "DAMAGER",
  overview = {
    "Feral Druid is a bleed-based melee spec that builds and spends Combo Points on finishers, keeping Rip and Rake active as bleeds while weaving in Ferocious Bite and Tiger's Fury-powered burst windows.",
    "The core resource is Combo Points (0-5, or higher with talents), generated by Shred/Rake and spent on finishers like Rip and Ferocious Bite. Energy regeneration and bleed uptime (Rake, Rip, Thrash) are the main damage drivers, with Bloodtalons and similar talents rewarding ability sequencing.",
    "Bring Feral when you want a mobile melee spec with strong sustained bleed damage, solid stealth-openers, and good multi-dot AoE, at the cost of a rotation that punishes dropped bleeds heavily.",
  },
  statPriority = {
    { stat = "primary" },
    { stat = "crit" },
    { stat = "mastery" },
    { stat = "versatility" },
    { stat = "haste" },
  },
  rotation = {
    { title = "Opener", steps = {
        { text = "Enter Prowl before combat for a guaranteed-crit opener" },
        { spellID = 1822, text = "Rake from stealth for a strong bleed and combo point" },
        { spellID = 5217, text = "Tiger's Fury to open a burst window with extra Energy" },
        { spellID = 1079, text = "Rip once you have 5 combo points to start the primary bleed" },
    }},
    { title = "Single Target", steps = {
        { spellID = 1822, text = "Rake to apply and refresh its bleed, especially from behind" },
        { text = "Thrash to keep a secondary bleed rolling" },
        { spellID = 5221, text = "Shred as your main combo point builder while behind the target" },
        { spellID = 1079, text = "Rip to apply/refresh the primary finisher bleed at 5 combo points" },
        { spellID = 22568, text = "Ferocious Bite to spend combo points once Rip and Rake are in good shape" },
    }},
    { title = "AoE", steps = {
        { text = "Thrash to apply its bleed across all nearby targets" },
        { text = "Swipe for direct AoE damage and combo point generation" },
        { spellID = 1079, text = "Rip on the priority target(s) once combo points allow" },
        { text = "Keep Rake up on a high-value target while cleaving with Thrash/Swipe" },
        { text = "Use Tiger's Fury and Berserk/Incarnation to power through burst AoE windows" },
    }},
  },
  cooldowns = {
    { spellID = 5217, text = "Tiger's Fury — Energy refund and damage buff, use to open burst windows" },
    { text = "Berserk / Incarnation: Avatar of Ashamane (talent-dependent) — major burst cooldown, line up with Tiger's Fury" },
    { spellID = 22812, text = "Barkskin — defensive, reduces damage taken while still attacking" },
    { spellID = 61336, text = "Survival Instincts — major defensive cooldown for heavy incoming damage" },
  },
  consumables = {
    { slot = "Flask", text = "Flask of Alchemical Chaos (Agility)" },
    { slot = "Food", text = "A feast or personal Agility food for the encounter" },
    { slot = "Potion", text = "Tempered Potion, used inside your burst window" },
    { slot = "Weapon", text = "Ironclaw Whetstone or the current-tier weapon enchant" },
    { slot = "Enchants", text = "Max-rank Agility enchants on cloak and rings" },
    { slot = "Gems", text = "Agility/secondary stat gems in available sockets" },
  },
  gear = {
    { slot = "Head", text = "One of your tier-set slots — the four-piece bonus is built around your bleed-and-combo-point loop, worth prioritizing" },
    { slot = "Chest", text = "A large stat budget and often your other tier piece — push Critical Strike first since it scales both bleeds and finishers" },
    { slot = "Neck", text = "Usually carries a socket — favor Critical Strike, then Mastery" },
    { slot = "Ring", text = "No set bonus attached — use rings to round out Critical Strike and Mastery" },
    { slot = "Trinket", text = "One on-use trinket timed with Tiger's Fury/Berserk so its burst lands inside your window" },
    { slot = "Trinket", text = "A passive Agility stat-stick trinket to keep bleed damage strong between cooldowns" },
    { slot = "Weapon", text = "Cat Form normalizes weapon speed, so simply take the highest weapon damage item — type doesn't matter for your attacks" },
    { slot = "Feet", text = "Look for an itemization roll that keeps Critical Strike or Mastery flowing since Feral has few other stat-heavy accessory options" },
  },
  tips = {
    "Never let Rip or Rake fall off the target — refreshing dropped bleeds costs far more than early refreshes.",
    "Open from Prowl whenever the pull allows it for a free crit and Energy tempo.",
    "Pool Energy slightly before Tiger's Fury/Berserk so you can dump it immediately when the window opens.",
    "On cleave fights, keep your main bleeds on the priority target while using Thrash/Swipe for the rest.",
  },
})

-- Guardian ---------------------------------------------------------------
ns.GuideStore:RegisterSpec("DRUID", 104, {
  specName = "Guardian",
  role = "TANK",
  overview = {
    "Guardian Druid tanks in Bear Form, relying on high armor and Stamina along with Frenzied Regeneration and Barkskin-style cooldowns for damage mitigation, while Ironfur and Mangle/Thrash keep threat and physical mitigation up.",
    "The core mechanic is Rage generation from taking and dealing damage, spent on Ironfur (a stacking armor buff) to reduce physical damage and on Maul/Moonfire-derived finishers. Ursoc's Fury and other passives reward staying in the fight and taking hits rather than sitting still.",
    "Bring Guardian when you want a tank with high physical damage mitigation, strong self-healing through Frenzied Regeneration and Ursine Vigor-style passives, and solid AoE threat via Thrash and Swipe.",
  },
  statPriority = {
    { stat = "stamina" },
    { stat = "primary" },
    { stat = "versatility" },
    { stat = "mastery" },
    { stat = "haste" },
    { stat = "crit" },
  },
  rotation = {
    { title = "Single Target", steps = {
        { text = "Mangle on cooldown for threat and Rage generation" },
        { text = "Thrash to apply/refresh its bleed even on a single target for extra mitigation and damage" },
        { text = "Moonfire (Guardian variant) to maintain a ranged dot when applicable" },
        { text = "Maul/Raze to spend excess Rage once Ironfur is maintained" },
        { text = "Swipe as filler when other abilities are on cooldown" },
    }},
    { title = "AoE", steps = {
        { text = "Thrash on cooldown as your primary AoE threat and bleed tool" },
        { text = "Swipe to hit all nearby targets for damage and Rage generation" },
        { text = "Mangle on cooldown for extra Rage and single strong-target damage" },
        { text = "Maintain Ironfur stacks across pulls, especially before damage lands" },
        { text = "Incarnation: Guardian of Ursoc (talent) for extended high-threat AoE windows" },
    }},
    { title = "Mitigation", steps = {
        { text = "Ironfur to stack physical mitigation, especially before an incoming hit or swing" },
        { text = "Frenzied Regeneration to heal through sustained damage" },
        { spellID = 22812, text = "Barkskin for a flat damage reduction window" },
        { spellID = 61336, text = "Survival Instincts for the heaviest damage spikes" },
        { text = "Don't let Rage sit unused — convert it into Ironfur before big hits rather than after" },
    }},
  },
  cooldowns = {
    { spellID = 61336, text = "Survival Instincts — major defensive, use for the heaviest damage spikes" },
    { spellID = 22812, text = "Barkskin — flat damage reduction, use proactively before predictable damage" },
    { text = "Incarnation: Guardian of Ursoc (talent) — major cooldown for extended tough phases" },
    { text = "Frenzied Regeneration — self-healing, use when sustained damage is outpacing external healing" },
  },
  consumables = {
    { slot = "Flask", text = "Flask of Alchemical Chaos (Agility, tank stat variant)" },
    { slot = "Food", text = "A feast or personal Stamina/Agility food for the encounter" },
    { slot = "Potion", text = "Tempered Potion or a Stamina/defensive potion for survival cooldowns" },
    { slot = "Weapon", text = "Ironclaw Whetstone or the current-tier weapon enchant" },
    { slot = "Enchants", text = "Max-rank Stamina/Agility enchants on cloak and rings" },
    { slot = "Gems", text = "Stamina/Agility gems in available sockets" },
  },
  gear = {
    { slot = "Head", text = "One of your tier-set slots — the four-piece bonus strengthens your Ironfur/Rage loop, worth prioritizing" },
    { slot = "Chest", text = "A large stat budget and often your other tier piece — balance Stamina for your health pool against Versatility for flat mitigation" },
    { slot = "Neck", text = "Usually carries a socket — lean Versatility first, then Mastery" },
    { slot = "Ring", text = "No set bonus attached — use rings to fill out Versatility and Mastery wherever your gear is light" },
    { slot = "Trinket", text = "One trinket built around avoidance, armor, or a defensive proc rather than pure Agility, to smooth out incoming spikes" },
    { slot = "Trinket", text = "A second trinket that adds Stamina or a passive mitigation effect so survivability doesn't get sacrificed entirely for threat" },
    { slot = "Weapon", text = "Bear Form normalizes weapon speed, so take the highest weapon damage item available regardless of type" },
    { slot = "Waist", text = "An easy slot to fill in an extra gem toward whichever secondary — Versatility or Mastery — your build is short on" },
  },
  tips = {
    "Keep Ironfur stacked proactively rather than reactively — mitigation applied before the hit lands is what matters.",
    "Don't neglect Thrash even on single-target fights; its bleed adds meaningful sustained damage and threat.",
    "Use Frenzied Regeneration to smooth out damage between healer cooldowns rather than saving it indefinitely.",
    "Pool Rage slightly before a telegraphed damage spike so you can pump Ironfur right before it lands.",
  },
})

-- Restoration --------------------------------------------------------------
ns.GuideStore:RegisterSpec("DRUID", 105, {
  specName = "Restoration",
  role = "HEALER",
  overview = {
    "Restoration Druid heals primarily through layered heal-over-time effects (Rejuvenation, Lifebloom, Wild Growth) that cover the whole raid, supplemented by direct heals like Regrowth for spot healing and Swiftmend for instant emergency top-ups.",
    "The core mechanic is HoT uptime and Efflorescence/Wild Growth-style group coverage: keeping Rejuvenation rolling on multiple targets and Lifebloom on the tank builds a strong passive healing floor, while Clearcasting procs from Overgrowth/other passives enable free, efficient direct heals.",
    "Bring Restoration when you want a mobile healer with strong raid-wide HoT coverage, good mana efficiency at moderate haste, and useful utility (Innervate, combat rebirth, roots/CC) beyond pure healing throughput.",
  },
  statPriority = {
    { stat = "primary" },
    { stat = "haste", note = "smooths HoT ticks and cast times" },
    { stat = "mastery" },
    { stat = "crit" },
    { stat = "versatility" },
  },
  rotation = {
    { title = "Priorities", steps = {
        { spellID = 774, text = "Rejuvenation to keep it rolling on injured or soon-to-be-injured targets" },
        { text = "Lifebloom on the tank (or primary target) to maintain its stack and bloom value" },
        { spellID = 48438, text = "Wild Growth on cooldown for burst group-wide healing" },
        { spellID = 8936, text = "Regrowth for efficient spot healing, especially on Clearcasting procs" },
        { text = "Swiftmend for instant emergency healing, consuming a HoT on the target" },
    }},
    { title = "Cooldown usage", steps = {
        { spellID = 740, text = "Tranquility for a strong raid-wide healing burst during heavy damage" },
        { text = "Incarnation: Tree of Life (talent) to extend and empower your HoT-based healing" },
        { text = "Flourish (talent) to extend all active HoTs during a big damage phase" },
        { text = "Innervate on yourself or another mana-hungry healer during a long fight" },
        { text = "Pre-HoT the raid ahead of known damage rather than reacting purely after it lands" },
    }},
  },
  cooldowns = {
    { spellID = 740, text = "Tranquility — raid-wide burst heal, use for a scripted heavy damage phase" },
    { text = "Incarnation: Tree of Life (talent) — major cooldown, amplifies HoT output for its duration" },
    { text = "Flourish (talent) — extends active HoTs, pairs well with Tranquility/Incarnation" },
    { text = "Nature's Swiftness — makes your next heal instant, use for an emergency or to weave in while moving" },
    { spellID = 22812, text = "Barkskin — personal defensive, reduces damage taken" },
  },
  consumables = {
    { slot = "Flask", text = "Flask of Alchemical Chaos (Intellect)" },
    { slot = "Food", text = "A feast or personal Intellect food for the encounter" },
    { slot = "Potion", text = "Tempered Potion or a healing-oriented potion for a big damage phase" },
    { slot = "Weapon", text = "Not applicable" },
    { slot = "Enchants", text = "Max-rank Intellect enchants on cloak and rings" },
    { slot = "Gems", text = "Intellect/secondary stat gems in available sockets" },
  },
  gear = {
    { slot = "Head", text = "One of your tier-set slots — the four-piece bonus adds real throughput to your HoT coverage, worth prioritizing" },
    { slot = "Chest", text = "A large stat budget and often your other tier piece — lean Haste first to smooth HoT ticks and cast times" },
    { slot = "Neck", text = "Usually carries a socket — favor Haste, then Mastery" },
    { slot = "Ring", text = "No set bonus attached — use rings to round out Haste and Mastery" },
    { slot = "Trinket", text = "One mana-efficiency or passive-throughput trinket to stretch your HoT-based healing across a long fight" },
    { slot = "Trinket", text = "A second trinket built around a burst-healing proc or on-use effect you can align with Tranquility/Incarnation" },
    { slot = "Weapon", text = "Take the highest weapon damage staff or one-hand-plus-off-hand — Restoration's healing scales off spellpower and stats, not weapon type" },
    { slot = "Off-hand", text = "A caster off-hand leaning Haste keeps your HoT rolling and cast-heavy spot healing smooth" },
  },
  tips = {
    "Keep Rejuvenation spread across as many raid members as you can sustainably maintain — it's your mana-efficient floor.",
    "Don't let Lifebloom fall off the tank; refreshing before it blooms preserves its passive healing bonus.",
    "Pre-HoT the raid before known damage windows so Wild Growth/Tranquility land on top of existing coverage.",
    "Use Swiftmend on cooldown-permitting emergencies rather than saving it indefinitely — it's meant to be used regularly.",
  },
})
