local ADDON, ns = ...

-- SpecSage guide data: Druid
-- Content targets Midnight (patch 12.1). Specs below with an `mplusLoadout`
-- field have that talent string (only) cross-checked against
-- SimulationCraft's public profiles (github.com/simulationcraft/simc,
-- GPLv3) as of patch 12.1; specs without one have no such reference.
-- Rotation/overview/tips/gear prose throughout this file is hand-authored
-- and was reviewed for Midnight ability changes, not derived from or
-- checked against SimC's APLs, and was not re-verified against current
-- tuning this pass — EXCEPT Balance (102), Feral (103), Guardian (104), and Restoration (105),
-- which each gained an `mplusMetaLoadout` (DESIGN.md's v1.4 section) this
-- pass: pulled live from Blizzard's own Battle.net Game Data API
-- (client-credentials OAuth, US region) rather than SimC, on 2026-08-30.
-- Methodology: every current-season Mythic+ leaderboard (8-dungeon pool,
-- period 1078) across all 83 US connected realms was scanned (top 20 groups
-- per realm/dungeon) for each spec's group members; the top-observed-keystone
-- characters (up to 50 per spec) had their live `specializations` looked up
-- for their active loadout's `talent_loadout_code`. See each field's own
-- `source` comment for the resulting distribution.
-- This pass also added an "Opener Notes" rotation entry naming each spec's
-- two hero talent trees, for the three specs that didn't already have one
-- inline (Feral, Guardian, Restoration - Balance already carried a hero-tree
-- note and was left as-is). Unlike the hand-authored prose above, these new
-- notes ARE cross-checked against SimC's current `midnight` branch profiles
-- (github.com/simulationcraft/simc) where a real action-list branch exists
-- per hero tree; where SimC's profile set has no branch (an identical
-- actions= list either way, or no profile for the spec at all), the note
-- says so honestly instead of inventing a rotation change.
-- Feral's overview was also corrected this pass: it credited "Bloodtalons
-- and similar talents" for rewarding ability sequencing. Blizzard's own
-- Midnight Pre-Expansion Content Update Notes list Bloodtalons among
-- talents removed outright, and SimC's current Feral profile has zero
-- Bloodtalons references - that damage is now baseline rather than
-- conditional on sequencing.
-- Balance's Eclipse description was also corrected this pass: it described
-- passively alternating Wrath/Starfire to shift Eclipse states, but SimC's
-- current profile treats Eclipse as a directly-cast ability with its own
-- recharging cooldown (cooldown.eclipse.full_recharge_time, charges),
-- confirmed against a Blizzard forum explainer thread on how Eclipse
-- currently works — Wrath/Starfire now only prime which Eclipse comes next.
-- This is community-maintained, conventional guidance (keep-it-simple stat
-- priorities, long-standing rotation patterns) and is NOT a claim of
-- sim-perfect or bleeding-edge optimal play.
-- To edit: find the RegisterSpec(...) block for the spec you want to change
-- and edit the table in place. To add a new tip/step, insert a new entry in
-- the relevant array. Keep this file data-only — no logic beyond the calls
-- below. See DESIGN.md "Guide data schema" for the full table shape.

if not ns.GuideStore then return end

-- Balance ------------------------------------------------------------------
ns.GuideStore:RegisterSpec("DRUID", 102, {
  specName = "Balance",
  role = "DAMAGER",
  overview = {
    "Balance Druid is a ranged caster spec built around Solar and Lunar Eclipse states: casting Wrath or Starfire primes which one comes next, then pressing Eclipse itself (a directly-cast ability on its own recharging cooldown, not a passive alternation) enters it, while building Astral Power to spend on Starsurge and Starfall.",
    "The core mechanic is Astral Power, generated by Wrath/Starfire and by keeping Sunfire/Moonfire ticking, spent on Starsurge (single target, and up to 3 targets) and Starfall (multi-target). Celestial Alignment and Incarnation: Chosen of Elune grant both Eclipse states' benefits simultaneously for a periodic burst window that empowers the whole kit.",
    "Bring Balance when you want a spec with strong sustained ranged damage, good AoE via Starfall/Wild Mushroom setups, and burst windows that scale well with raid cooldowns, at the cost of some setup time before damage ramps up. Elune's Chosen always casts Starfire and plays entirely out of Lunar Eclipse (Lunar Calling blocks it from entering Solar at all), pushing it toward Lunar Eclipse at 4+ targets, while Keeper of the Grove keeps the standard Solar/Lunar cycle and is the more single-target-focused of the two.",
  },
  statPriority = {
    { stat = "primary" },
    { stat = "haste" },
    { stat = "mastery" },
    { stat = "crit" },
    { stat = "versatility" },
  },
  rotation = {
    { title = "Opener", steps = {
        { spellID = 24858, text = "Moonkin Form before you start casting" },
        { text = "Sunfire on your kill target and Moonfire spread to any others to start building dots" },
        { text = "Begin casting Wrath (primes Solar) or Starfire (primes Lunar) to line up your first Eclipse" },
        { spellID = 194223, text = "Celestial Alignment/Incarnation together with Force of Nature and Fury of Elune, once dots are up, to open a strong burst window" },
        { spellID = 78674, text = "Starsurge to spend Astral Power during the burst window" },
        { text = "Opener Notes: Balance splits along the Elune's Chosen and Keeper of the Grove hero trees — Elune's Chosen always casts Starfire and plays entirely out of Lunar Eclipse since Lunar Calling blocks it from entering Solar at all, while Keeper of the Grove keeps closer to the Eclipse-cycle flow above" },
    }},
    { title = "Single Target", steps = {
        { text = "Keep Sunfire and Moonfire active on the target at all times" },
        { text = "Cast Wrath to prime and enter Solar Eclipse on single target (and up to 3 targets) — press Eclipse itself once it's off cooldown to enter it" },
        { spellID = 78674, text = "Starsurge on cooldown once Astral Power allows, prioritized on your single or priority target" },
        { text = "Cast Wrath as your Solar-phase filler between Starsurge casts" },
        { text = "Never let Astral Power sit near the cap — spend it rather than letting it float" },
        { text = "Weave in Force of Nature / Fury of Elune (talent-dependent) as available" },
    }},
    { title = "AoE", steps = {
        { text = "Sunfire and Moonfire to apply dots across as many targets as practical" },
        { text = "Enter Lunar Eclipse at 4+ targets by casting Starfire, rather than defaulting to Solar" },
        { spellID = 191034, text = "Starfall as your primary AoE Astral Power spender" },
        { text = "If you're talented into Starweaver, its free opposite-spender procs (a free Starfall during Solar, or a free Starsurge during Lunar) are worth using the moment they appear" },
        { text = "Wild Mushroom / Fury of Elune (talent-dependent) for extra AoE burst" },
        { text = "Use Typhoon/stuns to control adds if needed for the encounter" },
        { text = "Time Celestial Alignment/Incarnation for when the full pack is dotted and engaged" },
    }},
  },
  cooldowns = {
    { spellID = 194223, text = "Celestial Alignment — grants both Eclipse states' benefits simultaneously for a strong burst window" },
    { spellID = 390414, text = "Incarnation: Chosen of Elune (talent, alternative to Celestial Alignment) — extended burst with mobility" },
    { spellID = 202770, text = "Fury of Elune (talent) — burst AoE/cleave cooldown, use on cooldown inside your main burst window" },
    { spellID = 205636, text = "Force of Nature (talent) — summons treants for extra damage, keep it on cooldown alongside Fury of Elune" },
    { spellID = 22812, text = "Barkskin — defensive, reduces damage taken" },
    { spellID = 61336, text = "Survival Instincts — major defensive cooldown for heavy incoming damage" },
  },
  consumables = {
    { slot = "Flask", text = "Flask of Alchemical Chaos (Intellect)" },
    { slot = "Food", text = "A feast or personal Intellect food for the encounter" },
    { slot = "Potion", text = "Tempered Potion, used during Celestial Alignment" },
    { slot = "Weapon", text = "Not applicable" },
    { slot = "Enchants", text = "Max-rank Intellect enchants on cloak and rings" },
    { slot = "Gems", text = "Intellect/secondary stat gems in available sockets" },
  },
  gear = {
    { slot = "Head", text = "One of your tier-set slots — the four-piece bonus reinforces your Eclipse/Astral Power engine, worth prioritizing" },
    { slot = "Chest", text = "A large stat budget and often your other tier piece — lean Haste first for a faster Eclipse cycle" },
    { slot = "Neck", text = "Usually carries a socket — favor Haste, then Mastery" },
    { slot = "Ring", text = "No set bonus attached — use rings to round out Haste and Mastery" },
    { slot = "Trinket", text = "One on-use trinket timed with Celestial Alignment/Incarnation so its burst overlaps your merged-Eclipse window" },
    { slot = "Trinket", text = "A passive secondary-stat trinket to hold sustained dot-and-filler damage between burst windows" },
    { slot = "Weapon", text = "Take the highest weapon damage staff or one-hand-plus-off-hand — Balance's damage scales off spellpower and stats, not weapon type" },
    { slot = "Off-hand", text = "A caster off-hand leaning Haste keeps your Eclipse cycling and Astral Power flowing" },
  },
  -- MID1 fallback: SimC has not yet published a MID2 (12.1) default profile
  -- for Balance, so this loadout is pulled from the MID1 (12.0) profile set
  -- instead. Swap to a MID2 profile once SimC publishes one.
  mplusLoadout = {
    string = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNjxMDwsYmZmZhBjZZmlZYmZswyMLzMGzshhBYstMzgxsNCMBAAAYxMzMzgNDjxAAwMDMA",
    source = "SimulationCraft default profile (credit, not endorsement of 'best')",
    patch = "12.0 (MID1, previous tier)",
  },
  -- Live top-players pull (DESIGN.md's v1.4 section), NOT SimC - see this
  -- file's header for the full methodology. The plurality build among the
  -- sample: 4/50 (8%) ran this exact code, since flex-point choices vary - but
  -- the bigger signal is that 49/50 (98%) ran Elune's Chosen overall. Reported
  -- honestly rather than dressed up as more decisive than it is.
  mplusMetaLoadout = {
    string = "CYGADBD3hSPCL9Y9gz68WcKvMAAAAAAAAAAAAAAAAAWoMbNjxMDwsMzMzMLMYMLzsMzCzM2YZmlxMjxGGGgx22MDGz2IwEAAAgFmZmZwmhxYAAYmBLDA",
    source = "Blizzard Battle.net API, US region, 2026-08-30: top 50 current-season Mythic+ Balance Druids by best keystone level, sampled across all 83 US connected realms' leaderboards. This exact build was the plurality pick (4/50, 8%); 49/50 (98%) ran Elune's Chosen overall.",
    patch = "12.1",
    sampleSize = 50,
  },
  tips = {
    "Never let Sunfire or Moonfire fall off — dot uptime is a large share of Balance's total damage, and it's also your most efficient Astral Power generation.",
    "Don't sit at capped Astral Power; spend it on Starsurge/Starfall before it overflows.",
    "Line Celestial Alignment/Incarnation up with dots already applied so the burst window isn't wasted ramping up.",
    "Use your mobility and root/stun kit (Typhoon, Mass Entanglement) proactively on movement-heavy fights.",
    "Switch to Starfire and Lunar Eclipse once you're fighting 4 or more targets rather than defaulting to Solar.",
    "Elune's Chosen can't enter Solar Eclipse at all — Lunar Calling blocks it — so don't try to force it, just lean into Lunar.",
  },
})

-- Feral ----------------------------------------------------------------
ns.GuideStore:RegisterSpec("DRUID", 103, {
  specName = "Feral",
  role = "DAMAGER",
  overview = {
    "Feral Druid is a bleed-based melee spec that builds and spends Combo Points on finishers, keeping Rip and Rake active as bleeds while weaving in Ferocious Bite and Tiger's Fury-powered burst windows.",
    "The core resource is Combo Points (0-5, or higher with talents), generated by Shred/Rake and spent on finishers like Rip and Ferocious Bite — always spend a finisher once you hit 5 rather than letting them cap, and watch your combo point count for Panther's Guile procs. Energy regeneration and bleed uptime (Rake, Rip, Thrash) are the main damage drivers — Bloodtalons was removed as a talent in Midnight, so that damage is now baseline rather than conditional on ability sequencing; Tiger's Fury uptime still matters for snapshotting Rake/Moonfire's damage-over-time value, so refresh bleeds while it's active rather than before or after.",
    "Bring Feral when you want a mobile melee spec with strong sustained bleed damage, solid stealth-openers, and good multi-dot AoE, at the cost of a rotation that punishes dropped bleeds heavily. Wildstalker leans on bleed weight and edges ahead at single target, while Druid of the Claw leans on Ferocious Bite and edges ahead in AoE.",
  },
  statPriority = {
    { stat = "primary" },
    { stat = "crit" },
    { stat = "mastery" },
    { stat = "versatility" },
    { stat = "haste" },
  },
  rotation = {
    { title = "Opener", steps = {
        { text = "Enter Prowl before combat for a guaranteed-crit opener" },
        { spellID = 1822, text = "Rake from stealth for a strong bleed and combo point" },
        { spellID = 5217, text = "Tiger's Fury while still in Prowl, so its damage buff snapshots onto the Rake you just applied" },
        { text = "Berserk (or Incarnation) to open your main cooldown window" },
        { spellID = 323764, text = "Convoke the Spirits inside that window for a burst of extra combo points and damage" },
        { spellID = 274837, text = "Feral Frenzy to build to 5 combo points and set up an instant Rip" },
        { spellID = 1079, text = "Rip once you have 5 combo points to start the primary bleed" },
        { spellID = 22568, text = "Ferocious Bite to spend combo points once Rip and Rake are in good shape" },
        { text = "From there, maintain Rake and Moonfire and fall back to Shred as your steady-state builder" },
        { text = "Opener Notes: some current builds carry a talented finisher called Chomp alongside Ferocious Bite — check your talent row and use whichever finisher your build points at" },
    }},
    { title = "Single Target", steps = {
        { spellID = 1822, text = "Rake to apply and refresh its bleed, especially from behind" },
        { text = "Thrash to keep a secondary bleed rolling" },
        { spellID = 1079, text = "Rip if it's missing or about to fall off" },
        { spellID = 22568, text = "Ferocious Bite to spend combo points once Rip and Rake are in good shape" },
        { spellID = 5221, text = "Shred as your main combo point builder while behind the target" },
        { text = "Refresh Rake and Moonfire specifically while Tiger's Fury is active to snapshot its damage buff onto them" },
    }},
    { title = "AoE", steps = {
        { spellID = 285381, text = "Primal Wrath to apply Rip to the whole pack, ideally right before Berserk/Incarnation" },
        { text = "Thrash to apply its bleed across all nearby targets" },
        { text = "Swipe as your builder once Thrash and Rip are rolling" },
        { spellID = 22568, text = "Ferocious Bite afterward for Rampant Ferocity's bonus" },
        { text = "Keep Rake and Moonfire up on as many targets as you can sustain" },
        { text = "Use Tiger's Fury and Berserk/Incarnation to power through burst AoE windows" },
    }},
    { title = "Opener Notes", steps = {
        { text = "Your hero talent choice changes your AoE builder priority: Wildstalker leans on tighter Rake uptime across targets and a lower Swipe threshold, while Druid of the Claw times Swipe and Shred around your Berserk/Incarnation buff and Sudden Ambush procs instead — check which one your loadout uses. Wildstalker's bleed weighting also edges it slightly ahead at single target, while Druid of the Claw's Ferocious Bite weighting is the stronger pick in AoE." },
    }},
  },
  cooldowns = {
    { spellID = 5217, text = "Tiger's Fury — Energy refund and damage buff on roughly a 30-second cooldown; use it with as little Energy banked as possible so none of the refund is wasted" },
    { text = "Berserk / Incarnation: Avatar of Ashamane (talent-dependent) — major burst cooldown on roughly a 2-minute timer; sync it with Tiger's Fury and Convoke the Spirits" },
    { spellID = 323764, text = "Convoke the Spirits — burst cooldown, use inside your Berserk/Incarnation window" },
    { spellID = 274837, text = "Feral Frenzy — combo point burst that sets up an instant Rip; line it up with Tiger's Fury" },
    { spellID = 22812, text = "Barkskin — defensive, reduces damage taken while still attacking" },
    { spellID = 61336, text = "Survival Instincts — major defensive cooldown for heavy incoming damage" },
  },
  consumables = {
    { slot = "Flask", text = "Flask of Alchemical Chaos (Agility)" },
    { slot = "Food", text = "A feast or personal Agility food for the encounter" },
    { slot = "Potion", text = "Tempered Potion, used inside your burst window" },
    { slot = "Weapon", text = "Ironclaw Whetstone or the current-tier weapon enchant" },
    { slot = "Enchants", text = "Max-rank Agility enchants on cloak and rings" },
    { slot = "Gems", text = "Agility/secondary stat gems in available sockets" },
  },
  gear = {
    { slot = "Head", text = "One of your tier-set slots — the four-piece bonus is built around your bleed-and-combo-point loop, worth prioritizing" },
    { slot = "Chest", text = "A large stat budget and often your other tier piece — push Critical Strike first since it scales both bleeds and finishers" },
    { slot = "Neck", text = "Usually carries a socket — favor Critical Strike, then Mastery" },
    { slot = "Ring", text = "No set bonus attached — use rings to round out Critical Strike and Mastery" },
    { slot = "Trinket", text = "One on-use trinket timed with Tiger's Fury/Berserk so its burst lands inside your window" },
    { slot = "Trinket", text = "A passive Agility stat-stick trinket to keep bleed damage strong between cooldowns" },
    { slot = "Weapon", text = "Cat Form normalizes weapon speed, so simply take the highest weapon damage item — type doesn't matter for your attacks" },
    { slot = "Feet", text = "Look for an itemization roll that keeps Critical Strike or Mastery flowing since Feral has few other stat-heavy accessory options" },
  },
  -- MID1 fallback: SimC has not yet published a MID2 (12.1) default profile
  -- for Feral, so this loadout is pulled from the MID1 (12.0) profile set
  -- instead. Swap to a MID2 profile once SimC publishes one.
  mplusLoadout = {
    string = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjZwMzMzMmtFPwyMbzYGzMDAAAALBzGMmZUzYWYmZGjZmZAAAAAAAGAAAABAz2MLNbzssBmZAWMDGAAzMAYA",
    source = "SimulationCraft default profile (credit, not endorsement of 'best')",
    patch = "12.0 (MID1, previous tier)",
  },
  -- Live top-players pull (DESIGN.md's v1.4 section), NOT SimC - see this
  -- file's header for the full methodology. The plurality build among the
  -- sample: 5/50 (10%) ran this exact code, since flex-point choices vary - but
  -- the bigger signal is that 40/50 (80%) ran Druid of the Claw overall.
  -- Reported honestly rather than dressed up as more decisive than it is.
  mplusMetaLoadout = {
    string = "CcGADBD3hSPCL9Y9gz68WcKvMAAAAAAgZmZ2MzMzMGzmx2YbGzMmZAAAAYJY2M8AmZUzYWMzMzsMmhBAAAAAwADAAAgmZZWmZmBEYBmZGgFGMAAAmZDD",
    source = "Blizzard Battle.net API, US region, 2026-08-30: top 50 current-season Mythic+ Feral Druids by best keystone level, sampled across all 83 US connected realms' leaderboards. This exact build was the plurality pick (5/50, 10%); 40/50 (80%) ran Druid of the Claw overall.",
    patch = "12.1",
    sampleSize = 50,
  },
  tips = {
    "Never let Rip or Rake fall off the target — refreshing dropped bleeds costs far more than early refreshes.",
    "Open from Prowl whenever the pull allows it for a free crit and Energy tempo.",
    "Pool Energy slightly before Tiger's Fury/Berserk so you can dump it immediately when the window opens.",
    "On cleave fights, keep your main bleeds on the priority target while using Thrash/Swipe for the rest.",
    "Don't let combo points sit at 5 without spending a finisher, and watch your combo point count for Panther's Guile procs.",
    "Refresh Rake and Moonfire specifically while Tiger's Fury is up so their damage-over-time value snapshots at its strongest.",
  },
})

-- Guardian ---------------------------------------------------------------
ns.GuideStore:RegisterSpec("DRUID", 104, {
  specName = "Guardian",
  role = "TANK",
  overview = {
    "Guardian Druid tanks in Bear Form, relying on high armor and Stamina along with Frenzied Regeneration and Barkskin-style cooldowns for damage mitigation, while Ironfur and Mangle/Thrash keep threat and physical mitigation up.",
    "The core mechanic is Rage generation from taking and dealing damage — entering Bear Form itself grants 25 Rage — with Mangle and Thrash as your main generators from there, spent on Ironfur (a stacking armor buff) to reduce physical damage and on Maul/Raze once you're above 80 Rage, without ever sitting capped at 100. Ursoc's Fury and other passives reward staying in the fight and taking hits rather than sitting still.",
    "Bring Guardian when you want a tank with high physical damage mitigation, strong self-healing through Frenzied Regeneration and Ursine Vigor-style passives, and solid AoE threat via Thrash and Swipe. Its hero talents change less than most specs': Druid of the Claw adds Ravage procs to consume on top of the core Mangle/Thrash loop, while Elune's Chosen leans on Lunar Beam uptime instead — both are viable with little rotational difference between them.",
  },
  statPriority = {
    { stat = "stamina" },
    { stat = "primary" },
    { stat = "versatility" },
    { stat = "mastery" },
    { stat = "haste" },
    { stat = "crit" },
  },
  rotation = {
    { title = "Opener", steps = {
        { spellID = 192081, text = "Ironfur as fast as possible once you're in melee range" },
        { spellID = 33917, text = "Mangle and Thrash kept on cooldown from there as your main Rage generators" },
        { text = "Consume Ravage procs the moment they appear, on Druid of the Claw" },
        { spellID = 204066, text = "Lunar Beam on cooldown alongside Incarnation: Guardian of Ursoc, on Elune's Chosen" },
    }},
    { title = "Single Target", steps = {
        { spellID = 428545, text = "Moonfire (Guardian variant) kept up on the target" },
        { text = "Thrash on cooldown even at single target, for the bleed and extra mitigation" },
        { spellID = 33917, text = "Mangle on cooldown for threat and Rage generation" },
        { spellID = 192081, text = "Keep at least 1 stack of Ironfur up at all times" },
        { text = "Raze once you're above 80 Rage" },
        { text = "Maul when you want to spend Rage offensively" },
        { text = "Moonfire/Swipe as filler when nothing else is due" },
    }},
    { title = "AoE", steps = {
        { text = "Thrash the moment the pack reaches melee range" },
        { spellID = 33917, text = "Mangle on cooldown" },
        { text = "Raze as your multi-target Rage dump" },
        { spellID = 192081, text = "Maintain Ironfur stacks across pulls, especially before damage lands" },
        { spellID = 102558, text = "Incarnation: Guardian of Ursoc (talent) for extended high-threat AoE windows" },
    }},
    { title = "Mitigation", steps = {
        { spellID = 192081, text = "Ironfur to stack physical mitigation, especially before an incoming hit or swing" },
        { spellID = 22812, text = "Barkskin — your short, first-line defensive for smaller spikes" },
        { spellID = 61336, text = "Survival Instincts — 50% damage reduction for 6 seconds, save for the heaviest spikes" },
        { spellID = 22842, text = "Frenzied Regeneration to heal through sustained damage" },
        { text = "Rotate Frenzied Regeneration, Incarnation, and defensive trinkets across a fight rather than using them all together" },
        { text = "Don't let Rage sit unused — convert it into Ironfur before big hits rather than after" },
    }},
    { title = "Opener Notes", steps = {
        { text = "Guardian shares its two hero talent trees with the specs next to it in the web: Elune's Chosen (also Balance's) and Druid of the Claw (also Feral's) — check which one your loadout uses, since SimC's current profile for Guardian does not yet branch its action list on this the way it does for Balance and Feral. In practice the difference is small: Druid of the Claw adds Ravage procs to consume alongside the core Mangle/Thrash loop, while Elune's Chosen leans on Lunar Beam uptime instead — both are viable with little rotational change either way." },
    }},
  },
  cooldowns = {
    { spellID = 22812, text = "Barkskin — your short, first-line defensive; use it proactively before predictable damage" },
    { spellID = 61336, text = "Survival Instincts — 50% damage reduction for 6 seconds, save for the heaviest damage spikes" },
    { spellID = 102558, text = "Incarnation: Guardian of Ursoc (talent) — major cooldown for extended tough phases" },
    { spellID = 22842, text = "Frenzied Regeneration — self-healing, use when sustained damage is outpacing external healing" },
    { text = "Rotate these and your defensive trinkets across a fight rather than using them all together" },
  },
  consumables = {
    { slot = "Flask", text = "Flask of Alchemical Chaos (Agility, tank stat variant)" },
    { slot = "Food", text = "A feast or personal Stamina/Agility food for the encounter" },
    { slot = "Potion", text = "Tempered Potion or a Stamina/defensive potion for survival cooldowns" },
    { slot = "Weapon", text = "Ironclaw Whetstone or the current-tier weapon enchant" },
    { slot = "Enchants", text = "Max-rank Stamina/Agility enchants on cloak and rings" },
    { slot = "Gems", text = "Stamina/Agility gems in available sockets" },
  },
  gear = {
    { slot = "Head", text = "One of your tier-set slots — the four-piece bonus strengthens your Ironfur/Rage loop, worth prioritizing" },
    { slot = "Chest", text = "A large stat budget and often your other tier piece — balance Stamina for your health pool against Versatility for flat mitigation" },
    { slot = "Neck", text = "Usually carries a socket — lean Versatility first, then Mastery" },
    { slot = "Ring", text = "No set bonus attached — use rings to fill out Versatility and Mastery wherever your gear is light" },
    { slot = "Trinket", text = "One trinket built around avoidance, armor, or a defensive proc rather than pure Agility, to smooth out incoming spikes" },
    { slot = "Trinket", text = "A second trinket that adds Stamina or a passive mitigation effect so survivability doesn't get sacrificed entirely for threat" },
    { slot = "Weapon", text = "Bear Form normalizes weapon speed, so take the highest weapon damage item available regardless of type" },
    { slot = "Waist", text = "An easy slot to fill in an extra gem toward whichever secondary — Versatility or Mastery — your build is short on" },
  },
  -- MID1 fallback: SimC has not yet published a MID2 (12.1) default profile
  -- for Guardian, so this loadout is pulled from the MID1 (12.0) profile set
  -- instead. Swap to a MID2 profile once SimC publishes one.
  mplusLoadout = {
    string = "CgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmxsYmZMzmZZgZbZgxMMaimZmFzMzMLjZeADAAAAgZYGLzAAAAQNzysMzMDAgFMDgFzgBsYZbAwMbwA",
    source = "SimulationCraft default profile (credit, not endorsement of 'best')",
    patch = "12.0 (MID1, previous tier)",
  },
  -- Live top-players pull (DESIGN.md's v1.4 section), NOT SimC - see this
  -- file's header for the full methodology. The plurality build among the
  -- sample: 4/50 (8%) ran this exact code, since flex-point choices vary - but
  -- the bigger signal is that 49/50 (98%) ran Elune's Chosen overall. Reported
  -- honestly rather than dressed up as more decisive than it is.
  mplusMetaLoadout = {
    string = "CgGADBD3hSPCL9Y9gz68WcKvMAAAAAAAAAAAAgZmxsYmZMziZxMmZZZgZzwoJamZWmZmZmlxMAAAAAAMzsZALbzMYMLDgpAAAAbYmHAYxYYALWAYmBwA",
    source = "Blizzard Battle.net API, US region, 2026-08-30: top 50 current-season Mythic+ Guardian Druids by best keystone level, sampled across all 83 US connected realms' leaderboards. This exact build was the plurality pick (4/50, 8%); 49/50 (98%) ran Elune's Chosen overall.",
    patch = "12.1",
    sampleSize = 50,
  },
  tips = {
    "Keep Ironfur stacked proactively rather than reactively — mitigation applied before the hit lands is what matters.",
    "Don't neglect Thrash even on single-target fights; its bleed adds meaningful sustained damage and threat.",
    "Use Frenzied Regeneration to smooth out damage between healer cooldowns rather than saving it indefinitely.",
    "Pool Rage slightly before a telegraphed damage spike so you can pump Ironfur right before it lands.",
    "Bear Form itself grants 25 Rage on entry — use that head start rather than opening with an empty Rage bar.",
    "Don't let Rage sit capped at 100; Raze above 80 Rage is a good release valve outside of Ironfur upkeep.",
    "On Druid of the Claw, consume Ravage procs as soon as they appear rather than finishing your current cast first.",
  },
})

-- Restoration --------------------------------------------------------------
-- Revised for 12.1 (Curse of Ula'tek) from Blizzard patch-note content
-- reached via search summaries; the official article could not be fetched
-- directly from this environment, so the specific numbers/mechanics below
-- are UNVERIFIED against the source page and should be treated as
-- provisional pending direct confirmation. No SimC profile exists for this
-- spec, so it is NOT SimC-cross-checked — see the mplusLoadout note in the
-- header above. Innervate is redesigned (now a flat mana-regen effect
-- instead of making spells free); Abundance gets a clearer Regrowth-
-- efficiency threshold and Swiftmend is restored to a punchier single-target
-- emergency heal; Overgrowth's interaction with Nature's Swiftness was
-- changed.
ns.GuideStore:RegisterSpec("DRUID", 105, {
  specName = "Restoration",
  role = "HEALER",
  overview = {
    "Restoration Druid heals primarily through layered heal-over-time effects (Rejuvenation, Lifebloom, Wild Growth) that cover the whole raid, supplemented by direct heals like Regrowth for spot healing and Swiftmend for instant emergency top-ups.",
    "The core mechanic is HoT uptime and Efflorescence/Wild Growth-style group coverage: keep Efflorescence down under the group, Lifebloom on the tank (or primary target), and a second Lifebloom plus 1-2 self-cast Rejuvenations on yourself to proc Photosynthesis' bonus healing. Keeping roughly 5 Rejuvenations rolling raid-wide holds the Abundance buff, which is also what lets Regrowth become a cheaper, higher-crit direct heal once a target's active HoT count drops below its threshold.",
    "Patch 12.1 is mostly a usability pass rather than a rework: Innervate no longer makes your spells free, instead restoring a flat 25% of the target's maximum mana over 8 seconds; Swiftmend hits harder as an emergency single-target tool again; and Overgrowth's interaction with Nature's Swiftness was changed so that it lets Nature's Swiftness apply Lifebloom, Rejuvenation, and Wild Growth's HoT to your next Regrowth target in one cast.",
    "Bring Restoration when you want a mobile healer with strong raid-wide HoT coverage, good mana efficiency at moderate haste, and useful utility (Innervate, combat rebirth, roots/CC) beyond pure healing throughput.",
  },
  statPriority = {
    { stat = "primary" },
    { stat = "haste", note = "smooths HoT ticks and cast times" },
    { stat = "mastery" },
    { stat = "crit" },
    { stat = "versatility" },
  },
  rotation = {
    { title = "Priorities", steps = {
        { spellID = 33763, text = "Lifebloom on the tank (or primary target) to maintain its stack and bloom value" },
        { text = "A second Lifebloom on yourself, plus 1-2 self-cast Rejuvenations, to proc Photosynthesis' bonus healing" },
        { spellID = 145205, text = "Efflorescence kept down under the group as close to constantly as you can" },
        { spellID = 774, text = "Rejuvenation spread across roughly 5 targets to hold the Abundance buff" },
        { spellID = 48438, text = "Wild Growth on cooldown for burst group-wide healing" },
        { spellID = 18562, text = "Swiftmend for instant emergency healing, followed immediately by a Rejuvenation or Regrowth on the same target — 12.1 restored some of its punch as a single-target tool" },
        { spellID = 8936, text = "Regrowth for efficient spot healing — Abundance now gives a clear signal (a HoT-count threshold on the target) for when it's the efficient choice, rather than a fuzzy one" },
    }},
    { title = "Cooldown usage", steps = {
        { spellID = 740, text = "Tranquility for a strong raid-wide healing burst during heavy damage" },
        { spellID = 33891, text = "Incarnation: Tree of Life (talent) to extend and empower your HoT-based healing" },
        { spellID = 197721, text = "Flourish (talent) to extend all active HoTs during a big damage phase" },
        { spellID = 29166, text = "Innervate on yourself or another mana-hungry healer during a long fight — redesigned in 12.1 to a flat mana-regen effect rather than free casts, so use it for sustained mana pressure rather than to enable a burst of spam-casting" },
        { spellID = 132158, text = "If talented into Overgrowth, use Nature's Swiftness on Regrowth when you want one cast to also apply Lifebloom, Rejuvenation, and Wild Growth to the target" },
        { text = "Pre-HoT the raid ahead of known damage rather than reacting purely after it lands" },
    }},
    { title = "Opener Notes", steps = {
        { text = "Restoration's two hero talent trees are Wildstalker (also Feral's) and Keeper of the Grove (also Balance's); unlike most specs, the healing rotation itself doesn't meaningfully change between them — SimC still has no Restoration profile to branch a rotation from, but guide-site consensus agrees there's little to differentiate here, so pick based on the passive/utility flavor you want" },
    }},
  },
  cooldowns = {
    { spellID = 740, text = "Tranquility — raid-wide burst heal, use for a scripted heavy damage phase" },
    { spellID = 33891, text = "Incarnation: Tree of Life (talent) — major cooldown, amplifies HoT output for its duration" },
    { spellID = 197721, text = "Flourish (talent) — extends active HoTs, pairs well with Tranquility/Incarnation" },
    { spellID = 132158, text = "Nature's Swiftness — makes your next heal instant, use for an emergency or to weave in while moving; with the Overgrowth talent, pair it with Regrowth to spread three HoTs in one global" },
    { spellID = 22812, text = "Barkskin — personal defensive, reduces damage taken" },
  },
  consumables = {
    { slot = "Flask", text = "Flask of Alchemical Chaos (Intellect)" },
    { slot = "Food", text = "A feast or personal Intellect food for the encounter" },
    { slot = "Potion", text = "Tempered Potion or a healing-oriented potion for a big damage phase" },
    { slot = "Weapon", text = "Not applicable" },
    { slot = "Enchants", text = "Max-rank Intellect enchants on cloak and rings" },
    { slot = "Gems", text = "Intellect/secondary stat gems in available sockets" },
  },
  gear = {
    { slot = "Head", text = "One of your tier-set slots — the four-piece bonus adds real throughput to your HoT coverage, worth prioritizing" },
    { slot = "Chest", text = "A large stat budget and often your other tier piece — lean Haste first to smooth HoT ticks and cast times" },
    { slot = "Neck", text = "Usually carries a socket — favor Haste, then Mastery" },
    { slot = "Ring", text = "No set bonus attached — use rings to round out Haste and Mastery" },
    { slot = "Trinket", text = "One mana-efficiency or passive-throughput trinket to stretch your HoT-based healing across a long fight" },
    { slot = "Trinket", text = "A second trinket built around a burst-healing proc or on-use effect you can align with Tranquility/Incarnation" },
    { slot = "Weapon", text = "Take the highest weapon damage staff or one-hand-plus-off-hand — Restoration's healing scales off spellpower and stats, not weapon type" },
    { slot = "Off-hand", text = "A caster off-hand leaning Haste keeps your HoT rolling and cast-heavy spot healing smooth" },
  },
  -- Live top-players pull (DESIGN.md's v1.4 section), NOT SimC - see this
  -- file's header for the full methodology. The plurality build among the
  -- sample: 2/50 (4%) ran this exact code, since flex-point choices vary - but
  -- the bigger signal is that 42/50 (84%) ran Wildstalker overall. Reported
  -- honestly rather than dressed up as more decisive than it is.
  mplusMetaLoadout = {
    string = "CkGADBD3hSPCL9Y9gz68WcKvMMMmZZMjZmxsNMMzsMsZbGAAAAAAAAAAsMoZzw0MjZwsYmZmZZGegZAAAAAAAwAAQAAAz2MbNbzsYjxMDMzCoZAAmZAYA",
    source = "Blizzard Battle.net API, US region, 2026-08-30: top 50 current-season Mythic+ Restoration Druids by best keystone level, sampled across all 83 US connected realms' leaderboards. This exact build was the plurality pick (2/50, 4%); 42/50 (84%) ran Wildstalker overall.",
    patch = "12.1",
    sampleSize = 50,
  },
  tips = {
    "Keep Rejuvenation spread across as many raid members as you can sustainably maintain — it's your mana-efficient floor.",
    "Don't let Lifebloom fall off the tank; refreshing before it blooms preserves its passive healing bonus.",
    "Pre-HoT the raid before known damage windows so Wild Growth/Tranquility land on top of existing coverage.",
    "Use Swiftmend on cooldown-permitting emergencies rather than saving it indefinitely — 12.1 made it hit harder again, so it's worth using regularly.",
    "Innervate no longer frees your casts in 12.1 — it's now a straightforward 25%-of-max-mana-over-8-seconds regen effect, so treat it as sustained mana relief rather than a burst-casting cooldown.",
    "Keep a second Lifebloom on yourself with 1-2 self-cast Rejuvenations rolling to proc Photosynthesis' extra healing.",
    "Swiftmend, Wild Growth, and other efficient low-cost heals are cheap enough to use liberally — save full Regrowth hardcasts for when you actually need the burst.",
    "Keep Efflorescence down under the group as close to permanently as you can; it's easy to let it lapse while moving.",
  },
})
