local ADDON, ns = ...

-- SpecSage guide data: Demon Hunter
-- Content targets Midnight (patch 12.1). Specs below with an `mplusLoadout`
-- field have that talent string (only) cross-checked against
-- SimulationCraft's public profiles (github.com/simulationcraft/simc,
-- GPLv3) as of patch 12.1; specs without one have no such reference.
-- Rotation/overview/tips/gear prose throughout this file is hand-authored
-- and was reviewed for Midnight ability changes, not derived from or
-- checked against SimC's APLs, and was not re-verified against current
-- tuning this pass — EXCEPT Havoc (577) and Vengeance (581),
-- which each gained an `mplusMetaLoadout` (DESIGN.md's v1.4 section) this
-- pass: pulled live from Blizzard's own Battle.net Game Data API
-- (client-credentials OAuth, US region) rather than SimC, on 2026-08-30.
-- Methodology: every current-season Mythic+ leaderboard (8-dungeon pool,
-- period 1078) across all 83 US connected realms was scanned (top 20 groups
-- per realm/dungeon) for each spec's group members; the top-observed-keystone
-- characters (up to 50 per spec) had their live `specializations` looked up
-- for their active loadout's `talent_loadout_code`. See each field's own
-- `source` comment for the resulting distribution.
-- Both specs' overview/rotation were also corrected this pass, confirmed
-- against SimC's current `midnight` branch profiles (zero hits for the old
-- terms, dozens for the new) and Blizzard's own forums: Havoc's Momentum
-- talent is gone, replaced by Inertia (a Fel Rush/Vengeful Retreat trigger
-- your next action consumes), and Fel Barrage was removed outright, leaving
-- Glaive Tempest as the AoE talent; Vengeance's resource was unified into
-- Fury (not a separate "Pain" resource) long before this patch, and Shear
-- was replaced by Fracture as the baseline Fury/Soul Fragment generator.
-- This is community-maintained, conventional guidance (keep-it-simple stat
-- priorities, long-standing rotation patterns) and is NOT a claim of
-- sim-perfect or bleeding-edge optimal play.
-- To edit: find the RegisterSpec(...) block for the spec you want to change
-- and edit the table in place. To add a new tip/step, insert a new entry in
-- the relevant array. Keep this file data-only — no logic beyond the calls
-- below. See DESIGN.md "Guide data schema" for the full table shape.

-- Consumables/gear pass (2026-09-01, same session as the rotation-guide
-- enrichment above): every spec's Flask/Food/Potion/Augment Rune entries
-- were refreshed to the current Season 2 consumable system (stat-matched
-- "Flask of Tempered <X>" flasks rather than the old generic "Flask of
-- Alchemical Chaos" placeholder used everywhere; current food/potion/
-- augment-rune names), and specs with concrete Season 2 tier-set 2pc/4pc
-- effects (per the same guide-site sources) had that detail appended to
-- their Head gear entry - specs the sources gave no specific tier numbers
-- for were left with their existing generic tier-set mention rather than
-- inventing specifics. statPriority was deliberately NOT touched in this
-- pass either: stat-priority orderings are exactly the kind of contested
-- judgment call (not a mechanically-determined fact) this repo's policy
-- says to flag rather than silently adopt, and neither source gave a
-- confident order clearly better than what already shipped.

-- Devourer added (2026-09-02): Demon Hunter's third spec, specID 1480 (see
-- SimC's engine/dbc/generated/sc_specialization_data.inc). See that spec's
-- own block below for full sourcing notes - unlike Havoc/Vengeance above,
-- this is a from-scratch SimC-only pass with no prior community consensus
-- to check it against, since the spec is brand new this pass discovered it.
if not ns.GuideStore then return end

-- Havoc ----------------------------------------------------------------
ns.GuideStore:RegisterSpec("DEMONHUNTER", 577, {
  specName = "Havoc",
  role = "DAMAGER",
  overview = {
    "Havoc Demon Hunter is a fast, highly mobile melee spec that generates and spends Fury to fuel Chaos Strike/Annihilate and Blade Dance, with Eye Beam and Metamorphosis providing large periodic burst windows.",
    "The core resource is Fury, generated by Demon's Bite/Fel Rush-style abilities and Felblade, and spent on Chaos Strike (or Annihilate while transformed) for damage and Blade Dance/Death Sweep for cleave. Inertia (Momentum's replacement) rewards staying mobile: Fel Rush or Vengeful Retreat sets up a trigger that your next action consumes for a damage buff. On the Aldrachi Reaver hero talent, Reaver's Glaive empowers your next Blade Dance and Chaos Strike; Fel-Scarred swaps that combo for Sigil of Doom and Student of Suffering instead, and generates Fury noticeably faster, so it rewards spending more aggressively.",
    "Bring Havoc when you want extremely high mobility, strong burst windows via Eye Beam and Metamorphosis, and good AoE where Glaive Tempest now procs passively off a 3+ target Blade Dance rather than needing its own button, in exchange for a rotation that rewards careful Fury management.",
  },
  statPriority = {
    { stat = "primary" },
    { stat = "crit" },
    { stat = "haste" },
    { stat = "mastery" },
    { stat = "versatility" },
  },
  rotation = {
    { title = "Opener", steps = {
        { text = "Immolation Aura while closing the gap to start building Fury" },
        { text = "The Hunt to close in and, on Aldrachi Reaver, proc Reaver's Glaive" },
        { spellID = 198013, text = "Eye Beam to enter Demon Form through the Demonic talent" },
        { spellID = 162794, text = "Annihilate to spend Fury inside Demon Form" },
        { text = "Death Sweep x2 (via Eternal Hunt) to close out the opener" },
        { text = "Opener Notes: Havoc splits along the Aldrachi Reaver and Fel-Scarred hero trees — both keep this opener shape, but Fel-Scarred replaces the Reaver's Glaive step with Sigil of Doom to proc Student of Suffering instead, and generates Fury fast enough to justify spending more aggressively throughout" },
    }},
    { title = "Single Target", steps = {
        { text = "Reaver's Glaive first on Aldrachi Reaver — it empowers your next Blade Dance and Chaos Strike" },
        { text = "Blade Dance / Death Sweep on cooldown for cleave-capable damage and defense" },
        { spellID = 162794, text = "Chaos Strike (or Annihilate in Metamorphosis) to spend Fury on your hardest-hitting attack" },
        { spellID = 232893, text = "Felblade to generate Fury and keep Army Unto Oneself active" },
        { spellID = 198013, text = "Eye Beam on cooldown, ideally lined up with other cooldowns" },
        { spellID = 258860, text = "Essence Break (talent) between Eye Beam casts to debuff the target for extra Chaos Strike/Annihilation damage" },
        { text = "Don't cap Fury — spend before it overflows, more aggressively on Fel-Scarred where generation runs faster" },
    }},
    { title = "AoE", steps = {
        { spellID = 198013, text = "Eye Beam is a top AoE priority, not just a single-target cooldown" },
        { text = "Blade Dance / Death Sweep to hit all nearby enemies — Glaive Tempest now procs passively once it connects with 3+ targets, it's no longer its own button" },
        { spellID = 258920, text = "Immolation Aura for sustained cleave damage and Fury generation" },
        { text = "Chaos Strike/Annihilate still hits cleave targets via Chaos Theory-style talents" },
        { text = "Use Fel Rush/Throw Glaive to tag additional targets while repositioning" },
    }},
  },
  cooldowns = {
    { spellID = 191427, text = "Metamorphosis — major burst cooldown with extra mobility; if you have Chaotic Transformation, make sure both Blade Dance and Eye Beam are on cooldown before pressing it" },
    { spellID = 198013, text = "Eye Beam — strong AoE/cleave burst on a 30-second cooldown, and extends Metamorphosis through the Demonic talent" },
    { text = "The Hunt (talent) — gap closer with burst damage on roughly a 1-minute cooldown, use to open a fight or reposition into a pack" },
    { spellID = 258860, text = "Essence Break (talent) — debuffs the target for bonus Chaos Strike/Annihilation damage, use between Eye Beam casts" },
    { spellID = 198589, text = "Blur — defensive, reduces damage taken and helps with kiting" },
    { text = "Netherwalk — brief immunity/evasion, use to dodge an unavoidable burst hit" },
  },
  consumables = {
    { slot = "Flask", text = "Flask of Tempered Aggression — matches this spec's top secondary; Flask of Alchemical Chaos is the flex pick if your stat weights are close" },
    { slot = "Food", text = "Loa's Gathering or Feast of Knowledge for raid (Stamina + your highest secondary); Hearty Venom-Spiced Cutlets or Puffer Plate for Mythic+/personal (prefer the Hearty version for death persistence)" },
    { slot = "Potion", text = "Tempered Potion, used inside Metamorphosis. Liquid Luster (builds Versatility over 30s) is a strong ramp/M+ alternative, Potion of Unwavering Focus if you want a pure single-target pick instead; always carry Concentrated Silvermoon Health Potions for the emergency heal." },
    { slot = "Weapon", text = "Ironclaw Whetstone or the current-tier weapon enchant" },
    { slot = "Enchants", text = "Max-rank Agility enchants on cloak and rings" },
    { slot = "Gems", text = "Agility/secondary stat gems in available sockets" },
    { slot = "Augment Rune", text = "Crystallized Augment Rune (1-hour primary stat) for progression pulls and high keys; the reusable Ethereal Augment Rune the rest of the time" },
  },
  gear = {
    { slot = "Head", text = "One of your tier-set slots — the four-piece bonus reinforces your Fury/burst-window engine, worth prioritizing. Season 2's set bonus specifically: Blade Dance, Chaos Strike, and Essence Break all hit harder, and the four-piece adds a bigger, longer Essence Break debuff." },
    { slot = "Chest", text = "A large stat budget and often your other tier piece — push Critical Strike first for Chaos Strike/Blade Dance payoff" },
    { slot = "Neck", text = "Usually carries a socket — favor Critical Strike, then Haste" },
    { slot = "Ring", text = "No set bonus attached — use rings to round out Critical Strike and Haste" },
    { slot = "Trinket", text = "One on-use trinket timed with Metamorphosis/Eye Beam so its burst overlaps your biggest window" },
    { slot = "Trinket", text = "A passive Agility stat-stick trinket to keep pressure up between cooldowns" },
    { slot = "Weapon", text = "Warglaives (fast one-handers) fit Havoc's dual-wield Fury generation — take the pair with the highest weapon damage" },
    { slot = "Off-hand", text = "Match your off-hand glaive's secondary stats to your main-hand's Critical Strike lean" },
  },
  mplusLoadout = {
    string = "CEkAAAAAAAAAAAAAAAAAAAAAAYAzMzmxMzMmZmMmZAAAAAAAzyDMmtZYmxyMzYZm5BmZWmZWGjBWmFzYY200wMjhNAAAAAAAAmZwAAAAwA",
    source = "SimulationCraft default profile (credit, not endorsement of 'best')",
    patch = "12.1",
  },
  -- Live top-players pull (DESIGN.md's v1.4 section), NOT SimC - see this
  -- file's header for the full methodology. The plurality build among the
  -- sample: 16/50 (32%) ran this exact code, since flex-point choices vary -
  -- but the bigger signal is that 47/50 (94%) ran Fel-Scarred overall. Reported
  -- honestly rather than dressed up as more decisive than it is.
  mplusMetaLoadout = {
    string = "CEkAp/epaxe7D0A403L+Tvk0iamZGzMz2MmZmxYmMmZAAAAAAAzixsNDzMwMWmZmZYmBzyALzmZMMLaaMzMmxGAAAwAAQAwMDGACAAM",
    source = "Blizzard Battle.net API, US region, 2026-08-30: top 50 current-season Mythic+ Havoc Demon Hunters by best keystone level, sampled across all 83 US connected realms' leaderboards. This exact build was the plurality pick (16/50, 32%); 47/50 (94%) ran Fel-Scarred overall.",
    patch = "12.1",
    sampleSize = 50,
  },
  tips = {
    "Don't let Fury sit capped — that's wasted generation from Demon's Bite/Fel Rush.",
    "Use Vengeful Retreat/Fel Rush proactively for both Fury and repositioning, not only when out of range.",
    "Line up Eye Beam and Metamorphosis together when your build allows for a stacked burst window.",
    "Keep an eye on Blade Dance/Death Sweep cooldown — it's both damage and a defensive parry chance, so don't hold it too long.",
    "On Aldrachi Reaver, open with Reaver's Glaive before Blade Dance and Chaos Strike so both land empowered.",
    "Fel-Scarred generates Fury much faster than Aldrachi Reaver — lean into spending it rather than holding it the way you would on Reaver.",
    "Glaive Tempest no longer needs its own button — it procs on its own once Blade Dance connects with 3 or more targets.",
  },
})

-- Vengeance --------------------------------------------------------------
ns.GuideStore:RegisterSpec("DEMONHUNTER", 581, {
  specName = "Vengeance",
  role = "TANK",
  overview = {
    "Vengeance Demon Hunter tanks by building Fury from taking and dealing damage, spending it on Soul Cleave for both damage and self-healing, while Fiery Brand and Demon Spikes provide strong scheduled mitigation.",
    "The core mechanic is Fury, generated passively by taking damage and by Fracture — the baseline generator here since Midnight, having replaced Shear — and spent on Soul Cleave which heals you based on damage dealt. Soul Fragments (from Fracture/Fel Devastation-style abilities) further empower Soul Cleave's healing. Reaver's Glaive on the Aldrachi Reaver hero talent chains into an empowered Fracture and then an empowered Soul Cleave, both hitting harder than usual, so working that Art of the Glaive combo into the loop matters as much as the raw Fury math.",
    "Bring Vengeance when you want a tank with strong self-sustain through Soul Cleave healing, good burst AoE threat via Spirit Bomb/Fel Devastation, and a scheduled mitigation cooldown (Demon Spikes) that's easy to weave into any rotation. Aldrachi Reaver plays around that Reaver's Glaive combo, while Annihilator instead builds Voidfall stacks that you spend at 3.",
  },
  statPriority = {
    { stat = "stamina" },
    { stat = "primary" },
    { stat = "versatility" },
    { stat = "mastery" },
    { stat = "haste" },
    { stat = "crit" },
  },
  rotation = {
    { title = "Opener", steps = {
        { spellID = 203720, text = "Demon Spikes to establish your baseline mitigation before the pull lands" },
        { text = "Reaver's Glaive to start the Art of the Glaive combo, on Aldrachi Reaver" },
        { spellID = 263642, text = "Empowered Fracture next for a 10% bonus" },
        { spellID = 228477, text = "Empowered Soul Cleave to finish the combo for a 20% bonus" },
        { spellID = 204596, text = "Sigil of Flame woven in to debuff the pull and pick up extra Fury" },
        { text = "Fiery Brand woven in early to start its damage-reduction window" },
        { text = "Opener Notes: Vengeance splits along the Aldrachi Reaver and Annihilator hero trees — Aldrachi Reaver opens with the Reaver's Glaive combo above, while Annihilator instead opens by building Voidfall stacks to spend at 3; Sigil of Flame or Sigil of Spite both make good precombat openers depending on your build" },
    }},
    { title = "Single Target", steps = {
        { text = "Reaver's Glaive first, unless you're already mid-combo (Aldrachi Reaver)" },
        { spellID = 263642, text = "Fracture, then Soul Cleave right behind it — Fracture empowered by the combo hits for a 10% bonus, Soul Cleave for 20%" },
        { spellID = 228477, text = "Soul Cleave to spend Fury for damage and strong self-healing outside the combo" },
        { text = "Sigil of Spite to trigger Art of the Glaive whenever Reaver's Glaive isn't up" },
        { text = "Fiery Brand near 2 charges, or sooner for a scripted mechanic" },
        { text = "Soul Carver, ideally with Fiery Brand already active" },
        { text = "Immolation Aura on cooldown for passive AoE damage and Fury generation" },
        { spellID = 263642, text = "Fracture again once it's near 2 charges — don't let it sit capped" },
        { spellID = 247454, text = "Spirit Bomb at 5-6 Soul Fragments" },
        { spellID = 228477, text = "Soul Cleave at roughly 3 Soul Fragments otherwise" },
        { spellID = 212084, text = "Fel Devastation for burst damage and healing, ideally with Fiery Brand up" },
        { text = "Felblade/Throw Glaive as fillers when nothing else is ready" },
    }},
    { title = "AoE", steps = {
        { text = "The priority stays close to single-target — generating as many Soul Fragments as possible becomes the goal, since both Spirit Bomb and Soul Cleave scale with target count" },
        { spellID = 263642, text = "Fracture to build Soul Fragments quickly across a pack" },
        { spellID = 204596, text = "Sigil of Flame to hit and debuff a group of adds on pull" },
        { spellID = 247454, text = "Spirit Bomb (talent) to detonate 5-6 Soul Fragments across the pack, in place of Soul Cleave" },
        { text = "Immolation Aura on cooldown, it hits everything nearby passively" },
        { spellID = 212084, text = "Fel Devastation for strong AoE burst and self-healing" },
    }},
    { title = "Mitigation", steps = {
        { spellID = 203720, text = "Demon Spikes as your maintenance defensive — use proactively and never let its charges sit at cap" },
        { text = "Fiery Brand to reduce damage taken from the branded target significantly" },
        { spellID = 228477, text = "Soul Cleave for reliable self-healing on top of raw damage reduction tools" },
        { spellID = 187827, text = "Metamorphosis (tank form) for a major defensive/offensive cooldown" },
        { text = "Alternate Metamorphosis and Fiery Brand so at least one is active whenever possible, rather than stacking both together" },
    }},
  },
  cooldowns = {
    { text = "Fiery Brand — major defensive, marks the target for reduced damage taken from it; alternate it with Metamorphosis so one of the two is up whenever possible" },
    { spellID = 187827, text = "Metamorphosis — major cooldown, boosts survivability and damage for its duration" },
    { spellID = 203720, text = "Demon Spikes — frequent mitigation charge, use proactively rather than reactively; keep it recharging rather than sitting at cap" },
    { text = "Soul Carver — burst damage cooldown, line it up with Fiery Brand when you can" },
    { spellID = 212084, text = "Fel Devastation — damage + self-healing cooldown, use when a healing boost is valuable, ideally with Fiery Brand up" },
  },
  consumables = {
    { slot = "Flask", text = "Flask of Tempered Versatility — matches this spec's top secondary; Flask of Alchemical Chaos is the flex pick if your stat weights are close" },
    { slot = "Food", text = "Loa's Gathering or Feast of Knowledge for raid (Stamina + your highest secondary); Hearty Venom-Spiced Cutlets or Puffer Plate for Mythic+/personal (prefer the Hearty version for death persistence)" },
    { slot = "Potion", text = "Tempered Potion or a Stamina/defensive potion for survival cooldowns. Liquid Luster (builds Versatility over 30s) is a strong ramp/M+ alternative, Potion of Unwavering Focus if you want a pure single-target pick instead; always carry Concentrated Silvermoon Health Potions for the emergency heal." },
    { slot = "Weapon", text = "Ironclaw Whetstone or the current-tier weapon enchant" },
    { slot = "Enchants", text = "Max-rank Stamina/Agility enchants on cloak and rings" },
    { slot = "Gems", text = "Stamina/Agility gems in available sockets" },
    { slot = "Augment Rune", text = "Crystallized Augment Rune (1-hour primary stat) for progression pulls and high keys; the reusable Ethereal Augment Rune the rest of the time" },
  },
  gear = {
    { slot = "Head", text = "One of your tier-set slots — the four-piece bonus strengthens your Fury/Soul Cleave self-healing loop, worth prioritizing" },
    { slot = "Chest", text = "A large stat budget and often your other tier piece — balance Stamina for your health pool against Versatility for flat mitigation" },
    { slot = "Neck", text = "Usually carries a socket — lean Versatility first, then Mastery" },
    { slot = "Ring", text = "No set bonus attached — use rings to fill out Versatility and Mastery wherever your gear is light" },
    { slot = "Trinket", text = "One trinket built around avoidance, armor, or a defensive proc rather than pure Agility, to smooth out incoming spikes" },
    { slot = "Trinket", text = "A second trinket that adds Stamina or a passive mitigation effect so Soul Cleave healing isn't your only cushion" },
    { slot = "Weapon", text = "Warglaives fit Vengeance's dual-wield Fury generation — take the pair with the highest weapon damage" },
    { slot = "Waist", text = "An easy slot to fill in an extra gem toward whichever secondary — Versatility or Mastery — your build is short on" },
  },
  mplusLoadout = {
    string = "CUkAAAAAAAAAAAAAAAAAAAAAAAAYMzMjZmZkZmZY2MzMjBjZGzYmZGDzYmx2YmtxAAAAAAAABMzM2AAAAwgxMzMzSbzMzAgBAAAgB",
    source = "SimulationCraft default profile (credit, not endorsement of 'best')",
    patch = "12.1",
  },
  -- Live top-players pull (DESIGN.md's v1.4 section), NOT SimC - see this
  -- file's header for the full methodology. The plurality build among the
  -- sample: 3/50 (6%) ran this exact code, since flex-point choices vary - but
  -- the bigger signal is that 50/50 (100%) ran Annihilator overall. Reported
  -- honestly rather than dressed up as more decisive than it is.
  mplusMetaLoadout = {
    string = "CUkAp/epaxe7D0A403L+Tvk0iCAYMzMjhZkZmBWMjZwMjZGz8AzMzYYmZmx2YGjxMAAAAAAACYmZsBAAAgBmZmZml2mZmBAzAAAAYA",
    source = "Blizzard Battle.net API, US region, 2026-08-30: top 50 current-season Mythic+ Vengeance Demon Hunters by best keystone level, sampled across all 83 US connected realms' leaderboards. This exact build was the plurality pick (3/50, 6%); 50/50 (100%) ran Annihilator overall.",
    patch = "12.1",
    sampleSize = 50,
  },
  tips = {
    "Use Demon Spikes proactively before damage lands — its charges regenerate, so don't hoard them.",
    "Time Fiery Brand for the highest sustained-damage portion of the fight for maximum value.",
    "Soul Cleave is both your main spender and your primary self-heal — don't neglect it while chasing pure damage.",
    "Keep Immolation Aura on cooldown even outside AoE — the passive damage and Fury generation add up.",
    "Never let Fracture sit at max charges — spend it into Soul Cleave or Spirit Bomb before it caps.",
    "On Aldrachi Reaver, open every Art of the Glaive combo with Reaver's Glaive so both the Fracture and Soul Cleave that follow land empowered.",
    "On Annihilator, spend Voidfall stacks at 3 rather than banking them further.",
  },
})

-- Devourer ---------------------------------------------------------------
-- Added 2026-09-02: Devourer (specID 1480) is a new-this-session addition,
-- Demon Hunter's third spec. Unlike Havoc/Vengeance, this entire block is
-- sourced fresh from SimC's `midnight` branch (engine/class_modules/apl/
-- demon_hunter/devourer.simc and profiles/MID2/MID2_Demon_Hunter_Devourer.simc,
-- GPLv3) rather than corrected from older prose, since there is no prior
-- community consensus to check it against yet - flagged as such rather than
-- written with the same confidence as the other two specs. Two notable,
-- APL-confirmed facts: Devourer is the first Intellect/ranged Demon Hunter
-- spec (role=spell, position=back, and a ~3000 Intellect budget in SimC's
-- default gearset vs. low triple-digit Agility on Havoc/Vengeance), and
-- taking the Hunt talent flips BOTH of its hero trees from their default
-- ranged kit into a melee one (actions.annihilator_melee / _ranged and
-- actions.voidscarred_melee / _ranged are separate action lists gated on
-- `talent.the_hunt`, independent of hero tree). Devourer's own hero trees
-- are Annihilator (hero_tree.annihilator - also referenced by Vengeance's
-- APL, so this tree is shared across Vengeance/Devourer rather than being
-- Devourer-exclusive) and Void-Scarred (hero_tree.voidscarred, exclusive to
-- Devourer in the files checked). mplusLoadout below is Void-Scarred only:
-- SimC has not yet published a separate MID2 Annihilator profile for this
-- spec (only one, internally-named "..._Void-Scarred", exists under MID2 as
-- of this pass). Separately, MID2 profiles for every spec (not just this
-- one) carry a new `omnium_talents=` field with no equivalent in this file's
-- schema or in any MID1 profile - an apparent new patch-12.1 "Omnium" trait
-- layer this pass did not investigate further or attempt to represent here.
-- No mplusMetaLoadout: that requires a live Blizzard Battle.net API pull,
-- and this pass had no API credentials to run one.
ns.GuideStore:RegisterSpec("DEMONHUNTER", 1480, {
  specName = "Devourer",
  role = "DAMAGER",
  overview = {
    "Devourer is Demon Hunter's newest spec and its first built around Intellect rather than Agility: a void-corrupted caster that fights at range by default, channeling void energy to devour Soul Fragments instead of shredding with glaives up close.",
    "The core loop still runs on Fury, but Devourer spends it differently: build Fury and pick up Soul Fragments outside of Metamorphosis until your Void Metamorphosis stack maxes out, then transform. Unlike Havoc/Vengeance's fixed-duration Metamorphosis, Devourer's drains Fury continuously while active, so the transformed window is a race to spend Void Ray, Collapsing Star, and the escalating Eradicate/Cull/Reap finisher chain (each one consumes accumulated Soul Fragments for more damage the more you've stacked) before your Fury runs out and the form drops.",
    "Devourer's two hero talent trees are Annihilator (shared with Vengeance) and Void-Scarred (unique to this spec) - but the bigger choice is the Hunt talent, which flips either hero tree's default ranged kit into a melee one instead. Bring Devourer when you want a Demon Hunter that plays like a void-flavored spellcaster with a genuine ranged/melee flex built into a single talent pick, rather than Havoc's mobility or Vengeance's tanking. This is a brand-new spec with no established community consensus yet - treat this guide as a SimC-default-profile starting point, not settled best practice.",
  },
  statPriority = {
    { stat = "primary" },
    { stat = "mastery" },
    { stat = "haste" },
    { stat = "crit" },
    { stat = "versatility" },
  },
  rotation = {
    { title = "Opener", steps = {
        { text = "Soul Immolation precombat to have your damage-over-time already ticking when the pull lands" },
        { text = "Build Fury (Hungering Slash in the melee flex, Void Ray/fragment generators at range) while picking up Soul Fragments to stack Void Metamorphosis" },
        { text = "Metamorphosis once your Void Metamorphosis stack is maxed" },
        { text = "Void Ray, then the highest-tier finisher your banked Soul Fragments can afford (Eradicate > Cull > Reap), to spend hard inside the transformation" },
        { text = "Opener Notes: whichever hero tree you're on (Annihilator or Void-Scarred), taking the Hunt talent swaps this same shape from a ranged opener into a melee one - the fragment-building and Metamorphosis-timing logic stays the same either way" },
    }},
    { title = "Single Target", steps = {
        { text = "Keep Soul Immolation active on the target - it's a maintenance DoT, don't let it fall off" },
        { text = "Pick up Soul Fragments whenever they're up to keep feeding your Void Metamorphosis stack between transformations" },
        { text = "Void Ray on cooldown as your main Fury/cooldown-gated spender" },
        { text = "Spend banked Soul Fragments through Eradicate, or Cull if Eradicate isn't available, or Reap as the baseline option - always the strongest one you can currently afford" },
        { text = "Devour/Consume whenever the Soulburst buff is up - it's a free dump, don't hold it" },
        { text = "Don't let Metamorphosis drop from starving it of Fury - track the drain rate and feed it before it runs out" },
    }},
    { title = "AoE", steps = {
        { text = "Collapsing Star becomes the priority nuke once its stacking buff is built up - let it climb rather than firing it early" },
        { text = "Soul Immolation still goes on your primary target even while cleaving" },
        { text = "Reap/Eradicate/Cull scale with how many Soul Fragments you've picked up, so prioritize fragment pickups more aggressively in AoE" },
        { text = "The Hunt's melee flex trades some range for easier Fragment pickups when packs are stacked on top of each other" },
    }},
  },
  cooldowns = {
    { text = "Metamorphosis - not a flat-duration burst window like Havoc/Vengeance's; it drains Fury while active, so time your entry for when you can keep feeding it and have Fragments/Fury banked to spend" },
    { text = "The Hunt (talent) - shared Demon Hunter gap closer, and the talent that determines whether your whole kit plays ranged or melee" },
    { text = "Vengeful Retreat - reposition, and on Void-Scarred procs a Voidstep buff worth spending immediately after" },
    { text = "Collapsing Star - AoE/cleave payoff once its stacks are built; hold it for that rather than using it early" },
  },
  consumables = {
    { slot = "Flask", text = "Flask of Tempered Swiftness — matches this spec's top secondary; Flask of Alchemical Chaos is the flex pick if your stat weights are close" },
    { slot = "Food", text = "Loa's Gathering or Feast of Knowledge for raid (Stamina + your highest secondary); Hearty Venom-Spiced Cutlets or Puffer Plate for Mythic+/personal (prefer the Hearty version for death persistence)" },
    { slot = "Potion", text = "Tempered Potion, used inside Metamorphosis. Liquid Luster (builds Versatility over 30s) is a strong ramp/M+ alternative, Potion of Unwavering Focus if you want a pure single-target pick instead; always carry Concentrated Silvermoon Health Potions for the emergency heal." },
    { slot = "Weapon", text = "Ironclaw Whetstone or the current-tier weapon enchant on both glaives" },
    { slot = "Enchants", text = "Max-rank Intellect enchants on cloak and rings" },
    { slot = "Gems", text = "Intellect/secondary stat gems in available sockets" },
    { slot = "Augment Rune", text = "Crystallized Augment Rune (1-hour primary stat) for progression pulls and high keys; the reusable Ethereal Augment Rune the rest of the time" },
  },
  gear = {
    { slot = "Head", text = "One of your tier-set slots — SimC's default profile has Season 2's set bonus active, but this spec is new enough that the exact 2pc/4pc effects weren't confirmed by the sources checked this pass. Check your in-game tooltip." },
    { slot = "Chest", text = "A large stat budget and often your other tier piece — push your top secondary first" },
    { slot = "Neck", text = "Usually carries a socket — favor Mastery, then Haste" },
    { slot = "Ring", text = "No set bonus attached — use rings to round out Mastery and Haste" },
    { slot = "Trinket", text = "One on-use trinket timed with Metamorphosis so its burst overlaps your transformation window" },
    { slot = "Trinket", text = "A passive Intellect stat-stick trinket to keep pressure up between cooldowns" },
    { slot = "Weapon", text = "Warglaives (fast one-handers) fit Devourer's dual-wield Fury generation, same as Havoc — take the pair with the highest weapon damage" },
    { slot = "Off-hand", text = "Match your off-hand glaive's secondary stats to your main-hand's Mastery lean" },
  },
  mplusLoadout = {
    string = "CgcBAAAAAAAAAAAAAAAAAAAAAAAWMzMzMzMzMwMAAAAAAALzYMYGAAAAAAAAmxMMmZmZYmZGzsNzYsptFAEwAMjZmZbmZa2mZbmZMjBA",
    source = "SimulationCraft default profile, Void-Scarred hero tree (credit, not endorsement of 'best') - SimC has not yet published a separate MID2 Annihilator profile for this brand-new spec",
    patch = "12.1",
  },
  tips = {
    "This spec has no established community consensus yet — everything here is a SimC-default-profile reading, not settled best practice.",
    "Devourer is Intellect, not Agility — don't carry over Havoc/Vengeance gear or gem/enchant choices by habit.",
    "Track your Void Metamorphosis stack, not just Fury — you transform once it's maxed, and starving it of Soul Fragment pickups delays your next Metamorphosis window.",
    "Metamorphosis drains Fury the whole time it's active — going in without banked Fury/Fragments to spend just shortens the window for no benefit.",
    "The Hunt talent changes your whole playstyle from ranged to melee on both hero trees — pick it deliberately, not as an afterthought.",
    "Spend Soul Fragments through the strongest finisher you can afford (Eradicate over Cull over Reap) rather than defaulting to the cheapest one.",
  },
})
