local ADDON, ns = ...

-- SpecSage guide data: Demon Hunter
-- Content targets The War Within. This is community-maintained, conventional
-- guidance (keep-it-simple stat priorities, long-standing rotation patterns)
-- and is NOT a claim of sim-perfect or bleeding-edge optimal play.
-- To edit: find the RegisterSpec(...) block for the spec you want to change
-- and edit the table in place. To add a new tip/step, insert a new entry in
-- the relevant array. Keep this file data-only — no logic beyond the calls
-- below. See DESIGN.md "Guide data schema" for the full table shape.

if not ns.GuideStore then return end

-- Havoc ----------------------------------------------------------------
ns.GuideStore:RegisterSpec("DEMONHUNTER", 577, {
  specName = "Havoc",
  role = "DAMAGER",
  overview = {
    "Havoc Demon Hunter is a fast, highly mobile melee spec that generates and spends Fury to fuel Chaos Strike/Annihilate and Blade Dance, with Eye Beam and Metamorphosis providing large periodic burst windows.",
    "The core resource is Fury, generated by Demon's Bite/Fel Rush-style abilities and spent on Chaos Strike (or Annihilate while transformed) for damage and Blade Dance/Death Sweep for cleave. Momentum-style talents reward staying mobile with Fel Rush and Vengeful Retreat.",
    "Bring Havoc when you want extremely high mobility, strong burst windows via Eye Beam and Metamorphosis, and good AoE through Glaive Tempest/Fel Barrage-style talents, in exchange for a rotation that rewards careful Fury management.",
  },
  statPriority = {
    { stat = "primary" },
    { stat = "crit" },
    { stat = "haste" },
    { stat = "mastery" },
    { stat = "versatility" },
  },
  rotation = {
    { title = "Opener", steps = {
        { text = "Vengeful Retreat into Fel Rush (Momentum builds) to open with mobility and Fury" },
        { spellID = 198013, text = "Eye Beam early to line up with cooldowns and start building Momentum-style buffs" },
        { text = "Metamorphosis once Fury and cooldowns are ready for the main burst window" },
    }},
    { title = "Single Target", steps = {
        { text = "Demon's Bite / Fel Rush to build Fury" },
        { text = "Blade Dance / Death Sweep on cooldown for cleave-capable damage and defense" },
        { spellID = 162794, text = "Chaos Strike (or Annihilate in Metamorphosis) to spend Fury on your hardest-hitting attack" },
        { spellID = 198013, text = "Eye Beam on cooldown, ideally lined up with other cooldowns" },
        { text = "Don't cap Fury — spend before it overflows" },
    }},
    { title = "AoE", steps = {
        { text = "Blade Dance / Death Sweep to hit all nearby enemies" },
        { spellID = 198013, text = "Eye Beam for strong AoE damage across the pack" },
        { text = "Glaive Tempest / Fel Barrage (talent-dependent) for extra AoE burst" },
        { text = "Chaos Strike/Annihilate still hits cleave targets via Chaos Theory-style talents" },
        { text = "Use Fel Rush/Throw Glaive to tag additional targets while repositioning" },
    }},
  },
  cooldowns = {
    { text = "Metamorphosis — major burst cooldown with extra mobility, use aligned with Eye Beam and raid cooldowns" },
    { spellID = 198013, text = "Eye Beam — strong AoE/cleave burst, use on cooldown and stack with Metamorphosis when possible" },
    { text = "The Hunt (talent) — gap closer with burst damage, use to open a fight or reposition into a pack" },
    { spellID = 196555, text = "Blur — defensive, reduces damage taken and helps with kiting" },
    { text = "Netherwalk — brief immunity/evasion, use to dodge an unavoidable burst hit" },
  },
  consumables = {
    { slot = "Flask", text = "Flask of Alchemical Chaos (Agility)" },
    { slot = "Food", text = "A feast or personal Agility food for the encounter" },
    { slot = "Potion", text = "Tempered Potion, used inside Metamorphosis" },
    { slot = "Weapon", text = "Ironclaw Whetstone or the current-tier weapon enchant" },
    { slot = "Enchants", text = "Max-rank Agility enchants on cloak and rings" },
    { slot = "Gems", text = "Agility/secondary stat gems in available sockets" },
  },
  tips = {
    "Don't let Fury sit capped — that's wasted generation from Demon's Bite/Fel Rush.",
    "Use Vengeful Retreat/Fel Rush proactively for both Fury and repositioning, not only when out of range.",
    "Line up Eye Beam and Metamorphosis together when your build allows for a stacked burst window.",
    "Keep an eye on Blade Dance/Death Sweep cooldown — it's both damage and a defensive parry chance, so don't hold it too long.",
  },
})

-- Vengeance --------------------------------------------------------------
ns.GuideStore:RegisterSpec("DEMONHUNTER", 581, {
  specName = "Vengeance",
  role = "TANK",
  overview = {
    "Vengeance Demon Hunter tanks by building Pain from taking and dealing damage, spending it on Soul Cleave for both damage and self-healing, while Fiery Brand and Demon Spikes provide strong scheduled mitigation.",
    "The core mechanic is Pain, generated passively by taking damage and by abilities like Shear/Fracture, and spent on Soul Cleave which heals you based on damage dealt. Soul Fragments (from Fracture/Fel Devastation-style abilities) further empower Soul Cleave's healing.",
    "Bring Vengeance when you want a tank with strong self-sustain through Soul Cleave healing, good burst AoE threat via Spirit Bomb/Fel Devastation, and a scheduled mitigation cooldown (Demon Spikes) that's easy to weave into any rotation.",
  },
  statPriority = {
    { stat = "stamina" },
    { stat = "primary" },
    { stat = "versatility" },
    { stat = "mastery" },
    { stat = "haste" },
    { stat = "crit" },
  },
  rotation = {
    { title = "Single Target", steps = {
        { text = "Shear / Fracture to generate Pain and Soul Fragments" },
        { spellID = 228477, text = "Soul Cleave to spend Pain for damage and strong self-healing" },
        { text = "Immolation Aura on cooldown for passive AoE damage and Pain generation" },
        { text = "Fel Devastation for burst damage and healing when available" },
        { text = "Sigil of Flame to debuff the target and generate extra Pain" },
    }},
    { title = "AoE", steps = {
        { text = "Immolation Aura on cooldown, it hits everything nearby passively" },
        { text = "Fracture to build Soul Fragments quickly across a pack" },
        { text = "Spirit Bomb (talent) to detonate Soul Fragments for AoE damage, in place of Soul Cleave" },
        { text = "Sigil of Flame to hit and debuff a group of adds on pull" },
        { text = "Fel Devastation for strong AoE burst and self-healing" },
    }},
    { title = "Mitigation", steps = {
        { text = "Demon Spikes to increase armor, use proactively and keep charges from capping" },
        { text = "Fiery Brand to reduce damage taken from the branded target significantly" },
        { text = "Soul Cleave for reliable self-healing on top of raw damage reduction tools" },
        { spellID = 203720, text = "Metamorphosis (tank form) for a major defensive/offensive cooldown" },
        { text = "Don't let Demon Spikes charges cap — use them before a hit lands, not just when low" },
    }},
  },
  cooldowns = {
    { text = "Fiery Brand — major defensive, marks the target for reduced damage taken from it" },
    { spellID = 203720, text = "Metamorphosis — major cooldown, boosts survivability and damage for its duration" },
    { text = "Demon Spikes — frequent mitigation charge, use proactively rather than reactively" },
    { text = "Fel Devastation — damage + self-healing cooldown, use when a healing boost is valuable" },
  },
  consumables = {
    { slot = "Flask", text = "Flask of Alchemical Chaos (Agility, tank stat variant)" },
    { slot = "Food", text = "A feast or personal Stamina/Agility food for the encounter" },
    { slot = "Potion", text = "Tempered Potion or a Stamina/defensive potion for survival cooldowns" },
    { slot = "Weapon", text = "Ironclaw Whetstone or the current-tier weapon enchant" },
    { slot = "Enchants", text = "Max-rank Stamina/Agility enchants on cloak and rings" },
    { slot = "Gems", text = "Stamina/Agility gems in available sockets" },
  },
  tips = {
    "Use Demon Spikes proactively before damage lands — its charges regenerate, so don't hoard them.",
    "Time Fiery Brand for the highest sustained-damage portion of the fight for maximum value.",
    "Soul Cleave is both your main spender and your primary self-heal — don't neglect it while chasing pure damage.",
    "Keep Immolation Aura on cooldown even outside AoE — the passive damage and Pain generation add up.",
  },
})
