-- Data/SiteLoadouts.lua
-- GENERATED by tools/fetch_talents.py - do not hand-edit; re-run the script.
--
-- Recommended talent builds from Icy Veins' per-spec talent pages, as exact
-- Blizzard export strings, each verified to decode to the spec it is filed
-- under. One site's picks at the time the script ran, alongside (not
-- replacing) the SimC-default and live-top-player builds the guides carry.
-- See DESIGN.md's "Guide-site talent builds".
-- Generated: 2026-09-02 16:53 UTC

local ADDON, ns = ...
if not ns.GuideStore then return end

-- WARRIOR 71 (arms-warrior)
ns.GuideStore:RegisterSiteLoadouts(71, {
  source = "Icy Veins Arms Warrior talent guide, updated Aug 25, 2026 - 7:20 PM",
  patch = "12.1",
  builds = {
    { label = "Arms Single-Target - Slayer", string = "CcEAAAAAAAAAAAAAAAAAAAAAAAzMzsMzMmZGAAAghphxYmZzMzMzgxMDAAAAgZWmZAhxyyALgBMDTgZwGYmx2YbglZWGgZGAMDDA" },
    { label = "Arms Multi-Target - Slayer", string = "CcEAAAAAAAAAAAAAAAAAAAAAAAzMzsMzYmZGAAAghphxYmxyMzMzgxMDAAAAgZWmZgJMW2GYBMgZYCZGsBmZsN2GYZmtBYmBAzwA" },
    { label = "Arms Dungeons & Delves - Slayer", string = "CcEAAAAAAAAAAAAAAAAAAAAAAgZmZmFzYmZGAAAghphxYmZzMzMzYmxMDAAAAgxyMDMhxy2ALgBMDTgZwGYmhhBzyMbDwMDAmhBA" },
  },
})

-- WARRIOR 72 (fury-warrior)
ns.GuideStore:RegisterSiteLoadouts(72, {
  source = "Icy Veins Fury Warrior talent guide, updated Aug 25, 2026 - 7:20 PM",
  patch = "12.1",
  builds = {
    { label = "Fury Single-Target - Slayer", string = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDzMmZ2MzMzMDjZmZGzYmlZmxMzMbmZmBAAixy2ALgJYGmAzwGwMDjNAAYmhxYYMYM" },
    { label = "Fury Multi-target - Slayer", string = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjxMzmZmZmZmZMzMzMzYmlZMmZMbmZmBAAixy2ALgJYGmAzwGwMzmBAAYmhxsMwgxA" },
    { label = "Fury Dungeons & Delves - Thane", string = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjZMz2yMzMjZmxMzMzMjZWmZmZmxsZmZGAAIMwGssY0YGQmFMjFAzgBAMzAwwiZAGD" },
  },
})

-- WARRIOR 73 (protection-warrior)
ns.GuideStore:RegisterSiteLoadouts(73, {
  source = "Icy Veins Protection Warrior talent guide, updated Aug 12, 2026 - 9:20 AM",
  patch = "12.1",
  builds = {
    { label = "Single-Target - Colossus", string = "CkEAAAAAAAAAAAAAAAAAAAAAA02AAAzMDzMzMzMzmxsMjxYmGGDLzMzMDGzMAAAAYZAYGDAsYGDbwAzwCNmZBmxMDmNAAzMAgZgxA" },
    { label = "AoE - Mountain Thane", string = "CkEAAAAAAAAAAAAAAAAAAAAAA0yAAAjZYmZmZGziZmlZMGz0YGDLmZmZMDzMAAAAYZAYGDwAbw2iRjZAMLYmNYmZmhxCAMzAAwAGD" },
    { label = "Delves - Mountain Thane", string = "CkEAAAAAAAAAAAAAAAAAAAAAAkBAAGzYmZmZmxsYmZZGjxMNmxwiZmZGzwMDAAAAWGAmxAMwGstY0YGAzCmZDmZmZYsAAzMAAMgxA" },
    { label = "Defensive Raid Build", string = "CkEAAAAAAAAAAAAAAAAAAAAAAkBAAmZGmZmZmxsZmZZGjxMNMGWmZmZGMmZAAAAwyMDwMGgB2glFjGzAY2wMbgxMDmNAYmBAgZgxA" },
    { label = "Defensive Mythic+ Build", string = "CkEAAAAAAAAAAAAAAAAAAAAAAkBAAGzwMzMzMmFzMLzYMmpxMGWMzMzYGmZAAAAwyMDwMGgB2gtFjGzAYWwMbYYmZYsAAzMAAMgxA" },
    { label = "Defensive Raid Build", string = "CkEAAAAAAAAAAAAAAAAAAAAAAkBAAmZGmZmZmxsZmZZGjxMNMGWmZmZGMmZAAAAwyMDwMGAYxMG2gBmhFaMzCYMzgZDAwMDAYGYMA" },
    { label = "Defensive Mythic+ Build", string = "CkEAAAAAAAAAAAAAAAAAAAAAAkBAAGzwMzMzMmFzMLzYMmpxMGWMzMzYGmZAAAAwyMDwMGAYxMGWgBmhFaMzCYmZGGLAAmZAADYMA" },
  },
})

-- PALADIN 65 (holy-paladin)
ns.GuideStore:RegisterSiteLoadouts(65, {
  source = "Icy Veins Holy Paladin talent guide, updated Aug 10, 2026 - 7:20 PM",
  patch = "12.1",
  builds = {
    { label = "Herald of the Sun Raiding - HeraldoftheSun", string = "CEEAAAAAAAAAAAAAAAAAAAAAAAAAALAwMAAw2MzMjZMzYxYmZYZwMLmpJGzYmZYMbZAYADbgNWmxMLz2Mzs1AAAAsAAbGGzYGmBAwMDzghB" },
    { label = "Herald of the Sun Mythic+ - HeraldoftheSun", string = "CEEAAAAAAAAAAAAAAAAAAAAAAAAAgZBAmBAA2GzMzMjZmZBmZYZsZmFjmYWmxMzwY2yAwAwGYjlZmZWmtZmZrBAAAYBMD2AGGMDAgZGmxYYA" },
    { label = "Lightsmith Mythic+ - Lightsmith", string = "CEEAAAAAAAAAAAAAAAAAAAAAAAAAgZBAmBAA2GzMzMjZmZBmZYZsZmFjmYWmxMzwY2yAwAwGYjlZmBAAAmZ22WsNzwGYGsBMMYGAzMAMjxoB" },
  },
})

-- PALADIN 66 (protection-paladin)
ns.GuideStore:RegisterSiteLoadouts(66, {
  source = "Icy Veins Protection Paladin talent guide, updated Aug 18, 2026 - 11:20 PM",
  patch = "12.1",
  builds = {
    { label = "Raid / Single Target - Templar", string = "CIEAAAAAAAAAAAAAAAAAAAAAAsZmtZZmZMzMzMWGjxw2MGAAAAAAAAINGmxMzYMbtBgBMwMYbAAgZm2mZWmBAYjNMAGjZYMAALzAmZGwYB" },
    { label = "AoE / Mythic+ - Templar (Weekly Keys)", string = "CIEAAAAAAAAAAAAAAAAAAAAAAsZYWGzYmZmZW2GjZZWmlZMAAAAAAAAQTzMMjZGGzWbAYgBMD2GAAYmptZmlZAA2ssgBAjZYMAALzAmZGwYB" },
    { label = "AoE / Mythic+ - Templar (High Keys)", string = "CIEAAAAAAAAAAAAAAAAAAAAAAsZsMLjZMzMzMLbjxsMmlZMAAAAAAAAQTzMMjZGGzWbAYgBMD2GAAYmptZmlZAA2ssgBAjZYMAALzAmZGwYB" },
  },
})

-- PALADIN 70 (retribution-paladin)
ns.GuideStore:RegisterSiteLoadouts(70, {
  source = "Icy Veins Retribution Paladin talent guide, updated Aug 25, 2026 - 10:27 PM",
  patch = "12.1",
  builds = {
    { label = "Retribution Single Target - Herald of the Sun", string = "CYEAAAAAAAAAAAAAAAAAAAAAAAAAAAANbbzMzywMDAAAAAAzUGzwMjtxsNMz2MGjxwMWYbAYWmtZmZrBBAAsAYAwYGmBzYmZDYmZYMjBD" },
    { label = "Retribution AoE - Herald of the Sun", string = "CYEAAAAAAAAAAAAAAAAAAAAAAAAAAAwoZbbmZWGzMzAAAAAAYmyYGmZsNmthZ2mxYMGmxCbAYWmtZmZrBBAAsAYAwYGGYGzMbAzMDjZMYA" },
    { label = "Retribution Delves - Templar", string = "CYEAAAAAAAAAAAAAAAAAAAAAAAAAAAwoZbbmZWGjZmBAAAAAYmyYGMjtZmthZ2mxYMzwM2YDAAgZm2mZ2mBAsBYAAzwAzYGbYZGMmxMGMA" },
  },
})

-- HUNTER 253 (beast-mastery-hunter)
ns.GuideStore:RegisterSiteLoadouts(253, {
  source = "Icy Veins Beast Mastery Hunter talent guide, updated Aug 30, 2026 - 11:04 AM",
  patch = "12.1",
  builds = {
    { label = "Beast Mastery Single-Target - Pack Leader", string = "C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwCsAzwwMsBAgZYMzyMDzYmhhZGjZGzMjZMziZmxMmBjpZAAAAAzAAAwYmZAmZjxGMLgtBgB" },
    { label = "Beast Mastery Raid AoE/Cleave - Pack Leader", string = "C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwCsAzwQDbAAYGmZmlZGzMzMjZGMzYmhZGzYmFzMjZMDGTzAAAAAAAAgxMzAMzGZDmFw2AwA" },
    { label = "Beast Mastery Mythic+ - Pack Leader", string = "C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwCsAzwQDbAAYGzMzs8AzYmZmZMzgZGzMMzYmZGbzMjZMDLjpZAAAAAAAAgHYMGwMbEwsA2GAA" },
    { label = "Beast Mastery Delves - Pack Leader", string = "C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwCsAzwQDbAAYGzMzs8AzYmZmZMzgZGzMMzYmZGMGzYmhx0AAAAAAAAAzMGDYmNCWmZBsNAA" },
  },
})

-- HUNTER 254 (marksmanship-hunter)
ns.GuideStore:RegisterSiteLoadouts(254, {
  source = "Icy Veins Marksmanship Hunter talent guide, updated Aug 22, 2026 - 4:31 PM",
  patch = "12.1",
  builds = {
    { label = "Marksmanship Single Target - Sentinel", string = "C4PAAAAAAAAAAAAAAAAAAAAAAwCMwMGzYZAjZwGAAAAAAAAYGzYmFzYmZMDGTzYwYbZmZmZmZmZWYmlBzAAAGzMjBwM22gBYjZ2mxAA" },
    { label = "Marksmanship Raid AoE/Cleave - Sentinel", string = "C4PAAAAAAAAAAAAAAAAAAAAAAwCMwMGzYZAjZwGAAAAAAAAYGzYmFzYmZMDGTzYwstZmZmZmZmZWYmlhZAAAGzMjBwM22gBYjZ2mxAA" },
    { label = "Marksmanship Mythic+ - Sentinel", string = "C4PAAAAAAAAAAAAAAAAAAAAAAwGMwMGzYZAjZwGAAAAAAAAYGzMzYbGzMjZYZMNjBzy22MzMzMzMzswMLDzAAA4BGjBgZsBGgNmZbGD" },
    { label = "Marksmanship Delves - Sentinel", string = "C4PAAAAAAAAAAAAAAAAAAAAAAwGMwMGzYZAjZwGAAAAAAAAYGzMzgxMzYmhx0wgZZbbmZmZmZmZWwsNMDAAwMjxAwM2wyMAbMz2MG" },
  },
})

-- HUNTER 255 (survival-hunter)
ns.GuideStore:RegisterSiteLoadouts(255, {
  source = "Icy Veins Survival Hunter talent guide, updated Aug 18, 2026 - 7:46 PM",
  patch = "12.1",
  builds = {
    { label = "Survival Single Target - Sentinel", string = "C8PAAAAAAAAAAAAAAAAAAAAAAMWgBmxoxyAYmgtZMzMGzyAAAAAAwMmxMLmxYGzgx0MAAAADAmxyyMzsYMzMjZmBAzYZDGDjNDAA" },
    { label = "Survival Mythic+ - Sentinel", string = "C8PAAAAAAAAAAAAAAAAAAAAAAMWgBmxYGLDgZGYbmZmZmxsNPAAAAAAgZMzMjtZMmxMsMmmBAAAYAgxyyMjFMzMegxYAYGbgxYmZzAAA" },
    { label = "Survival Delves - Sentinel", string = "C8PAAAAAAAAAAAAAAAAAAAAAAMWgBmxYGLDgZGYbmZmZmxsNPAAAAAAgZMzMDGjZMzwYaAAAAAAGLLzMWwMzMzYMAMjNsMjxMzmBAAA" },
  },
})

-- ROGUE 259 (assassination-rogue)
ns.GuideStore:RegisterSiteLoadouts(259, {
  source = "Icy Veins Assassination Rogue talent guide, updated Aug 10, 2026 - 7:20 PM",
  patch = "12.1",
  builds = {
    { label = "Assassination Pure Single-Target - Fatebound", string = "CMQAAAAAAAAAAAAAAAAAAAAAAYmlxsNDGAAAAAY2GsNDAAAAAIbzMzMzMjxyMzMbzsMzMzYGzYMmZMMAGYBmxoxsBYbAbGAMzMGD" },
    { label = "Assassination Raid Cleave - Fatebound", string = "CMQAAAAAAAAAAAAAAAAAAAAAAYmlxsZwAAAAAAzygtZAAAAAAttNzMzMzMGLzMzsNzyMz8AjxMjxYmZmxAYgFYGjGzGgtBsZAwMzgB" },
    { label = "Assassination Mythic+/Delves - Fatebound", string = "CMQAAAAAAAAAAAAAAAAAAAAAAYmlZmFDAAAAAAzygtZAAAAAAttNzMzMzMGLzMzsNzyMz8AmxMjxwMjxAYgFYGjGzCgtBsZAwMzMMA" },
  },
})

-- ROGUE 260 (outlaw-rogue)
ns.GuideStore:RegisterSiteLoadouts(260, {
  source = "Icy Veins Outlaw Rogue talent guide, updated Aug 10, 2026 - 7:20 PM",
  patch = "12.1",
  builds = {
    { label = "Outlaw Single Target - Trickster", string = "CQQAAAAAAAAAAAAAAAAAAAAAAAgx2MMzMmZmtZmZmZMmF4BmZbaZw2MAAAAAALLzMzwMzMziZmZbAAAAYmBAjZxwADMLsQLsxAMzgBG" },
    { label = "Outlaw AoE - Trickster", string = "CQQAAAAAAAAAAAAAAAAAAAAAAAgx2MMzMjZmtZmZMzMzsAmZbaZw2MAAAAAALLzMzwMzMziZmZbAAAAYmBAjZxwADMLsQLsxAMzgBG" },
  },
})

-- ROGUE 261 (subtlety-rogue)
ns.GuideStore:RegisterSiteLoadouts(261, {
  source = "Icy Veins Subtlety Rogue talent guide, updated Aug 10, 2026 - 7:20 PM",
  patch = "12.1",
  builds = {
    { label = "Single-Target - Deathstalker", string = "CUQAAAAAAAAAAAAAAAAAAAAAAAgx2MAAAAAwsMGLTMbbjxMDDzMzMzw8AbzYGbbzMzMzMjBjZ2GAAAAGMmFzyADYBsMMBmFMDzMAzYA" },
    { label = "Mythic+/AoE - Trickster", string = "CUQA5HmDzx68KWyrW/8Y781L7Dgx2MAAAAAwsMGLTMbLjxMMjZmZmZGGbzYGbbzMzMzMjBjZ2GAAAAGMGwY2MMwAziWoFbYGwMDmxA" },
    { label = "High Mythic+ - Deathstalker", string = "CUQAAAAAAAAAAAAAAAAAAAAAAAgx2MAAAAAwsMGLTMbLjxMMjZmZmZGGbzYGbbzMzMzMjBjZ2GAAAAGMmFzyADYBsMMhMLYGmZAmxA" },
  },
})

-- PRIEST 256 (discipline-priest)
ns.GuideStore:RegisterSiteLoadouts(256, {
  source = "Icy Veins Discipline Priest talent guide, updated Aug 18, 2026 - 7:20 PM",
  patch = "12.1",
  builds = {
    { label = "Voidweaver Raid", string = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMmxyYmBzgZbmtZmZmZmBAAAAAAAAAgZYZGMzMDzYmBMNTzMYmBAAY2mtFwYzAAwYMzYwMYmBjgB" },
    { label = "Oracle Mythic+", string = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMDWmZMmBmZbmtZmZmxMDAAAAAAAAAgZYZGMzMzwYmBbmmJGgZWwQYMLDwYwCAAMmZmxgZAmZGBzA" },
  },
})

-- PRIEST 257 (holy-priest)
ns.GuideStore:RegisterSiteLoadouts(257, {
  source = "Icy Veins Holy Priest talent guide, updated Aug 25, 2026 - 12:20 PM",
  patch = "12.1",
  builds = {
    { label = "Holy Priest Raid - Oracle Easy Mode", string = "CEQAAAAAAAAAAAAAAAAAAAAAAADAAAAAAYBmZWGzMmZMMDzsMzYGAAAAzYWmBzMzwMMjBMTBwMLYIMmtBYMwiZmZBgZMzYMMzAMzMgB" },
    { label = "Holy Priest Raid - Archon", string = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAgZmlxYMzMDzMzYZGmBAAAwwsMDzMzMMDzYAzUAgZWMDziBAGD2MzMLAaGzMGDzMbLDwAGA" },
    { label = "Holy Priest Delves & M+ - Oracle", string = "CEQAAAAAAAAAAAAAAAAAAAAAAADAAAAAAgZmxsMMjZGDzwYZmZmBAAAwYmlZwMzM2MmZMgZKAmZBDhxsNAjBWMzMLAMjZGjBzAMzMgB" },
  },
})

-- PRIEST 258 (shadow-priest)
ns.GuideStore:RegisterSiteLoadouts(258, {
  source = "Icy Veins Shadow Priest talent guide, updated Sep 1, 2026 - 8:15 PM",
  patch = "12.1",
  builds = {
    { label = "Shadow Raid - Archon", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMz2MGzw2MzYmZGbIzYxMNAzAMzmZY2MAkxYBAzMgxMzMmNmZbZAmBDA" },
    { label = "Shadow AoE - Voidweaver", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMzyMzYG2mZGzMzYDZGLmpBYmZGAIAz2stAmNGAYwYmZGzGzgZGMDGA" },
    { label = "Shadow Delves - Voidweaver", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMzyMzYmx2MYmZmZDZGLb0AMzMDAEgZb2WAzGDAMwMzMzMbMDmZwMYA" },
    { label = "Archon Raid - No 4pc Season 2", string = "CIQAR03Gt7xPmcDNOjs2Zlb3yOMjZGAAAAAAAAAAAgxMMjx2MDzsNzwMjtZMmZmBmMwMNzAzAMzmZ0sZAIjxCAmBYMzMjZbMz2yAMDGA" },
    { label = "Archon Raid - Sszorak", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDzAAAAAAAAAAAAwMLmxMbzMGz2MGzw2MzYmZGbIzYxMNAzAMzmZY2MAkxYBAzMgxMzMmNmZbZAmBDA" },
    { label = "Archon Raid - Entombed Sentinels", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDzAAAAAAAAAAAAMmZxMGbzMmZ2mBzw2MzYmZGbIzYxMNAzAMzmZY2MAkxYBAzMgxMzMmNmZbZAmBDA" },
    { label = "Archon Raid - Lost Explorers", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDPAAAAAAAAAAAAghZxMmZbmxMz2MGzw2MzYmZGbIzYxMNAzAMzmZ0sZAIjxCAmZMYMzMjZjZ2WGgZwA" },
    { label = "Archon Raid - Ulatek (Heroic)", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZZmxMz2MGzw2MzYmZGbIzYxMNAzAMziZY2MAkxYBAzMIjZmZMbMz2yAMTMA" },
    { label = "Archon Raid - Ulatek (Mythic)", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDPAAAAAAAAAAAAghZxMmZZmxMz2MGzw2MzYmZGbIzYxMNAzAMziZY2MAkxYBAzMGZMzMjZjZ2WGgZiB" },
    { label = "Archon AoE - No 4pc Season 2", string = "CIQAR03Gt7xPmcDNOjs2Zlb3yOMjZGAAAAAAAAAAAghZxMGbzMmZWmZYmx2MGzMzYDZGLmpBYGgZ2MjmNDAZMWAwMAjZmZMbjZ2WGgZwA" },
    { label = "Voidweaver Raid - No 4pc Season 2", string = "CIQAR03Gt7xPmcDNOjs2Zlb3yOMjZGAAAAAAAAAAAgxMMjx2MDzsNzwMsNzMmZmxGyMWMTDwMzMAQAmtZbJY2YAmBYMzMjZbMDmZwMYA" },
    { label = "Voidweaver Raid - Sszorak", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAAegZxMmZbmBz2MzYG2mZGzMzYDZGLmpBYmZGAIAz2stAmNGAYwYmZGz2YGMzgZwA" },
    { label = "Voidweaver Raid - Entombed Sentinels", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAgxDMLmxYbmhZ2mZYG2mZGzMzYDZGLmpBYmZGAIAz2stAmNGAYwYmZGz2YGMzgZwA" },
    { label = "Voidweaver Raid - Lost Explorers", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMjZMAAAAAAAAAAAAYMLzMGbzMmZ2mZGzw2MzYmZGbIzYxMNAzMzAABY2mtFwsxAADGzMzY2GzgZGMDGA" },
    { label = "Voidweaver AoE - No 4pc Season 2", string = "CIQAR03Gt7xPmcDNOjs2Zlb3yOMjZGAAAAAAAAAAAghZxMGbzMmZWmZYmx2MGzMzYDZGLmpBYmZGAIAz2stEMbMAwgxMzMmtxMYmBzgB" },
  },
})

-- DEATHKNIGHT 250 (blood-death-knight)
ns.GuideStore:RegisterSiteLoadouts(250, {
  source = "Icy Veins Blood Death Knight talent guide, updated Aug 10, 2026 - 7:20 PM",
  patch = "12.1",
  builds = {
    { label = "Blood Single Target - San'layn", string = "CoPAAAAAAAAAAAAAAAAAAAAAAwYWmZGmxMzMMLzMz0MLGzMzMGAAAAwMzMzMzMDzYMDAMzMzAAAYgBmxiGLLAWGwGgZMDAAYmBwA" },
    { label = "Blood Mythic+ - San'layn", string = "CoPAAAAAAAAAAAAAAAAAAAAAAwMzyMzwMmZmhZZmZmmZxYmxMGAAAAwMmZmZmZYGjBAjZmZGAAADMwMW0YZBwyA2AMjZAAAzMwwA" },
    { label = "Blood Delves - Deathbringer", string = "CoPAAAAAAAAAAAAAAAAAAAAAAwMzyMzwMmZmhZZmZmmZxYmZmxAAAAAmxMzMzMDzYMAYMzMzAAAMmtBGwCYbYCMsAYGzAAwMDAMA" },
    { label = "Blood - Defensive San'layn", string = "CoPAAAAAAAAAAAAAAAAAAAAAAwMzyMzwMmZmhZZmZmmZxYmxMGAAAAwMmZmZmZ8AzYAAzMzMzAAAYgBmxiGLLAWGwGgZYAAAzMwwA" },
    { label = "Blood - Defensive Deathbringer", string = "CoPAAAAAAAAAAAAAAAAAAAAAAwMzyMzwMmZmhZZmZmmZxYmZmxAAAAAmxMzMzMjHYGDAYmZmZGAAgxsNwAWAbDTghFAzwAAwMDAMA" },
  },
})

-- DEATHKNIGHT 251 (frost-death-knight)
ns.GuideStore:RegisterSiteLoadouts(251, {
  source = "Icy Veins Frost Death Knight talent guide, updated Aug 10, 2026 - 7:20 PM",
  patch = "12.1",
  builds = {
    { label = "Frost Single Target", string = "CsPAAAAAAAAAAAAAAAAAAAAAAMDwMjZmZGDz2MzMzMLmZmMjxYYmxgZMzMzMzMDAAAAAAAAAgNzihBGY2YohNMzYmZgBgBgZGgB" },
    { label = "Frost Mythic+/Delves", string = "CsPAAAAAAAAAAAAAAAAAAAAAAMDYmZMzMzYY2mZmZmZxMjMjxYYMGMzMzMzMzMDAAAAAAAAAjZbgBsAWGmAjFMzYmZgBghZGAgB" },
  },
})

-- DEATHKNIGHT 252 (unholy-death-knight)
ns.GuideStore:RegisterSiteLoadouts(252, {
  source = "Icy Veins Unholy Death Knight talent guide, updated Aug 24, 2026 - 7:20 PM",
  patch = "12.1",
  builds = {
    { label = "Unholy Single-Target", string = "CwPAAAAAAAAAAAAAAAAAAAAAAAwMjZMzYY2mZmZa2MzMjZAAAAAAAAg5BGGDAWmhZ2MzYmZMwAzYRjlFAbD2AwMAmZmZGzgZGMjxA" },
    { label = "Unholy Mythic+/Delves", string = "CwPAAAAAAAAAAAAAAAAAAAAAAAYmhZMzMDz2MzMTzmZGjZAAAAAAAAg5BGDDAWmhZ2MzYMjBGYGLassAYbwGGwMAmZmZGzgZGMjxA" },
  },
})

-- SHAMAN 262 (elemental-shaman)
ns.GuideStore:RegisterSiteLoadouts(262, {
  source = "Icy Veins Elemental Shaman talent guide, updated Aug 10, 2026 - 11:10 PM",
  patch = "12.1",
  builds = {
    { label = "Elemental Single Target - Farseer", string = "CYQAAAAAAAAAAAAAAAAAAAAAAAAAAAzMbLzMmZmZZZZMMjBAAAAsYmNYADY2YCMLAwsNzMjZ2WmJMzsxyMzMjZwyMWMzwMLDAYAgZGDDD" },
    { label = "Elemental Mythic+ - Farseer", string = "CYQAAAAAAAAAAAAAAAAAAAAAAAAAAAzMbLzMGjZZZZMmhBAAAAsYmNYADY2YCMLAwsNzMjx2iJMzsNWmZmZMjFLzMmZGzMLAADAMzYYYA" },
    { label = "Elemental Delves - Farseer", string = "CYQAAAAAAAAAAAAAAAAAAAAAAAAAAAzMbLzMGjZZZZMmhBAAAAsYmNYADY2YCMLAwsNzMjZ2WmJMzYsYmZGzYxyMjZmxMzCAwAAzMGGGA" },
  },
})

-- SHAMAN 263 (enhancement-shaman)
ns.GuideStore:RegisterSiteLoadouts(263, {
  source = "Icy Veins Enhancement Shaman talent guide, updated Aug 23, 2026 - 7:20 PM",
  patch = "12.1",
  builds = {
    { label = "Raid / Single Target - Stormbringer", string = "CcQAAAAAAAAAAAAAAAAAAAAAAMzMzgZmZmZmhZmZAAAAAAAAA2AsZGDbwCMDDNYBgZZGzMjllZgZmNWmZmZYYMDAwMMmZMzEYmBDGDA" },
    { label = "AoE / Mythic+ - Stormbringer", string = "CcQAAAAAAAAAAAAAAAAAAAAAAMzMzgZmZmZmhZmZAAAAAAAAAsBYzMG2gFYGGawCAzyMmxYZxYjZmtxyMzMzYswMAAzwYmhRgZGMYMA" },
    { label = "Delves - Totemic", string = "CcQAAAAAAAAAAAAAAAAAAAAAAMzMjZmZmZmZmZmZGzAAAAAAAAAALwGMjFN2GAzA2AYWmxMGLLzAzMGLmZmZMWYGAADMGzMxMDAMGA" },
  },
})

-- SHAMAN 264 (restoration-shaman)
ns.GuideStore:RegisterSiteLoadouts(264, {
  source = "Icy Veins Restoration Shaman talent guide, updated Aug 10, 2026 - 7:20 PM",
  patch = "12.1",
  builds = {
    { label = "Restoration Dungeons - Totemic", string = "CgQAAAAAAAAAAAAAAAAAAAAAAAAAAgBAAAAzMzsstMmZmZmZGjZMsBbwMW0YbAMDshxMMLzMGNLLzMbmxsxixMjhlZZAAAAzMYmBgxgZA" },
    { label = "Restoration Raid - Totemic", string = "CgQAAAAAAAAAAAAAAAAAAAAAAAAAAgBAAAAzMzsssNjZGjZGzMYsBbwMW0YbAMDsZGmBbjZmpZbZmhZMbsMzMzYwsMAAAwMzgZGAYwM" },
    { label = "Restoration Delves - Farseer", string = "CgQAAAAAAAAAAAAAAAAAAAAAAAAAAgBAAAAzMzsssNzMzMzMzYmhxiZWgBMgZhJwYhBY2mZMa2WmZ2MzMLsYmZGDmlBAAAYGAMzgZwM" },
  },
})

-- MAGE 62 (arcane-mage)
ns.GuideStore:RegisterSiteLoadouts(62, {
  source = "Icy Veins Arcane Mage talent guide, updated Aug 12, 2026 - 7:13 AM",
  patch = "12.1",
  builds = {
    { label = "Arcane Raid - Sunfury", string = "C4DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMDamZGAAAGAwMz0sssMDAgNAAAzMDbWmxMLzYMzMzMsxMmZmBAYAAAGgZGwMAYYmZA" },
    { label = "Arcane Mythic+ - Sunfury", string = "C4DAAAAAAAAAAAAAAAAAAAAAAMzwYZmZmFMzQzMzAAAwAAmZmmlllZAAsBAwGMzMsZZGzsMjxMzMzwGzYGzAAMAAADwMDMzAghZmB" },
    { label = "Arcane Delves - Sunfury", string = "C4DAAAAAAAAAAAAAAAAAAAAAAMzwYZGzsYzMDNzYGAAADAYmZaWWWmBAwGAAbwMzwmlZMzyMGzMzMDbMjZMDAwAAAMAzMwMDAGmZG" },
  },
})

-- MAGE 63 (fire-mage)
ns.GuideStore:RegisterSiteLoadouts(63, {
  source = "Icy Veins Fire Mage talent guide, updated Aug 10, 2026 - 7:20 PM",
  patch = "12.1",
  builds = {
    { label = "Fire Raid - Sunfury", string = "C8DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMDZmZGAAAGAwMz0sstMDAwmZmx2MzMzYDAAAAAbmZMzAAgZMmZmZMzsMAMzAMGwMMGA" },
    { label = "Fire Mythic+ - Sunfury", string = "C8DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzsgZGZmZGAAAAAmZmmltlZAA2MzM2mZmZGbAAAAAYzMjZGAAMjxMzMjZmlBgZGMjxAmhxA" },
  },
})

-- MAGE 64 (frost-mage)
ns.GuideStore:RegisterSiteLoadouts(64, {
  source = "Icy Veins Frost Mage talent guide, updated Aug 10, 2026 - 7:20 PM",
  patch = "12.1",
  builds = {
    { label = "Frost Single Target", string = "CAEAAAAAAAAAAAAAAAAAAAAAAYGGLzMzsMmZmYmZGjZMziZmZmZMDAAAMzMzyyMTbAAAAAAwGAbbjZmZwsNPgxMsAAAwMbAzADYGMMA" },
    { label = "Frost Light Cleave/Raid", string = "CAEAAAAAAAAAAAAAAAAAAAAAAYGGLzMzsMmZmYmZGzMzMziZmZMjZAAAgZmZWWmZaDAAAAAA2AYbbMzMDmthxMsAAAwMbAzADYGMMA" },
    { label = "Frost AoE", string = "CAEAAAAAAAAAAAAAAAAAAAAAAYGGLzMzsMmZmYmZGzMzMWMzMzMzYmlZamZZWAAAgFAAAAAAYBgttxMzMY2mxMzYbBAAAMzgZgBMDwA" },
  },
})

-- WARLOCK 265 (affliction-warlock)
ns.GuideStore:RegisterSiteLoadouts(265, {
  source = "Icy Veins Affliction Warlock talent guide, updated Aug 31, 2026 - 7:41 PM",
  patch = "12.1",
  builds = {
    { label = "Affliction Single-Target - Soul Harvester", string = "CkQAAAAAAAAAAAAAAAAAAAAAAwMzMzoZhhZmZmlBAAYmZZ2mZmlxAAjllBGwEMDbBG2GAAAmBAAwMDzMjBzwMzMzMGMzMzAAmBG" },
    { label = "Affliction AoE - Soul Harvester", string = "CkQAAAAAAAAAAAAAAAAAAAAAAwMjZGNLmxyMzYWGAAwMzsMLzMzyYAgx2yADYCmhtADbDAAAzAAAYmZMzwsxwYmZmZYYmZmBAMDMA" },
    { label = "Affliction Delves - Soul Harvester", string = "CkQAAAAAAAAAAAAAAAAAAAAAAwMjZGNLmxyMzYWGAAwMzsMLzMzyYAgxyyADYAzwWghtBAAgZAAAMzMmZY2GjZwMzMMMzMzAAmBG" },
  },
})

-- WARLOCK 266 (demonology-warlock)
ns.GuideStore:RegisterSiteLoadouts(266, {
  source = "Icy Veins Demonology Warlock talent guide, updated Aug 11, 2026 - 7:59 PM",
  patch = "12.1",
  builds = {
    { label = "Demonology Single-Target - Soul Harvester", string = "CoQAAAAAAAAAAAAAAAAAAAAAAwMzMzoZjhZmxsMAAAAAAAjtlBGwAmhtQGbmhZ2mlZmZMDAYMzMzAMzMmxMDAAwMzMzMjZYZAYA" },
    { label = "Demonology AoE - Diabolist", string = "CoQAAAAAAAAAAAAAAAAAAAAAAwMjZGNLmxmZGzyAAAAAAAAGzYYBGYb0CNsYMzYZ2mZmxMAwMjZGzMDwYmxMbAAgxMzMzww2MGwA" },
    { label = "Demonology Delves - Soul Harvester", string = "CoQAAAAAAAAAAAAAAAAAAAAAAwMjZGNLmxiZGzyAAAAAAAMWWGYADYG2CM2MmZsMmxMzMAwMzMGDwMzYmxMbAAgxMzMzYw2MDwA" },
  },
})

-- WARLOCK 267 (destruction-warlock)
ns.GuideStore:RegisterSiteLoadouts(267, {
  source = "Icy Veins Destruction Warlock talent guide, updated Aug 21, 2026 - 7:59 PM",
  patch = "12.1",
  builds = {
    { label = "Destruction Single-Target - Hellcaller", string = "CsQAAAAAAAAAAAAAAAAAAAAAAwMmZGNLMzmZmZWmFzMzsYMWMDAAmZGzMziNYgZxoxMAmtYjBAAGDM2AAmZwYGzYDAAwMzMAAMGG" },
    { label = "Destruction AoE - Diabolist", string = "CsQAAAAAAAAAAAAAAAAAAAAAAwMjZGNLmxmZGzysNzYmFzYZZMAAYGjZmZBMmxwCMw2wCNWYAAgxMMsBgZGgxMjZ2AAAMzMzAAYMM" },
    { label = "Destruction Delves - Hellcaller", string = "CsQAAAAAAAAAAAAAAAAAAAAAAwMjZGNLmxmZGzysZGzsYYZZmBAAzMjZmZxCMwsY0YGAzG2YAAgxMAAAzMYMzMmNAAAzMzMAAMDD" },
  },
})

-- MONK 268 (brewmaster-monk)
ns.GuideStore:RegisterSiteLoadouts(268, {
  source = "Icy Veins Brewmaster Monk talent guide, updated Aug 10, 2026 - 7:20 PM",
  patch = "12.1",
  builds = {
    { label = "Brewmaster Raiding (Defensive) - Master of Harmony", string = "CwQAAAAAAAAAAAAAAAAAAAAAAAAAAgZbzYGPwYWM2mxMDAAAAAAALLYEmBmhxmZMmZmZMzywMmZZYZzy2sNMLAAwysMtMbzsMAAAAzwGYmBMNGAAwA" },
    { label = "Brewmaster Mythic+ (Standard) - Shado Pan", string = "CwQAAAAAAAAAAAAAAAAAAAAAAAAAAwMLbGDzwyM2MmZMAAAAAAALLgYmBmhBzgZmZGzsNMjZWGW2stNbzYWAAgNAAAwsNLNzMzGDbAMzw0YADAYA" },
    { label = "Brewmaster Delves/Open World - Master of Harmony", string = "CwQAAAAAAAAAAAAAAAAAAAAAAAAAAgZZzYGzwyM2MmZMAAAAAAALLgYmBmhBzgZmZGzsNMjZWGW2ssNbzYWAAglZZaZ2mZZAAAAMsBmZATjBMAgB" },
  },
})

-- MONK 270 (mistweaver-monk)
ns.GuideStore:RegisterSiteLoadouts(270, {
  source = "Icy Veins Mistweaver Monk talent guide, updated Aug 18, 2026 - 6:30 PM",
  patch = "12.1",
  builds = {
    { label = "Mistweaver Raid - Conduit of the Celestials", string = "C4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAghx2YZYzixMzyyM2wYGmZZbbmxCzoZMDYwAsMzMzwsBDWmJAAAAAAYxyMLzyMDAAMgBYGwYYsMZMDA" },
    { label = "Mistweaver Mythic+ - Conduit of the Celestials", string = "C4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAghxyMLjZx2MmZsZstsNjZ2Mz22yMjFmRzYGwgBDmZmZY2GmhZ5BmAAAAAAgFLzsMLzMAAwAAMDYMwiMmBA" },
    { label = "Mistweaver Delves - Conduit of the Celestials", string = "C4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAghxyMLjZx2MzMz2G2sNjZ2Mz22yMjFmZaGzYBDGglZmZGmNYwyMBAAAAAALWmZZWmZAAAYAYGwAsMZMDA" },
  },
})

-- MONK 269 (windwalker-monk)
ns.GuideStore:RegisterSiteLoadouts(269, {
  source = "Icy Veins Windwalker Monk talent guide, updated Aug 11, 2026 - 10:20 AM",
  patch = "12.1",
  builds = {
    { label = "Windwalker Raids - Shado-Pan", string = "C0QAAAAAAAAAAAAAAAAAAAAAAMzYM2GmhlZGbzAAAAAAAAAAAAsMMCzwwAmZGmZmZY2GmhZZmAAWMz2MjZmZmBAwGAMLzSzMzsAgBmZAYsMAGwFA" },
    { label = "Windwalker Mythic+ - Conduit of the Celestials", string = "C0QAAAAAAAAAAAAAAAAAAAAAAMzYMgxYZmZ2mBAAAAAAAAAAAYZYEmhhBMjhZmZGmNMDzyMBAswsxMmZmZAAsYmlZZMBAAmZGAzAMWGDYmZ2M" },
  },
})

-- DRUID 102 (balance-druid)
ns.GuideStore:RegisterSiteLoadouts(102, {
  source = "Icy Veins Balance Druid talent guide, updated Aug 10, 2026 - 7:20 PM",
  patch = "12.1",
  builds = {
    { label = "Balance Druid Single-Target - Elune's", string = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNjxMD8AmFzMzMLMMMmZZGGzYhlZWmZMmZDDAGbLzMYMbDgJAAAALMzMzgNjZMmBAwMDWGA" },
    { label = "Balance Druid AoE - Elune's", string = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNjxMD8AmFzMzMLMMMmZZmFzMjFWmZZMmZsgBAjttZGMmtBwEAAAgFmZmZwmxMGzAAYmBGA" },
    { label = "Balance Druid Delves - Keeper", string = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNjxMD8AmlZmZmZDgZZmtZWmxMzGLzYMGzshBADw22YBTzMbDAAAA2MzMzMYzYGjBgZGAYA" },
    { label = "Keeper of the Grove Cleave Build", string = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNjxMDMmlZmZmBMDjZWmZZGzYhlZMmZmxCGAMALbjFMNzsMAAAAYjZmZGsZgxMAmZAgBA" },
  },
})

-- DRUID 103 (feral-druid)
ns.GuideStore:RegisterSiteLoadouts(103, {
  source = "Icy Veins Feral Druid talent guide, updated Aug 10, 2026 - 7:20 PM",
  patch = "12.1",
  builds = {
    { label = "Raid / Single Target - Wildstalker", string = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAwYMjxYmZMmtFWGbzMzYmZAAAAYLY2MMmZUzYWmZmZGjZMAAAAAAMwAAAAAAMbzs0sNzyGYmHAYxMYAAMzAgB" },
    { label = "Raid / Cleave - Wildstalker", string = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZMzGzMzMGz2yYZsNjZmHYmBAAAgtgZzwYmRNjZZmZmZMmxAAAAAAwADAAAAAwsNzSzyMLbgZeAgFzgBAwMDAGA" },
    { label = "AoE / Mythic+ - Druid of the Claw", string = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmZ2YmZmxY2MPw2YbGzMmZAAAAYLY2M8AmZUzYWMzMzsMmxAAAAAAwADAAAgmZZWmZmBAsAzMDwCDGAAAzshB" },
    { label = "Delves - Druid of the Claw", string = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjZYmxMzMzsZsNz2MmZegZGAAAA2CmNDPgZG1MmlxMzMLjZYAAAAAAMwAAAAoZWmlZmZAALwMzAswgBAAwMbYA" },
  },
})

-- DRUID 104 (guardian-druid)
ns.GuideStore:RegisterSiteLoadouts(104, {
  source = "Icy Veins Guardian Druid talent guide, updated Aug 10, 2026 - 7:20 PM",
  patch = "12.1",
  builds = {
    { label = "Guardian Single Target - Druid of the Claw", string = "CgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmxsMPwYMzmZZGMLLDMbwoJamZWmZmZGjZMDAAAAAYGLzAAAAgmZZWmZmBAwCmZAWMDGwmFDAmZDG" },
    { label = "Guardian AoE - Elunes Chosen", string = "CgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmZml5BmZMziZxwMLLDMbGGNRmZWmZmZmlxMGAAAAAgZsYAbbzMYMLDgJAAAgNMzAsYGMgNLAMzAYA" },
    { label = "Guardian Delves - Elunes Chosen", string = "CgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmxsMPwMjZWMLGmZZZgZzwoJyMzyMzMzsMmxAAAAAAMjlZALbzMYMLDgJAAAgNMzAsYGMgNLAMzAYA" },
  },
})

-- DRUID 105 (restoration-druid)
ns.GuideStore:RegisterSiteLoadouts(105, {
  source = "Icy Veins Restoration Druid talent guide, updated Aug 10, 2026 - 7:20 PM",
  patch = "12.1",
  builds = {
    { label = "Wildstalker Raid", string = "CkGAAAAAAAAAAAAAAAAAAAAAAYMmZZmZMzMmthBzsZsNmBAAAAAAAAAAbDa2YMNzY4BMLzMzMDDzAAAAAAAAAAIAAgZbmlmtZ2sxYmZwMwoZAAmZAYA" },
    { label = "Wildstalker Mythic+", string = "CkGAAAAAAAAAAAAAAAAAAAAAAMMmZZMjZmxsNMMmlZsZbGAAAAAAAAAAsMoZzw0MjZwsYmZmZZGegZAAAAAAAwAAQAAAz2MbNbzsYjxMDMzCoZAAmZAYA" },
    { label = "Wildstalker Delves", string = "CkGAAAAAAAAAAAAAAAAAAAAAAMMmxYGzMjZbmZYYhZx2MAAAAAAAAAAYbQzmhpZMzYMLmZmZWmhxAAAAAAAYMAAEAAwsMzWzyML2gZeAMjFQzAAMzAwA" },
  },
})

-- DEMONHUNTER 577 (havoc-demon-hunter)
ns.GuideStore:RegisterSiteLoadouts(577, {
  source = "Icy Veins Havoc Demon Hunter talent guide, updated Aug 30, 2026 - 2:00 AM",
  patch = "12.1",
  builds = {
    { label = "Raid / Cleave – Fel-Scarred", string = "CEkAAAAAAAAAAAAAAAAAAAAAAYgZmZMjZmZmxMZMzAAAAAAAmNjZbmxYmtZmxyMjZsMzwMLzsMDGGLbMhxMjhFAAAAAAAwMDwAAAAwA" },
    { label = "AoE / Mythic+ – Fel-Scarred", string = "CEkAAAAAAAAAAAAAAAAAAAAAAYmZGzMz2MmZmxYmMmZAAAAAAAzixsNDzMwMWmZmZYmBzyAbzmZMMbMNmZGzYDAAAYAAAAMzgBAAAgB" },
    { label = "Delves – Fel-Scarred", string = "CEkAAAAAAAAAAAAAAAAAAAAAAYmZGzMjZMzMjxMhZGAAAAAAwsYmhZMzAzYZmZmxyMDmlB2mNzYY2YaMzMzM2AAAAAAAAYmBDAAAAD" },
    { label = "High Mythic+ Keys - Aldrachi Reaver", string = "CEkAAAAAAAAAAAAAAAAAAAAAAYgZmZ2mxMzMGzkxMDAAAAAAYWMmtZYmZ2mZGLzMmxyMDzsMz2MYYssxEGzMmxCAAAAAAAYmBYAAAAYA" },
  },
})

-- DEMONHUNTER 581 (vengeance-demon-hunter)
ns.GuideStore:RegisterSiteLoadouts(581, {
  source = "Icy Veins Vengeance Demon Hunter talent guide, updated Aug 10, 2026 - 7:20 PM",
  patch = "12.1",
  builds = {
    { label = "Vengeance Single Target", string = "CUkAAAAAAAAAAAAAAAAAAAAAAAAMjZmZMzMjMzMYWMzMDMjZGzYGzMDzMzM2GzsNGAAAAAAAAwMzYDAAAADGzMzMbtNzMDAAAAAwA" },
    { label = "Vengeance AoE", string = "CUkAAAAAAAAAAAAAAAAAAAAAAAAMjZmZMMzkZmBWMjZwMjZGzMzMzYwMzM2YmtxwAAAAAAAAwMzMbAAAAYgZmZmZrtZmZAgBAAAwA" },
  },
})

-- DEMONHUNTER 1480 (devourer-demon-hunter)
ns.GuideStore:RegisterSiteLoadouts(1480, {
  source = "Icy Veins Devourer Demon Hunter talent guide, updated Aug 17, 2026 - 6:47 PM",
  patch = "12.1",
  builds = {
    { label = "Devourer Single Target - Void-Scarred", string = "CgcBAAAAAAAAAAAAAAAAAAAAAAAWMzMzMzMjBmBAAAAAAY5BGz2gZAAAAAAAAYGzw8AzMzMzMzMjZ2mZM202CACYAMmZmtZmpZbmlZmxYGA" },
    { label = "Devourer AoE - Void-Scarred", string = "CgcBAAAAAAAAAAAAAAAAAAAAAAAWMzMzMzYMGmBAAAAAAY5BGz2gZAAAAAAAAYGzw8AzMzMzMzMjZ2mZM202CACYAMmZmtZmpZZmlZmhZGA" },
    { label = "Devourer Delves - Void-Scarred", string = "CgcBAAAAAAAAAAAAAAAAAAAAAAA2MzMzMzMjxwMAAAAAAAmxAmBAAAAAAAgZMDzDMzMzMzMzMmZbmxYTbbAIgBwMzMz2Mz0sNz2MzwMDA" },
  },
})

-- EVOKER 1467 (devastation-evoker)
ns.GuideStore:RegisterSiteLoadouts(1467, {
  source = "Icy Veins Devastation Evoker talent guide, updated Aug 10, 2026 - 7:20 PM",
  patch = "12.1",
  builds = {
    { label = "Scalecommander Raid/Delves", string = "CsbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjZgZYGzMgBjZamZmpZmx2MMzMzMzMzAmxMGzMLzMDMwYwGsMGN2GAzAwGGYmBDD" },
    { label = "Scalecommander Mythic+", string = "CsbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjZAMzwMwMYMTjZmpZmZ2mhZmZmZmZGwMzMGzMLzMDMwYwGsMGN2GAzAwGGYmBDD" },
  },
})

-- EVOKER 1468 (preservation-evoker)
ns.GuideStore:RegisterSiteLoadouts(1468, {
  source = "Icy Veins Preservation Evoker talent guide, updated Aug 28, 2026 - 6:30 AM",
  patch = "12.1",
  builds = {
    { label = "Flameshaper Raiding - Flameshaper", string = "CwbBAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMDmZMYGzmhZmZbAAAMjZMYGzIzMDAAAwMzMZmZmxsNzMAYGzALgFwMMB2MsZYAMzMGA" },
    { label = "Flameshaper Mythic+ - Flameshaper", string = "CwbBAAAAAAAAAAAAAAAAAAAAAAAAAAAmZmZ2WmZGDjxsZGw2wAAAzYGzMjhZiZmBAAAMzMTGzMjxMzAAjZgFwCYGmAbM2MMAmZGD" },
    { label = "Chronowarden Raiding - Chronowarden", string = "CwbBAAAAAAAAAAAAAAAAAAAAAAAAAAAmZmZwMjBzY2MMzMbYAAgZMjBzYGZmZAAAAmZmJzYmxsNzMAYgxM2YBGYGGawYBGzMAjB" },
    { label = "Chronowarden Mythic+ - Chronowarden", string = "CwbBAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMz2yAzYmxsZGjx2wAAAzYGzghZyMzMAAAw2MzMNjZmZGjZAAYMjFWgBmhhGGWgxMDAD" },
  },
})

-- EVOKER 1473 (augmentation-evoker)
ns.GuideStore:RegisterSiteLoadouts(1473, {
  source = "Icy Veins Augmentation Evoker talent guide, updated Aug 10, 2026 - 7:20 PM",
  patch = "12.1",
  builds = {
    { label = "Raiding Build - Chronowarden", string = "CEcBAAAAAAAAAAAAAAAAAAAAAMMzMbzMzgZYmZZGzMjZ2AAAAAAAAYmhxMYM1YmZGAAAAMjZMmZWGzMwMMwYGLsADMDDNwCGjZGAYA" },
    { label = "Weekly Mythic+ Build - Scalecommander", string = "CEcBAAAAAAAAAAAAAAAAAAAAAMMzMbjZmxyMYmtZMzMmBAAAAAAAAmhHYGYM1YmZGAAAAMzMjxMz2YmBmZzYwCsMGGbDgZQshxMYmBDG" },
    { label = "High Key Mythic+ Build - Chronowarden", string = "CEcBAAAAAAAAAAAAAAAAAAAAAMMzMbzMzgZYmZZGzMjZ2AAAAAAAAYmhZGYM1YmZGAAAAMjZMmZWGzMwMMwYGLsADMDDNwCGzMzAAD" },
  },
})
