-- Data/SiteLoadouts.lua
-- GENERATED by tools/fetch_talents.py - do not hand-edit; re-run the script.
--
-- Recommended talent builds from Icy Veins' and Wowhead's per-spec talent pages
-- (Wowhead via tools/wowhead_harvest.js + tools/wowhead_dump.json), as exact
-- Blizzard export strings, each verified to decode to the spec it is filed
-- under. One site's picks at the time the script ran, alongside (not
-- replacing) the SimC-default and live-top-player builds the guides carry.
-- See DESIGN.md's "Guide-site talent builds".
-- Generated: 2026-09-02 20:07 UTC

local ADDON, ns = ...
if not ns.GuideStore then return end

-- WARRIOR 71 (arms-warrior)
ns.GuideStore:RegisterSiteLoadouts(71, {
  source = "Icy Veins Arms Warrior talent guide, updated Aug 25, 2026 - 7:20 PM; Wowhead Arms Warrior talent guide, updated 2026/08/12",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Arms Single-Target - Slayer", string = "CcEAAAAAAAAAAAAAAAAAAAAAAAzMzsMzMmZGAAAghphxYmZzMzMzgxMDAAAAgZWmZAhxyyALgBMDTgZwGYmx2YbglZWGgZGAMDDA" },
    { site = "Icy Veins", label = "Arms Multi-Target - Slayer", string = "CcEAAAAAAAAAAAAAAAAAAAAAAAzMzsMzYmZGAAAghphxYmxyMzMzgxMDAAAAgZWmZgJMW2GYBMgZYCZGsBmZsN2GYZmtBYmBAzwA" },
    { site = "Icy Veins", label = "Arms Dungeons & Delves - Slayer", string = "CcEAAAAAAAAAAAAAAAAAAAAAAgZmZmFzYmZGAAAghphxYmZzMzMzYmxMDAAAAgxyMDMhxy2ALgBMDTgZwGYmhhBzyMbDwMDAmhBA" },
    { site = "Wowhead", label = "Slayer: Raid ST", string = "CcEAAAAAAAAAAAAAAAAAAAAAAAzMzsMzMmZGAAAghphxYmxyMzMzgxMDAAAAgZWmZAhxyyALgBMDTIzgNwMjtx2ALzsMAzMAYGGA" },
    { site = "Wowhead", label = "Slayer: Mythic+", string = "CcEAAAAAAAAAAAAAAAAAAAAAAgZmZmFzYmZGAAAghphxYmZzMzMzYmxMDAAAAgxyMDMhxy2AbgBMDTIzgNwMDDDmlZ2GgZGAMDDA" },
    { site = "Wowhead", label = "Colossus: ST Raid", string = "CcEAAAAAAAAAAAAAAAAAAAAAAAzMzsMzwMDAAAghphxYmxyMzMzgxMDAAAAgZ2mZABwmZMsBDMj2oxgFwMjtx2MzmlZWGMzAAMDDA" },
    { site = "Wowhead", label = "Colossus: MT Raid", string = "CcEAAAAAAAAAAAAAAAAAAAAAAgZmxsMzMzYGAAAghphxYmxyMzMzgxMDAAAAgxmZgJLAbmxwCMwMajGDWAzM2GbjxsZ2GMzAAMDDA" },
    { site = "Wowhead", label = "Colossus: Mythic+", string = "CcEAAAAAAAAAAAAAAAAAAAAAAgZmxsMzMzYGAAAghphxYmZzMzMzYmxMDAAAAgxmZgJLAbmxwCMwMajGDWAzMMMGzmZbwMDAwMMA" },
  },
})

-- WARRIOR 72 (fury-warrior)
ns.GuideStore:RegisterSiteLoadouts(72, {
  source = "Icy Veins Fury Warrior talent guide, updated Aug 25, 2026 - 7:20 PM; Wowhead Fury Warrior talent guide, updated 2026/08/12",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Fury Single-Target - Slayer", string = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDzMmZ2MzMzMDjZmZGzYmlZmxMzMbmZmBAAixy2ALgJYGmAzwGwMDjNAAYmhxYYMYM" },
    { site = "Icy Veins", label = "Fury Multi-target - Slayer", string = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjxMzmZmZmZmZMzMzMzYmlZMmZMbmZmBAAixy2ALgJYGmAzwGwMzmBAAYmhxsMwgxA" },
    { site = "Icy Veins", label = "Fury Dungeons & Delves - Thane", string = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjZMz2yMzMjZmxMzMzMjZWmZmZmxsZmZGAAIMwGssY0YGQmFMjFAzgBAMzAwwiZAGD" },
    { site = "Wowhead", label = "Slayer: Raid ST", string = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDzMmZ2MzMzMDjZmZGzMzsMzMmZmZzYmBAAixy2ALgJYGmAzwGwMDjNAAYmhxYYMYM" },
    { site = "Wowhead", label = "Slayer: Raid MT", string = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjxMzmZmZmZYMzMzMzYmlZMmZMbmZmBAAixy2ALgJYGmAzwGwMzmxGAAMzwYWGGDGD" },
    { site = "Wowhead", label = "Mountain Thane: ST Raid", string = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjZmZ2MzMzMDjZmZGzMzsMzMzMjZ5BGzMAAQYgNYZxoxMgMLYYBwMMzGAMzAMGYMgxA" },
    { site = "Wowhead", label = "Mountain Thane: MT Raid", string = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjZmZ2WmZmZMMmZmZmZMzyMzMzMmFzMzAAAhB2glFjGzAysgZsAYmNGAwMDADLmBYM" },
    { site = "Wowhead", label = "Mountain Thane: Mythic+", string = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjZMz2yMzMjZmxMzMzMjZWmZmZmxsYmZGAAIMwGssY0YGQmFMjFAzgBAMzAwwiZAGD" },
  },
})

-- WARRIOR 73 (protection-warrior)
ns.GuideStore:RegisterSiteLoadouts(73, {
  source = "Icy Veins Protection Warrior talent guide, updated Aug 12, 2026 - 9:20 AM; Wowhead Protection Warrior talent guide, updated 2026/08/12",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Single-Target - Colossus", string = "CkEAAAAAAAAAAAAAAAAAAAAAA02AAAzMDzMzMzMzmxsMjxYmGGDLzMzMDGzMAAAAYZAYGDAsYGDbwAzwCNmZBmxMDmNAAzMAgZgxA" },
    { site = "Icy Veins", label = "AoE - Mountain Thane", string = "CkEAAAAAAAAAAAAAAAAAAAAAA0yAAAjZYmZmZGziZmlZMGz0YGDLmZmZMDzMAAAAYZAYGDwAbw2iRjZAMLYmNYmZmhxCAMzAAwAGD" },
    { site = "Icy Veins", label = "Delves - Mountain Thane", string = "CkEAAAAAAAAAAAAAAAAAAAAAAkBAAGzYmZmZmxsYmZZGjxMNmxwiZmZGzwMDAAAAWGAmxAMwGstY0YGAzCmZDmZmZYsAAzMAAMgxA" },
    { site = "Icy Veins", label = "Defensive Raid Build", string = "CkEAAAAAAAAAAAAAAAAAAAAAAkBAAmZGmZmZmxsZmZZGjxMNMGWmZmZGMmZAAAAwyMDwMGgB2glFjGzAY2wMbgxMDmNAYmBAgZgxA" },
    { site = "Icy Veins", label = "Defensive Mythic+ Build", string = "CkEAAAAAAAAAAAAAAAAAAAAAAkBAAGzwMzMzMmFzMLzYMmpxMGWMzMzYGmZAAAAwyMDwMGgB2gtFjGzAYWwMbYYmZYsAAzMAAMgxA" },
    { site = "Icy Veins", label = "Defensive Raid Build", string = "CkEAAAAAAAAAAAAAAAAAAAAAAkBAAmZGmZmZmxsZmZZGjxMNMGWmZmZGMmZAAAAwyMDwMGAYxMG2gBmhFaMzCYMzgZDAwMDAYGYMA" },
    { site = "Icy Veins", label = "Defensive Mythic+ Build", string = "CkEAAAAAAAAAAAAAAAAAAAAAAkBAAGzwMzMzMmFzMLzYMmpxMGWMzMzYGmZAAAAwyMDwMGAYxMGWgBmhFaMzCYmZGGLAAmZAADYMA" },
    { site = "Wowhead", label = "Colossus: Raid", string = "CkEAAAAAAAAAAAAAAAAAAAAAA0yAAAzMDzMzMzMzmxsMjxYmGmZGLjZmZYGzMAAAAYZAYGDAsZGDbkBmhFaMzCMDzgZDAwMDAYAjB" },
    { site = "Wowhead", label = "Colossus: Mythic+", string = "CkEAAAAAAAAAAAAAAAAAAAAAA0yAAAjZYmZmZGzmZmlZMGz0YGzYZMzMDzYmBAAAALDAzYAgNzYYjMwMsQjZWgZGzgZDAwMDAYAjB" },
    { site = "Wowhead", label = "Mountain Thane: Raid", string = "CkEAAAAAAAAAAAAAAAAAAAAAA0yAAAzMzYmZGzY2MzsMjxYmGmZYZMzMDzYmBAAAAbDAzYAGYD2WMaMDgZLmZDmxMDmNAYmBAgBMG" },
    { site = "Wowhead", label = "Mountain Thane: Mythic+", string = "CkEAAAAAAAAAAAAAAAAAAAAAAkBAAGzYmZmZmxsZmZZGjxImxwyMzMzYGmZAAAAwyMDwMGgB2glFjGzAYWiZ2AmZGGbAwMDAAzAjB" },
  },
})

-- PALADIN 65 (holy-paladin)
ns.GuideStore:RegisterSiteLoadouts(65, {
  source = "Icy Veins Holy Paladin talent guide, updated Aug 10, 2026 - 7:20 PM; Wowhead Holy Paladin talent guide, updated 2026/08/12",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Herald of the Sun Raiding - HeraldoftheSun", string = "CEEAAAAAAAAAAAAAAAAAAAAAAAAAALAwMAAw2MzMjZMzYxYmZYZwMLmpJGzYmZYMbZAYADbgNWmxMLz2Mzs1AAAAsAAbGGzYGmBAwMDzghB" },
    { site = "Icy Veins", label = "Herald of the Sun Mythic+ - HeraldoftheSun", string = "CEEAAAAAAAAAAAAAAAAAAAAAAAAAgZBAmBAA2GzMzMjZmZBmZYZsZmFjmYWmxMzwY2yAwAwGYjlZmZWmtZmZrBAAAYBMD2AGGMDAgZGmxYYA" },
    { site = "Icy Veins", label = "Lightsmith Mythic+ - Lightsmith", string = "CEEAAAAAAAAAAAAAAAAAAAAAAAAAgZBAmBAA2GzMzMjZmZBmZYZsZmFjmYWmxMzwY2yAwAwGYjlZmBAAAmZ22WsNzwGYGsBMMYGAzMAMjxoB" },
    { site = "Wowhead", label = "Herald of the Sun: Raid", string = "CEEAAAAAAAAAAAAAAAAAAAAAAAAAALAwMAAw2MzMjZMzYxYmZYZwMLmpJGGzMDjZLDADYYDsxyMmZZ2mZmtGAAAgFAYzwYGzwMAAmZYGjRDA" },
    { site = "Wowhead", label = "Herald of the Sun: Raid (2)", string = "CEEAAAAAAAAAAAAAAAAAAAAAAAAAALAwMAAwyMzMjZ2mZmNYMsM2MziZaihxMzwY2yAwAG2AbsMjZWmtZmZrBAAAYBA2MMmxMMDAgZGmxY0A" },
    { site = "Wowhead", label = "Herald of the Sun: Mythic+", string = "CEEAAAAAAAAAAAAAAAAAAAAAAAAAALAwMAAD2GzMzMjZmZBmZYZsZmFjmYYMzMMmtMAMAsB2YZmZmlZbmZ2aAAAAWAmhNDMjZYGAAzMMjxoB" },
    { site = "Wowhead", label = "Herald of the Sun: Mythic+ (2)", string = "CEEAAAAAAAAAAAAAAAAAAAAAAAAAALAwMAADWGzMzMjZmZBGDLzsZmFjmYYMzMMmtMAMAsB2YZmZmlZbmZ2aAAAAWAmhNDMjZwAAYmhZMGNA" },
    { site = "Wowhead", label = "Herald of the Sun: Delves", string = "CEEAAAAAAAAAAAAAAAAAAAAAAAAAALAwMAADMmZmZGzMzixMmxyYzMLGNxYGjZYMbZAYAYDsxyMzMLz2Mzs1AAAAsAMDbGYGzwAAwMDzYMaA" },
    { site = "Wowhead", label = "Lightsmith: Raid", string = "CEEAAAAAAAAAAAAAAAAAAAAAAAAAAbAwMAAw2MzMjZMzYxYmZYZwMLmpJGGzMDjZLDADYYDsxyMGAEAwMzyyitZG2AgNDjZMDzAYmBgZMGNA" },
    { site = "Wowhead", label = "Lightsmith: Raid (2)", string = "CEEAAAAAAAAAAAAAAAAAAAAAAAAAALAwMAAwyMzMjZMzMbGzYYZsZmFz0EDjZmhxslBgBMsB2YZGDACAYmZZZx2MDbAwmhxMmhBgZGAmxY0A" },
    { site = "Wowhead", label = "Lightsmith: Mythic+", string = "CEEAAAAAAAAAAAAAAAAAAAAAAAAAAbAwMAAD2GzMzMjZmZBmZYZsZmFjmYYMzMMmtMAMAsB2YZmZAQAAzMLLL2mZYDYG2MwMmhZAMzAwMGjGA" },
    { site = "Wowhead", label = "Lightsmith: Mythic+ (2)", string = "CEEAAAAAAAAAAAAAAAAAAAAAAAAAALAwMAADWGzMzMjZmZZwYYZsZmFz0EDjZmhxslBgBgNwGLzMDACAYmZZZx2MDbAzwmBmxMMAMzAwMGjGA" },
    { site = "Wowhead", label = "Lightsmith: Delves", string = "CEEAAAAAAAAAAAAAAAAAAAAAAAAAALAwMAADMmZmZGzMzixMmxyYzMLGNxwYMDjZLDADAbgNWmZGAEAwMz22ilZG2AzMsZgZYYAYmBgZMGNA" },
  },
})

-- PALADIN 66 (protection-paladin)
ns.GuideStore:RegisterSiteLoadouts(66, {
  source = "Icy Veins Protection Paladin talent guide, updated Aug 18, 2026 - 11:20 PM; Wowhead Protection Paladin talent guide, updated 2026/08/12",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Raid / Single Target - Templar", string = "CIEAAAAAAAAAAAAAAAAAAAAAAsZmtZZmZMzMzMWGjxw2MGAAAAAAAAINGmxMzYMbtBgBMwMYbAAgZm2mZWmBAYjNMAGjZYMAALzAmZGwYB" },
    { site = "Icy Veins", label = "AoE / Mythic+ - Templar (Weekly Keys)", string = "CIEAAAAAAAAAAAAAAAAAAAAAAsZYWGzYmZmZW2GjZZWmlZMAAAAAAAAQTzMMjZGGzWbAYgBMD2GAAYmptZmlZAA2ssgBAjZYMAALzAmZGwYB" },
    { site = "Icy Veins", label = "AoE / Mythic+ - Templar (High Keys)", string = "CIEAAAAAAAAAAAAAAAAAAAAAAsZsMLjZMzMzMLbjxsMmlZMAAAAAAAAQTzMMjZGGzWbAYgBMD2GAAYmptZmlZAA2ssgBAjZYMAALzAmZGwYB" },
    { site = "Wowhead", label = "Templar: Raid", string = "CIEAAAAAAAAAAAAAAAAAAAAAAsNzYWmZYGzM2WGDLzithBAYAAAAAAQamZxMmZGjZrNAMgBMYbAAgZm2mZWmBAYzyGzYAMmhxAAsNDwMDyYD" },
    { site = "Wowhead", label = "Templar: Mythic+", string = "CIEAAAAAAAAAAAAAAAAAAAAAAsZeAzyYGzYmZWWGjZZWmlZMAADAAAAAAaamhZMzwY2aDADMgZw2AAAzMtNzsMDAwmlFMAgZYMAALzAmZGkxC" },
    { site = "Wowhead", label = "Lightsmith: Raid", string = "CIEAAAAAAAAAAAAAAAAAAAAAAsNzYWmZYGzM2WGDLzithBAYAAAAAAQamZxMmZGjZrNAMgBMYbAAAEgZmttlWmZsYZjZMAGzwYAwMDAmZQGb" },
    { site = "Wowhead", label = "Lightsmith: Mythic+", string = "CIEAAAAAAAAAAAAAAAAAAAAAAsZeAzyYGzYmZWWGjZZWmlZMAADAAAAAAaamhZMzwY2aDADMgZw2AAAIAzMbbLtMzYxyCGAwMMGAMzAwMzgMWA" },
  },
})

-- PALADIN 70 (retribution-paladin)
ns.GuideStore:RegisterSiteLoadouts(70, {
  source = "Icy Veins Retribution Paladin talent guide, updated Aug 25, 2026 - 10:27 PM; Wowhead Retribution Paladin talent guide, updated 2026/08/25",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Retribution Single Target - Herald of the Sun", string = "CYEAAAAAAAAAAAAAAAAAAAAAAAAAAAANbbzMzywMDAAAAAAzUGzwMjtxsNMz2MGjxwMWYbAYWmtZmZrBBAAsAYAwYGmBzYmZDYmZYMjBD" },
    { site = "Icy Veins", label = "Retribution AoE - Herald of the Sun", string = "CYEAAAAAAAAAAAAAAAAAAAAAAAAAAAwoZbbmZWGzMzAAAAAAYmyYGmZsNmthZ2mxYMGmxCbAYWmtZmZrBBAAsAYAwYGGYGzMbAzMDjZMYA" },
    { site = "Icy Veins", label = "Retribution Delves - Templar", string = "CYEAAAAAAAAAAAAAAAAAAAAAAAAAAAwoZbbmZWGjZmBAAAAAYmyYGMjtZmthZ2mxYMzwM2YDAAgZm2mZ2mBAsBYAAzwAzYGbYZGMmxMGMA" },
    { site = "Wowhead", label = "Templar: Raid", string = "CYEAAAAAAAAAAAAAAAAAAAAAAAAAAAANbbzMzywMDAAAAAAzUGzwMjtxsNMz2MGjxwMWYbAAAZmptZmtZAAbAGAMmhZwMmZ2w2MYYMjBD" },
    { site = "Wowhead", label = "Templar: Mythic+", string = "CYEAAAAAAAAAAAAAAAAAAAAAAAAAAAwoZbbmZWGzMzAAAAAAYmyYGmZsNmthZ2mxYMGmxGbAAAZmptZmtZAAbAGAMmhBmxMzGWmBDjZMYA" },
    { site = "Wowhead", label = "Templar: Delves", string = "CYEAAAAAAAAAAAAAAAAAAAAAAAAAAAwoZbbmZWGjZmBAAAAAYmyYGMjtZmthZ2mxYMzwM2YDAAIzMtNzsNDAYDwAAmhBmxM2wyMYMjZMYA" },
    { site = "Wowhead", label = "Herald of the Sun: Delves", string = "CYEAAAAAAAAAAAAAAAAAAAAAAAAAAAwoZbbmZWGjZmBAAAAAYmyYGMjtZmthZ2mxYMzwMWYDAzysNzMbNIAAgFADAYGGYGzYDYmZMjZMYA" },
  },
})

-- HUNTER 253 (beast-mastery-hunter)
ns.GuideStore:RegisterSiteLoadouts(253, {
  source = "Icy Veins Beast Mastery Hunter talent guide, updated Aug 30, 2026 - 11:04 AM; Wowhead Beast Mastery Hunter talent guide, updated 2026/08/12",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Beast Mastery Single-Target - Pack Leader", string = "C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwCsAzwwMsBAgZYMzyMDzYmhhZGjZGzMjZMziZmxMmBjpZAAAAAzAAAwYmZAmZjxGMLgtBgB" },
    { site = "Icy Veins", label = "Beast Mastery Raid AoE/Cleave - Pack Leader", string = "C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwCsAzwQDbAAYGmZmlZGzMzMjZGMzYmhZGzYmFzMjZMDGTzAAAAAAAAgxMzAMzGZDmFw2AwA" },
    { site = "Icy Veins", label = "Beast Mastery Mythic+ - Pack Leader", string = "C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwCsAzwQDbAAYGzMzs8AzYmZmZMzgZGzMMzYmZGbzMjZMDLjpZAAAAAAAAgHYMGwMbEwsA2GAA" },
    { site = "Icy Veins", label = "Beast Mastery Delves - Pack Leader", string = "C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwCsAzwQDbAAYGzMzs8AzYmZmZMzgZGzMMzYmZGMGzYmhx0AAAAAAAAAzMGDYmNCWmZBsNAA" },
    { site = "Wowhead", label = "Pack Leader: Raid", string = "C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwCsAzwQDbAAYGGzsMzwMmZYYmxYmxMzYGzwMzYGzghmBAAAAMDAAAzMzMAzsRYYWAbDAD" },
    { site = "Wowhead", label = "Pack Leader: Mythic+", string = "C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwCsBzwQDbAAYGPwMzsMzwMzMjZGMzYmhZGzMzYbmZYMDLDNDAAAAAAAAmHYMzAmZjAmFw2AwA" },
    { site = "Wowhead", label = "Pack Leader: Delves", string = "C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwCsAzwQDbAAYGPwMzsMzwMzMjZGMzYmhZmZGzwMzwYmhx0MAAAAAAAAYMmBYmNCWmZBsNAM" },
    { site = "Wowhead", label = "Dark Ranger: Raid", string = "C0PAAAAAAAAAAAAAAAAAAAAAAYzsNwAGwMsBZsAAgZMjZWMDzYmxMMzYYGzMjZMDzMjZMDGaGAAAAwMAAAMzMzgZGQYYWAbDAD" },
    { site = "Wowhead", label = "Dark Ranger: Mythic+", string = "C0PAAAAAAAAAAAAAAAAAAAAAAYzsNwAGwMsBZsAAgZGzMziZYGmxMjZmZYGzMjZmZsNzMMmhlhmBAAAAMDAAAzDMmZYmBEwsA2GAA" },
    { site = "Wowhead", label = "Dark Ranger: Delves", string = "C0PAAAAAAAAAAAAAAAAAAAAAAYzsNwAGwMsBZsAAgZGzMziZYGmxMjZmZYGzMzMjZYmZYMzwYaGAAAAwMAAAMGzgZGQwyMLgtBA" },
  },
})

-- HUNTER 254 (marksmanship-hunter)
ns.GuideStore:RegisterSiteLoadouts(254, {
  source = "Icy Veins Marksmanship Hunter talent guide, updated Aug 22, 2026 - 4:31 PM; Wowhead Marksmanship Hunter talent guide, updated 2026/08/12",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Marksmanship Single Target - Sentinel", string = "C4PAAAAAAAAAAAAAAAAAAAAAAwCMwMGzYZAjZwGAAAAAAAAYGzYmFzYmZMDGTzYwYbZmZmZmZmZWYmlBzAAAGzMjBwM22gBYjZ2mxAA" },
    { site = "Icy Veins", label = "Marksmanship Raid AoE/Cleave - Sentinel", string = "C4PAAAAAAAAAAAAAAAAAAAAAAwCMwMGzYZAjZwGAAAAAAAAYGzYmFzYmZMDGTzYwstZmZmZmZmZWYmlhZAAAGzMjBwM22gBYjZ2mxAA" },
    { site = "Icy Veins", label = "Marksmanship Mythic+ - Sentinel", string = "C4PAAAAAAAAAAAAAAAAAAAAAAwGMwMGzYZAjZwGAAAAAAAAYGzMzYbGzMjZYZMNjBzy22MzMzMzMzswMLDzAAA4BGjBgZsBGgNmZbGD" },
    { site = "Icy Veins", label = "Marksmanship Delves - Sentinel", string = "C4PAAAAAAAAAAAAAAAAAAAAAAwGMwMGzYZAjZwGAAAAAAAAYGzMzgxMzYmhx0wgZZbbmZmZmZmZWwsNMDAAwMjxAwM2wyMAbMz2MG" },
    { site = "Wowhead", label = "Sentinel: Single Target", string = "C4PAAAAAAAAAAAAAAAAAAAAAAwCMwMGzYZAMD2AAAAAAAAAzYmZmFzYmZMDGTzYwYbZmZmZmZmZWwsMYGAAwYmZMAmptNYA2YmtZMA" },
    { site = "Wowhead", label = "Sentinel: Raid AoE/Cleave", string = "C4PAAAAAAAAAAAAAAAAAAAAAAwCMwMGzYZAMD2AAAAAAAAAzYmZmFzYmZMDGTzYwstZmZmZmZmZWwsMMDAAwYmZMAmptNYA2YmtZMA" },
    { site = "Wowhead", label = "Sentinel: Mythic+", string = "C4PAAAAAAAAAAAAAAAAAAAAAAwGMwMGzYZAMD2AAAAAAAAAzYmZGbzYmZMDLjpZMYW22mZmZmZmZmFmZZYGAAAPwYMAMTbgBYjZ2mxA" },
    { site = "Wowhead", label = "Sentinel: Delves", string = "C4PAAAAAAAAAAAAAAAAAAAAAAwGMwMGzYZAMD2AAAAAAAAAzYmZGMmZGzMMmGGMLbLzMzMzMzMzCmthZAAAmZMGAmpNsMDwGzsNjB" },
    { site = "Wowhead", label = "Dark Ranger: Single Target", string = "C4PAAAAAAAAAAAAAAAAAAAAAAYzsMwAmgZYbAzCAAAAAAAAYGzMzsYGzMjZwYaGDGbLzMzMzMzMzCmlBDAAwYmZMzMDIbwAsxMbzYA" },
    { site = "Wowhead", label = "Dark Ranger: Mythic+", string = "C4PAAAAAAAAAAAAAAAAAAAAAAYzsMwAmgZYbAzCAAAAAAAAYGzMzYbGzMjZYZMNjBzymZMzMzMzMLMzywMAAAegxYmZmBEwAsxMbzYA" },
    { site = "Wowhead", label = "Dark Ranger: Delves", string = "C4PAAAAAAAAAAAAAAAAAAAAAAYzsMwAmgZYbAzCAAAAAAAAYGzMzgxMzYmhx0wgZZzMmZmZmZmFMbDzAAAMzYMzMzACWmBYjZ2mxA" },
  },
})

-- HUNTER 255 (survival-hunter)
ns.GuideStore:RegisterSiteLoadouts(255, {
  source = "Icy Veins Survival Hunter talent guide, updated Aug 18, 2026 - 7:46 PM; Wowhead Survival Hunter talent guide, updated 2026/08/27",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Survival Single Target - Sentinel", string = "C8PAAAAAAAAAAAAAAAAAAAAAAMWgBmxoxyAYmgtZMzMGzyAAAAAAwMmxMLmxYGzgx0MAAAADAmxyyMzsYMzMjZmBAzYZDGDjNDAA" },
    { site = "Icy Veins", label = "Survival Mythic+ - Sentinel", string = "C8PAAAAAAAAAAAAAAAAAAAAAAMWgBmxYGLDgZGYbmZmZmxsNPAAAAAAgZMzMjtZMmxMsMmmBAAAYAgxyyMjFMzMegxYAYGbgxYmZzAAA" },
    { site = "Icy Veins", label = "Survival Delves - Sentinel", string = "C8PAAAAAAAAAAAAAAAAAAAAAAMWgBmxYGLDgZGYbmZmZmxsNPAAAAAAgZMzMDGjZMzwYaAAAAAAGLLzMWwMzMzYMAMjNsMjxMzmBAAA" },
    { site = "Wowhead", label = "Pack Leader: Raid", string = "C8PAAAAAAAAAAAAAAAAAAAAAAMgxMGWIbwMM0gFjZmxMWGAAAAAAmZmZmhZMmxMYMNDAAAwAgZssMzMLMzMzYmxAmZDAjxMWMAA" },
    { site = "Wowhead", label = "Pack Leader: Mythic+", string = "C8PAAAAAAAAAAAAAAAAAAAAAAMgxMG2ILwMM0gFzMzMzMWGAAAAAAmZmZmhZMmxMYMNDAAAwAgHYssMzYhZmZGzMGwMbAYMmZWMAA" },
    { site = "Wowhead", label = "Pack Leader: Delves", string = "C8PAAAAAAAAAAAAAAAAAAAAAAMgxMG2ILwMM0gFzMzMzMWGAAAAAAmZmZmhZMMmZYMNDAAAwAgHYssMzYhZmZGjxAmZDgZMmZWMAA" },
    { site = "Wowhead", label = "Sentinel: Raid", string = "C8PAAAAAAAAAAAAAAAAAAAAAAMWgBmxoxyAYmgNjZmxwyAAAAAAwMmZmhZMmxMYMNDAAAwAgZstMzMLmZmZGzMzAwMWAjxMWMAA" },
    { site = "Wowhead", label = "Sentinel: Mythic+", string = "C8PAAAAAAAAAAAAAAAAAAAAAAMWgBmxoxyAYmgtZmZmxMz2MAAAAAAmxMzMMjxMmBjpZAAAAGAgltZGLzYmxYMzAwM2wixwMLGAA" },
    { site = "Wowhead", label = "Sentinel: Mythic+ (2)", string = "C8PAAAAAAAAAAAAAAAAAAAAAAMWgBmxoxyAYmgtZmZmxMz2MAAAAAAmxMzMMjxMmBjpZAAAAGAgltZGbzYmxYMzAwM2wixwMLGAA" },
    { site = "Wowhead", label = "Sentinel: Delves", string = "C8PAAAAAAAAAAAAAAAAAAAAAAMWgBmxoxyAYmgtZmZmZmZ2mBAAAAAwMzMzMMjhxMDjpZAAAAGAgltZGLDzMGjxAwM2gZMMziBA" },
  },
})

-- ROGUE 259 (assassination-rogue)
ns.GuideStore:RegisterSiteLoadouts(259, {
  source = "Icy Veins Assassination Rogue talent guide, updated Aug 10, 2026 - 7:20 PM; Wowhead Assassination Rogue talent guide, updated 2026/09/01",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Assassination Pure Single-Target - Fatebound", string = "CMQAAAAAAAAAAAAAAAAAAAAAAYmlxsNDGAAAAAY2GsNDAAAAAIbzMzMzMjxyMzMbzsMzMzYGzYMmZMMAGYBmxoxsBYbAbGAMzMGD" },
    { site = "Icy Veins", label = "Assassination Raid Cleave - Fatebound", string = "CMQAAAAAAAAAAAAAAAAAAAAAAYmlxsZwAAAAAAzygtZAAAAAAttNzMzMzMGLzMzsNzyMz8AjxMjxYmZmxAYgFYGjGzGgtBsZAwMzgB" },
    { site = "Icy Veins", label = "Assassination Mythic+/Delves - Fatebound", string = "CMQAAAAAAAAAAAAAAAAAAAAAAYmlZmFDAAAAAAzygtZAAAAAAttNzMzMzMGLzMzsNzyMz8AmxMjxwMjxAYgFYGjGzCgtBsZAwMzMMA" },
    { site = "Wowhead", label = "Deathstalker: Raid Single Target", string = "CMQAAAAAAAAAAAAAAAAAAAAAAYmlxsNDGAAAAAYWGsNDAAAAAottZmZmZmxYZmZmtZWmZmZMjZMGzMGGgNzyADYJYZYCMsAmZAGjB" },
    { site = "Wowhead", label = "Deathstalker: Raid", string = "CMQAAAAAAAAAAAAAAAAAAAAAAYmlxsZwAAAAAAzygtZAAAAAAttNzMzMzMGLzMzsNzyMz8AjxMjxYmZmxAsZWGYALBLDTghFwMDwYMA" },
    { site = "Wowhead", label = "Deathstalker: Mythic+", string = "CMQAAAAAAAAAAAAAAAAAAAAAAYmlZmFDAAAAAAzygtZAAAAAAttNzMzMzMGLzMzsNzyMz8AmxMjxMmZMGgNzyADYJYZYCMsYwMDgZ8BA" },
    { site = "Wowhead", label = "Fatebound: Raid Single Target", string = "CMQAAAAAAAAAAAAAAAAAAAAAAYmlxsNDGAAAAAYWGsNDAAAAAottZmZmZmxYZmZmtZWmZmZMjZMGzMGGADsAzY0Y2AZbAbGAMzMYA" },
    { site = "Wowhead", label = "Fatebound: Raid", string = "CMQAAAAAAAAAAAAAAAAAAAAAAYmlxsZwAAAAAAzygtZAAAAAAttNzMzMzMGLzMzsNzyMz8AjxMjxYmZmxAYgFYGjGzGIbDYzAgZmBD" },
    { site = "Wowhead", label = "Fatebound: Mythic+", string = "CMQAAAAAAAAAAAAAAAAAAAAAAYmlZmFDAAAAAAzygtZAAAAAAttNzMzMzMGLzMzsNzyMz8AmxMjxMmZMGADsAzY0YWAZbAbGAMzMDfA" },
  },
})

-- ROGUE 260 (outlaw-rogue)
ns.GuideStore:RegisterSiteLoadouts(260, {
  source = "Icy Veins Outlaw Rogue talent guide, updated Aug 10, 2026 - 7:20 PM; Wowhead Outlaw Rogue talent guide, updated 2026/08/12",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Outlaw Single Target - Trickster", string = "CQQAAAAAAAAAAAAAAAAAAAAAAAgx2MMzMmZmtZmZmZMmF4BmZbaZw2MAAAAAALLzMzwMzMziZmZbAAAAYmBAjZxwADMLsQLsxAMzgBG" },
    { site = "Icy Veins", label = "Outlaw AoE - Trickster", string = "CQQAAAAAAAAAAAAAAAAAAAAAAAgx2MMzMjZmtZmZMzMzsAmZbaZw2MAAAAAALLzMzwMzMziZmZbAAAAYmBAjZxwADMLsQLsxAMzgBG" },
    { site = "Wowhead", label = "Trickster: Raid", string = "CQQAAAAAAAAAAAAAAAAAAAAAAAgx2MMzMmZmtZmZmZMmF4BmZbaZw2MAAAAAAbbzMzwMzMziZmZbAAAAYmBAjZxwQGYWYhWYjBYmBDMA" },
    { site = "Wowhead", label = "Trickster: Mythic+", string = "CQQAAAAAAAAAAAAAAAAAAAAAAAgx2MMzMjZmtZmZMzMzsAmZbaZw2MAAAAAAbbzMzwMzMziZmZbAAAAYmBAjZxwQGYWYhWYjBYmBDMA" },
    { site = "Wowhead", label = "Trickster: Delves", string = "CQQAAAAAAAAAAAAAAAAAAAAAAAgx2MMzMjZmtZmZMzMzsAmZbaZw2MAAAAAA2mZmhZmZmFzMz2AAAAwYAwYWMMkBmFWoF2YAmZwMYG" },
    { site = "Wowhead", label = "Fatebound: Raid", string = "CQQAAAAAAAAAAAAAAAAAAAAAAAgx2MMzMmZmtZmZmZMmF4BmZbaZw2MAAAAAAbbzMzwMzMziZmZbAAAAYmBMwGMjRjZDw2EWYAwMzAD" },
    { site = "Wowhead", label = "Fatebound: Mythic+", string = "CQQAAAAAAAAAAAAAAAAAAAAAAAgx2MMzMjZmtZmZMzMzsAmZbaZw2MAAAAAAbbzMzwMzMziZmZbAAAAYmBMwGMjRjZDw2EWYAgZGYA" },
    { site = "Wowhead", label = "Fatebound: Delves", string = "CQQAAAAAAAAAAAAAAAAAAAAAAAgx2MMzMjZmtZmZMzMzsAmZbaZw2MAAAAAA2mZmhZmZmFzMz2AAAAwYADsBzY0Y2AsNhFGAMzMDmB" },
  },
})

-- ROGUE 261 (subtlety-rogue)
ns.GuideStore:RegisterSiteLoadouts(261, {
  source = "Icy Veins Subtlety Rogue talent guide, updated Aug 10, 2026 - 7:20 PM; Wowhead Subtlety Rogue talent guide, updated 2026/08/20",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Single-Target - Deathstalker", string = "CUQAAAAAAAAAAAAAAAAAAAAAAAgx2MAAAAAwsMGLTMbbjxMDDzMzMzw8AbzYGbbzMzMzMjBjZ2GAAAAGMmFzyADYBsMMBmFMDzMAzYA" },
    { site = "Icy Veins", label = "Mythic+/AoE - Trickster", string = "CUQA5HmDzx68KWyrW/8Y781L7Dgx2MAAAAAwsMGLTMbLjxMMjZmZmZGGbzYGbbzMzMzMjBjZ2GAAAAGMGwY2MMwAziWoFbYGwMDmxA" },
    { site = "Icy Veins", label = "High Mythic+ - Deathstalker", string = "CUQAAAAAAAAAAAAAAAAAAAAAAAgx2MAAAAAwsMGLTMbLjxMMjZmZmZGGbzYGbbzMzMzMjBjZ2GAAAAGMmFzyADYBsMMhMLYGmZAmxA" },
    { site = "Wowhead", label = "Deathstalker: Raid", string = "CUQAAAAAAAAAAAAAAAAAAAAAAAgx2MAAAAAwsMGLTMbbjxMDDzMzMzw8AbzYGbbzMzMzMjBjZ2GAAAAGMmFzyADYBsMMhMLYGmZAmxA" },
    { site = "Wowhead", label = "Deathstalker: Mythic+", string = "CUQAAAAAAAAAAAAAAAAAAAAAAAgx2MAAAAAwsMGLTMbbjxMDjZmZmZGGbzYGbbzMzMzMjBjZ2GAAAAGMmFzyADYBsMMhMLYGmZAmxA" },
    { site = "Wowhead", label = "Trickster: Raid", string = "CUQAAAAAAAAAAAAAAAAAAAAAAAgx2MAAAAAwsMGLTMbbjxMDDzMzMzw8AbzYGbbzMzMzMjBjZ2GAAAAGMGwY2MMwAziWoFbYGwMDmxA" },
    { site = "Wowhead", label = "Trickster: Mythic+", string = "CUQAAAAAAAAAAAAAAAAAAAAAAAgx2MAAAAAwsMGLTMbLjxMDDzMzMzw8AbzYGbbzMzMzMjBjZ2GAAAAGMGwY2MMwAziWoFbYGwMDmxA" },
  },
})

-- PRIEST 256 (discipline-priest)
ns.GuideStore:RegisterSiteLoadouts(256, {
  source = "Icy Veins Discipline Priest talent guide, updated Aug 18, 2026 - 7:20 PM; Wowhead Discipline Priest talent guide, updated 2026/08/12",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Voidweaver Raid", string = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMmxyYmBzgZbmtZmZmZmBAAAAAAAAAgZYZGMzMDzYmBMNTzMYmBAAY2mtFwYzAAwYMzYwMYmBjgB" },
    { site = "Icy Veins", label = "Oracle Mythic+", string = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMDWmZMmBmZbmtZmZmxMDAAAAAAAAAgZYZGMzMzwYmBbmmJGgZWwQYMLDwYwCAAMmZmxgZAmZGBzA" },
    { site = "Wowhead", label = "Oracle: Raid", string = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMGWmZmBDmZbmtZmZmxMDAAAAAAAAAgZYZGMzMDmxMgpZamBYmNMEGzyAMGsAAAjxMjBzAMzMTwA" },
    { site = "Wowhead", label = "Oracle: Mythic+", string = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMDWmZMmBmZbmtZmZmxMDAAAAAAAAAgxYZGMzMjNjZGsZamYAmZDDhxsMAjBLAAwYmZGDmBYmZEMD" },
    { site = "Wowhead", label = "Voidweaver: Raid", string = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMmxyYmBzgZbmtZmZmZmBAAAAAAAAAgZYZGMzMDzwMgpZamBzMAIAmtZbBM2MAAMGzMGmZwMDGBD" },
    { site = "Wowhead", label = "Voidweaver: Mythic+", string = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMzMWYMGzgZzsNzMzMzMDAAAAAAAAAgxYZGMzMjNjZGsZamYwMDACgZb2WAjNDAAjZmZMYGMzgRwM" },
  },
})

-- PRIEST 257 (holy-priest)
ns.GuideStore:RegisterSiteLoadouts(257, {
  source = "Icy Veins Holy Priest talent guide, updated Aug 25, 2026 - 12:20 PM; Wowhead Holy Priest talent guide, updated 2026/08/24",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Holy Priest Raid - Oracle Easy Mode", string = "CEQAAAAAAAAAAAAAAAAAAAAAAADAAAAAAYBmZWGzMmZMMDzsMzYGAAAAzYWmBzMzwMMjBMTBwMLYIMmtBYMwiZmZBgZMzYMMzAMzMgB" },
    { site = "Icy Veins", label = "Holy Priest Raid - Archon", string = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAgZmlxYMzMDzMzYZGmBAAAwwsMDzMzMMDzYAzUAgZWMDziBAGD2MzMLAaGzMGDzMbLDwAGA" },
    { site = "Icy Veins", label = "Holy Priest Delves & M+ - Oracle", string = "CEQAAAAAAAAAAAAAAAAAAAAAAADAAAAAAgZmxsMMjZGDzwYZmZmBAAAwYmlZwMzM2MmZMgZKAmZBDhxsNAjBWMzMLAMjZGjBzAMzMgB" },
    { site = "Wowhead", label = "Archon: Raid", string = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAgZmlxMjZmZYmZYZGmBAAAwwsMDzMzMYGzAYmaAgZWMTmFDAMGsZmZ2A0MMjxwMz2yAMDMA" },
    { site = "Wowhead", label = "Archon: Mythic+", string = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAMmxsMYMzMDzMDLzMzMAAAAGzsMDmZmBjZGDYmCAMzmZysZAgxgNzM2A0MmZMGmZ2WGgBMA" },
    { site = "Wowhead", label = "Archon: Delves", string = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAMmxsMmxMzYYmBLzMzMAAAAGmlZGzMzM2MmZMbLYmCAMziZysZAgxgNzM2A0wMMGMz2yAMgB" },
    { site = "Wowhead", label = "Oracle: Raid", string = "CEQAAAAAAAAAAAAAAAAAAAAAAADAAAAAAYBmZWGzMmZMMDzsMzYGAAAAzYWmBzMzwMMDgZqBwMbYIMmlBYMwiZmZBQzYMGDzMAzMzAD" },
    { site = "Wowhead", label = "Oracle: Mythic+", string = "CEQAAAAAAAAAAAAAAAAAAAAAAADAAAAAAgZmxsMmZMzYYGYZmZmBAAAwYmlZwMzM2mxMDgZKAmZDDhxsMAjBWMzMLAaGzMGDmBYmZAD" },
  },
})

-- PRIEST 258 (shadow-priest)
ns.GuideStore:RegisterSiteLoadouts(258, {
  source = "Icy Veins Shadow Priest talent guide, updated Sep 1, 2026 - 8:15 PM; Wowhead Shadow Priest talent guide, updated 2026/08/12",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Shadow Raid - Archon", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMz2MGzw2MzYmZGbIzYxMNAzAMzmZY2MAkxYBAzMgxMzMmNmZbZAmBDA" },
    { site = "Icy Veins", label = "Shadow AoE - Voidweaver", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMzyMzYG2mZGzMzYDZGLmpBYmZGAIAz2stAmNGAYwYmZGzGzgZGMDGA" },
    { site = "Icy Veins", label = "Shadow Delves - Voidweaver", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMzyMzYmx2MYmZmZDZGLb0AMzMDAEgZb2WAzGDAMwMzMzMbMDmZwMYA" },
    { site = "Icy Veins", label = "Archon Raid - No 4pc Season 2", string = "CIQAR03Gt7xPmcDNOjs2Zlb3yOMjZGAAAAAAAAAAAgxMMjx2MDzsNzwMjtZMmZmBmMwMNzAzAMzmZ0sZAIjxCAmBYMzMjZbMz2yAMDGA" },
    { site = "Icy Veins", label = "Archon Raid - Sszorak", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDzAAAAAAAAAAAAwMLmxMbzMGz2MGzw2MzYmZGbIzYxMNAzAMzmZY2MAkxYBAzMgxMzMmNmZbZAmBDA" },
    { site = "Icy Veins", label = "Archon Raid - Entombed Sentinels", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDzAAAAAAAAAAAAMmZxMGbzMmZ2mBzw2MzYmZGbIzYxMNAzAMzmZY2MAkxYBAzMgxMzMmNmZbZAmBDA" },
    { site = "Icy Veins", label = "Archon Raid - Lost Explorers", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDPAAAAAAAAAAAAghZxMmZbmxMz2MGzw2MzYmZGbIzYxMNAzAMzmZ0sZAIjxCAmZMYMzMjZjZ2WGgZwA" },
    { site = "Icy Veins", label = "Archon Raid - Ulatek (Heroic)", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZZmxMz2MGzw2MzYmZGbIzYxMNAzAMziZY2MAkxYBAzMIjZmZMbMz2yAMTMA" },
    { site = "Icy Veins", label = "Archon Raid - Ulatek (Mythic)", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDPAAAAAAAAAAAAghZxMmZZmxMz2MGzw2MzYmZGbIzYxMNAzAMziZY2MAkxYBAzMGZMzMjZjZ2WGgZiB" },
    { site = "Icy Veins", label = "Archon AoE - No 4pc Season 2", string = "CIQAR03Gt7xPmcDNOjs2Zlb3yOMjZGAAAAAAAAAAAghZxMGbzMmZWmZYmx2MGzMzYDZGLmpBYGgZ2MjmNDAZMWAwMAjZmZMbjZ2WGgZwA" },
    { site = "Icy Veins", label = "Voidweaver Raid - No 4pc Season 2", string = "CIQAR03Gt7xPmcDNOjs2Zlb3yOMjZGAAAAAAAAAAAgxMMjx2MDzsNzwMsNzMmZmxGyMWMTDwMzMAQAmtZbJY2YAmBYMzMjZbMDmZwMYA" },
    { site = "Icy Veins", label = "Voidweaver Raid - Sszorak", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAAegZxMmZbmBz2MzYG2mZGzMzYDZGLmpBYmZGAIAz2stAmNGAYwYmZGz2YGMzgZwA" },
    { site = "Icy Veins", label = "Voidweaver Raid - Entombed Sentinels", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAgxDMLmxYbmhZ2mZYG2mZGzMzYDZGLmpBYmZGAIAz2stAmNGAYwYmZGz2YGMzgZwA" },
    { site = "Icy Veins", label = "Voidweaver Raid - Lost Explorers", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMjZMAAAAAAAAAAAAYMLzMGbzMmZ2mZGzw2MzYmZGbIzYxMNAzMzAABY2mtFwsxAADGzMzY2GzgZGMDGA" },
    { site = "Icy Veins", label = "Voidweaver AoE - No 4pc Season 2", string = "CIQAR03Gt7xPmcDNOjs2Zlb3yOMjZGAAAAAAAAAAAghZxMGbzMmZWmZYmx2MGzMzYDZGLmpBYmZGAIAz2stEMbMAwgxMzMmtxMYmBzgB" },
    { site = "Wowhead", label = "Archon: Single Target", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDzAAAAAAAAAAAAwMLmxMbzMGz2MGzw2MzYmZGbIzYxMNAzAMzmZY2MAkxYBAzMIjZmZMbMz2yAMTMA" },
    { site = "Wowhead", label = "Archon: Raid Cleave", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMz2MGzw2MzYmZGbIzYxMNAzAMzmZY2MAkxYBAzMIjZmZMbMz2yAMTMA" },
    { site = "Wowhead", label = "Archon: Mythic+", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMzyMGD2mZGzMzYDZGLbz0AMDwMbmhZzAQGjFAMzgMmZmxsxMbLDwMxA" },
    { site = "Wowhead", label = "Voidweaver: Single Target", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAAegZxMmZbmBz2MzYG2mZGzMzYDZGLmpBYmZGAIAz2stAmNGAYkxMzMmtxMYmBzEDA" },
    { site = "Wowhead", label = "Voidweaver: Raid Cleave", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAAMLmxMbzMMz2MzYG2mZGzMzYDZGLmpBYmZGAIAz2stAmNGAYkxMzMmtxMYmBzEDA" },
    { site = "Wowhead", label = "Voidweaver: Mythic+", string = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMzyMzYG2mZGzMzYDZGLmpBYmZGAIAz2stAmNGAYkxMzMmNmBzMYmYA" },
  },
})

-- DEATHKNIGHT 250 (blood-death-knight)
ns.GuideStore:RegisterSiteLoadouts(250, {
  source = "Icy Veins Blood Death Knight talent guide, updated Aug 10, 2026 - 7:20 PM; Wowhead Blood Death Knight talent guide, updated 2026/08/20",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Blood Single Target - San'layn", string = "CoPAAAAAAAAAAAAAAAAAAAAAAwYWmZGmxMzMMLzMz0MLGzMzMGAAAAwMzMzMzMDzYMDAMzMzAAAYgBmxiGLLAWGwGgZMDAAYmBwA" },
    { site = "Icy Veins", label = "Blood Mythic+ - San'layn", string = "CoPAAAAAAAAAAAAAAAAAAAAAAwMzyMzwMmZmhZZmZmmZxYmxMGAAAAwMmZmZmZYGjBAjZmZGAAADMwMW0YZBwyA2AMjZAAAzMwwA" },
    { site = "Icy Veins", label = "Blood Delves - Deathbringer", string = "CoPAAAAAAAAAAAAAAAAAAAAAAwMzyMzwMmZmhZZmZmmZxYmZmxAAAAAmxMzMzMDzYMAYMzMzAAAMmtBGwCYbYCMsAYGzAAwMDAMA" },
    { site = "Icy Veins", label = "Blood - Defensive San'layn", string = "CoPAAAAAAAAAAAAAAAAAAAAAAwMzyMzwMmZmhZZmZmmZxYmxMGAAAAwMmZmZmZ8AzYAAzMzMzAAAYgBmxiGLLAWGwGgZYAAAzMwwA" },
    { site = "Icy Veins", label = "Blood - Defensive Deathbringer", string = "CoPAAAAAAAAAAAAAAAAAAAAAAwMzyMzwMmZmhZZmZmmZxYmZmxAAAAAmxMzMzMjHYGDAYmZmZGAAgxsNwAWAbDTghFAzwAAwMDAMA" },
    { site = "Wowhead", label = "Deathbringer: Raid", string = "CoPAAAAAAAAAAAAAAAAAAAAAAwYWGzMmxMjhZZmZmmZxYmxMmBAAAAmZmZmZmZYGjZAYMzMzAAAMmtBGwSwywEYYBwMMAAMzAYYA" },
    { site = "Wowhead", label = "Deathbringer: Mythic+", string = "CoPAAAAAAAAAAAAAAAAAAAAAAwMzyMzMmxMzMMLzMz0MLGjxMGAAAAwMmZmZmZYGDAYmZmZGAAgxsNwAWCWGmADLAmxMAAMzAYYA" },
    { site = "Wowhead", label = "Deathbringer: Delves", string = "CoPAAAAAAAAAAAAAAAAAAAAAAwYWmZmxMmZmhZZmZmmZxYmxMGAAAAwMzMzMzMDzYMAYMzMzAAAMmtBGwSwywEYYBghZAAMzAMYA" },
    { site = "Wowhead", label = "San'layn: Raid", string = "CoPAAAAAAAAAAAAAAAAAAAAAAwYWmZmxMmZmhZZmZmmZxYMmxAAAAAmZmZmZmZYGjZAYMzMzAAAYgBmxiGLLgsMgNAzwAAAmZghB" },
    { site = "Wowhead", label = "San'layn: Mythic+", string = "CoPAAAAAAAAAAAAAAAAAAAAAAwYWmZmxMmZmhZZmZmmZxYMmxAAAAAmxMzMzMDzYMAYMzMzAAAYgBmxiGLLgsMgNAzYmBAAmZghB" },
    { site = "Wowhead", label = "San'layn: Delves", string = "CoPAAAAAAAAAAAAAAAAAAAAAAwYWmZmxMmZmhZZmZmmZxYMmxAAAAAmxMzMzMDzYMAYMzMzAAAYgBmxiGLLgsMgNAzYmBAAmZwgB" },
  },
})

-- DEATHKNIGHT 251 (frost-death-knight)
ns.GuideStore:RegisterSiteLoadouts(251, {
  source = "Icy Veins Frost Death Knight talent guide, updated Aug 10, 2026 - 7:20 PM; Wowhead Frost Death Knight talent guide, updated 2026/08/12",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Frost Single Target", string = "CsPAAAAAAAAAAAAAAAAAAAAAAMDwMjZmZGDz2MzMzMLmZmMjxYYmxgZMzMzMzMDAAAAAAAAAgNzihBGY2YohNMzYmZgBgBgZGgB" },
    { site = "Icy Veins", label = "Frost Mythic+/Delves", string = "CsPAAAAAAAAAAAAAAAAAAAAAAMDYmZMzMzYY2mZmZmZxMjMjxYYMGMzMzMzMzMDAAAAAAAAAjZbgBsAWGmAjFMzYmZgBghZGAgB" },
    { site = "Wowhead", label = "Deathbringer: Raid", string = "CsPAAAAAAAAAAAAAAAAAAAAAAMAmZMjZAz2MzMzMLzMjMjxYYmxgZmZmZmZmZAAAAAAAAAYMbDMgFwywEyYBzMmZGYAYYmBYmBD" },
    { site = "Wowhead", label = "Deathbringer: Mythic+", string = "CsPAAAAAAAAAAAAAAAAAAAAAAMAzMMjZAz2MzMzMLzMjMjxYYmxgZmZmZmZmZAAAAAAAAAYMbDMgFwywEyYBzMmZGYAYYmBYmBD" },
    { site = "Wowhead", label = "Deathbringer: Delves", string = "CsPAAAAAAAAAAAAAAAAAAAAAAMAzMMzMDY2MzMzMLzMjMjxYYmxgZmZmZmZmZAAAAAAAAAYMbDMgFwywEyYBzMmZGYAYYmBYmBD" },
    { site = "Wowhead", label = "Rider of the Apocalypse: Raid", string = "CsPAAAAAAAAAAAAAAAAAAAAAAMDwMjZMDY2mZmZmZZmZkZMGDzMGMjZmZmZmZAAAAAAAAAAsZWMMwAzmGaYDzMmZGYAYAYmZmBD" },
    { site = "Wowhead", label = "Rider of the Apocalypse: Mythic+", string = "CsPAAAAAAAAAAAAAAAAAAAAAAMAmhZMDY2mZmZmZZmZ0MjxYYmxgZmZmZmZmZAAAAAAAAAAsZWMMwAzmGaYDzMmZGYAYAYmZmBD" },
    { site = "Wowhead", label = "Rider of the Apocalypse: Delves", string = "CsPAAAAAAAAAAAAAAAAAAAAAAYAzMMjZMDzmZmZmZxMjmZMGmZGGPwMmZmZmZmZAAAAAAAAAAsZ2MMwAzmGaYDzMzMzAAYAYmZGYA" },
  },
})

-- DEATHKNIGHT 252 (unholy-death-knight)
ns.GuideStore:RegisterSiteLoadouts(252, {
  source = "Icy Veins Unholy Death Knight talent guide, updated Aug 24, 2026 - 7:20 PM; Wowhead Unholy Death Knight talent guide, updated 2026/08/12",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Unholy Single-Target", string = "CwPAAAAAAAAAAAAAAAAAAAAAAAwMjZMzYY2mZmZa2MzMjZAAAAAAAAg5BGGDAWmhZ2MzYmZMwAzYRjlFAbD2AwMAmZmZGzgZGMjxA" },
    { site = "Icy Veins", label = "Unholy Mythic+/Delves", string = "CwPAAAAAAAAAAAAAAAAAAAAAAAYmhZMzMDz2MzMTzmZGjZAAAAAAAAg5BGDDAWmhZ2MzYMjBGYGLassAYbwGGwMAmZmZGzgZGMjxA" },
    { site = "Wowhead", label = "Rider of the Apocalypse: Rider ST", string = "CwPAAAAAAAAAAAAAAAAAAAAAAAwMjZMDDz2MzMTzmZmZMjBAAAAAAAgZGmZAwyMmZ2mZGzMDYzsYYIDMbM0YBAzAAzMjZAmZmxYA" },
    { site = "Wowhead", label = "Rider of the Apocalypse: Rider M+/Delves", string = "CwPAAAAAAAAAAAAAAAAAAAAAAAYmhZMDDz2MzMTzmxMzMjBAAAAAAAgZGzYAwyMmZ2MzYMDYzsZYIDMbM0YBDYGAGzMjZAmZmxYA" },
    { site = "Wowhead", label = "Rider of the Apocalypse: Open World", string = "CwPAAAAAAAAAAAAAAAAAAAAAAAwMjZMDDz2MzMTzmZmZMjBAAAAAAAgZGzYAw2MmZ2mZGjZAbmNDDZgZhhGLYAzAAzMjZAmZmxYA" },
    { site = "Wowhead", label = "San'layn: San ST", string = "CwPAAAAAAAAAAAAAAAAAAAAAAAwMjZMDDz2MzMTjZmxYGDAAAAAAAAzDMMGAsMDzsZmxMzYgBmxiGLbA2mYDAzAYmZmZMDmZwMzYA" },
    { site = "Wowhead", label = "San'layn: San AoE", string = "CwPAAAAAAAAAAAAAAAAAAAAAAAwMjZMDDz2MzMTzmZmZMjBAAAAAAAg5BGDDAWmhZ2MzYMjBGYGbassAYZiNMgZAMzMzMmBzMYGjB" },
  },
})

-- SHAMAN 262 (elemental-shaman)
ns.GuideStore:RegisterSiteLoadouts(262, {
  source = "Icy Veins Elemental Shaman talent guide, updated Aug 10, 2026 - 11:10 PM; Wowhead Elemental Shaman talent guide, updated 2026/08/21",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Elemental Single Target - Farseer", string = "CYQAAAAAAAAAAAAAAAAAAAAAAAAAAAzMbLzMmZmZZZZMMjBAAAAsYmNYADY2YCMLAwsNzMjZ2WmJMzsxyMzMjZwyMWMzwMLDAYAgZGDDD" },
    { site = "Icy Veins", label = "Elemental Mythic+ - Farseer", string = "CYQAAAAAAAAAAAAAAAAAAAAAAAAAAAzMbLzMGjZZZZMmhBAAAAsYmNYADY2YCMLAwsNzMjx2iJMzsNWmZmZMjFLzMmZGzMLAADAMzYYYA" },
    { site = "Icy Veins", label = "Elemental Delves - Farseer", string = "CYQAAAAAAAAAAAAAAAAAAAAAAAAAAAzMbLzMGjZZZZMmhBAAAAsYmNYADY2YCMLAwsNzMjZ2WmJMzYsYmZGzYxyMjZmxMzCAwAAzMGGGA" },
    { site = "Wowhead", label = "Farseer: Raid", string = "CYQAAAAAAAAAAAAAAAAAAAAAAAAAAAzMbLzMmZmZZbZMMjBAAAAsYmNYADY2YCZWAgZZmZGjtFTYmZZsMzMzYYZWmxiZGmZZAADAMzYYYA" },
    { site = "Wowhead", label = "Farseer: Mythic+", string = "CYQAAAAAAAAAAAAAAAAAAAAAAAAAAAzMbLzMGjZZZZMmhBAAAAsYmNYADY2YCZWAgZZmZGjtFTbMzYsMzMzYYZWMWmZGzMLAAzAgZGDDD" },
    { site = "Wowhead", label = "Farseer: Delves", string = "CYQAAAAAAAAAAAAAAAAAAAAAAAAAAAzMLLzMmZmZbZZMmxMDAAAAsZmNYADY2YCZWAgZZmZGjtFTYmxYZmZmZmxiFjFMmZWAAGAYmxwwA" },
    { site = "Wowhead", label = "Stormbringer: Mythic+", string = "CYQAAAAAAAAAAAAAAAAAAAAAAAAAAAzMLLzMzMzMbbLDmxMDAAAAA2MjhNYBmRDN2AgZZmZGjtFTYmxYZmZmZmxiFjFjhZWAAGAzMwwwA" },
  },
})

-- SHAMAN 263 (enhancement-shaman)
ns.GuideStore:RegisterSiteLoadouts(263, {
  source = "Icy Veins Enhancement Shaman talent guide, updated Aug 23, 2026 - 7:20 PM; Wowhead Enhancement Shaman talent guide, updated 2026/08/22",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Raid / Single Target - Stormbringer", string = "CcQAAAAAAAAAAAAAAAAAAAAAAMzMzgZmZmZmhZmZAAAAAAAAA2AsZGDbwCMDDNYBgZZGzMjllZgZmNWmZmZYYMDAwMMmZMzEYmBDGDA" },
    { site = "Icy Veins", label = "AoE / Mythic+ - Stormbringer", string = "CcQAAAAAAAAAAAAAAAAAAAAAAMzMzgZmZmZmhZmZAAAAAAAAAsBYzMG2gFYGGawCAzyMmxYZxYjZmtxyMzMzYswMAAzwYmhRgZGMYMA" },
    { site = "Icy Veins", label = "Delves - Totemic", string = "CcQAAAAAAAAAAAAAAAAAAAAAAMzMjZmZmZmZmZmZGzAAAAAAAAAALwGMjFN2GAzA2AYWmxMGLLzAzMGLmZmZMWYGAADMGzMxMDAMGA" },
    { site = "Wowhead", label = "Stormbringer: Raid", string = "CcQAAAAAAAAAAAAAAAAAAAAAAMzMzgZmZmZmhZmZAAAAAAAAA2AsZGDLkFYGGawCAzyMmZGLLzAzMbsMzMzwwYGAgZYMzYmJwMDGMGA" },
    { site = "Wowhead", label = "Stormbringer: Cleave", string = "CcQAAAAAAAAAAAAAAAAAAAAAAMzMzgZmZmZmhZmZAAAAAAAAA2AsZGDbkFYGGawCAzyMmZGLLzAzMbsMzMzwwYGAgZYMzYmJwMDGMGA" },
    { site = "Wowhead", label = "Stormbringer: Mythic+", string = "CcQAAAAAAAAAAAAAAAAAAAAAAMzMzgZmZmZmhZmZAAAAAAAAA2AsZGDbkFYGGawCAzyMmxYZxYjZmtxyMzMzgFmBAYGGzMMTgZGMYMA" },
    { site = "Wowhead", label = "Stormbringer: Delves", string = "CcQAAAAAAAAAAAAAAAAAAAAAAMzMzgZmZmZmhZmZAAAAAAAAA2AsZGDbkNYGGawCAzyMmxYZZGYmxYxMzMjxCzAAMDjZGzMBmZwgxA" },
    { site = "Wowhead", label = "Totemic: Raid", string = "CcQAAAAAAAAAAAAAAAAAAAAAAMzMzMzMzMzMzMzMzYGAAAAAAAAAsAbwMW0YbAMTwGAzyMmZGLLzAzMbsMzMzwwYGAADwYmJmZAgxA" },
    { site = "Wowhead", label = "Totemic: Cleave", string = "CcQAAAAAAAAAAAAAAAAAAAAAAMzMzMzMzMzMzMzMzYGAAAAAAAAAsAbwMW0YbAMTwGAzyMmZGLLzAzMbsMzMzwwYGAAgxYmJmZAgxA" },
    { site = "Wowhead", label = "Totemic: Mythic+", string = "CcQAAAAAAAAAAAAAAAAAAAAAAMzMzMjZmZmZmZmZGzAAAAAAAAAgFYDmxiGbDgZC2AYWmxMGLLGbMzsNWm5BmZGsMmBAAYMmRMzAMYMA" },
    { site = "Wowhead", label = "Totemic: Delves", string = "CcQAAAAAAAAAAAAAAAAAAAAAAMzMjZmZmZmZmZmZGzAAAAAAAAAgFYDmxiGbDgZC2AYWmxMGLLzAzMGLmZmZMWYGAAgxYmJmZAGMGA" },
  },
})

-- SHAMAN 264 (restoration-shaman)
ns.GuideStore:RegisterSiteLoadouts(264, {
  source = "Icy Veins Restoration Shaman talent guide, updated Aug 10, 2026 - 7:20 PM; Wowhead Restoration Shaman talent guide, updated 2026/08/27",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Restoration Dungeons - Totemic", string = "CgQAAAAAAAAAAAAAAAAAAAAAAAAAAgBAAAAzMzsstMmZmZmZGjZMsBbwMW0YbAMDshxMMLzMGNLLzMbmxsxixMjhlZZAAAAzMYmBgxgZA" },
    { site = "Icy Veins", label = "Restoration Raid - Totemic", string = "CgQAAAAAAAAAAAAAAAAAAAAAAAAAAgBAAAAzMzsssNjZGjZGzMYsBbwMW0YbAMDsZGmBbjZmpZbZmhZMbsMzMzYwsMAAAwMzgZGAYwM" },
    { site = "Icy Veins", label = "Restoration Delves - Farseer", string = "CgQAAAAAAAAAAAAAAAAAAAAAAAAAAgBAAAAzMzsssNzMzMzMzYmhxiZWgBMgZhJwYhBY2mZMa2WmZ2MzMLsYmZGDmlBAAAYGAMzgZwM" },
    { site = "Wowhead", label = "Farseer: Raid", string = "CgQAAAAAAAAAAAAAAAAAAAAAAAAAAgBAAAAzMzsssNjZGjZGzMMWMzGMgJY2YCMWMDzgtxYmmtlZmNzYWYxMzMmhZZAAAgZmBAzMwgZA" },
    { site = "Wowhead", label = "Farseer: Mythic+", string = "CgQAAAAAAAAAAAAAAAAAAAAAAAAAAgBAAAAzMzsssNzMzMjZGjZMWMzCMgJYWYCMWwMDmtZGjmtlZmNzYWYxYmxwysMAAAwMzAgZGYwM" },
    { site = "Wowhead", label = "Totemic: Raid", string = "CgQAAAAAAAAAAAAAAAAAAAAAAAAAAgBAAAAzMzsssNjZGjZGzMDjFYDmxiGbDIzAbmhZw2YMTz2yMzmZMLsYegZGzwsMAAAwMzgZGAYwM" },
    { site = "Wowhead", label = "Totemic: Mythic+", string = "CgQAAAAAAAAAAAAAAAAAAAAAAAAAAgBAAAAzMzsstMzMzMjZGjZgFYDmxiGbDIzAbMzMY2mZMa2WmZ2MjZhFjZGDLzyAAAAzMDmZAgBzA" },
  },
})

-- MAGE 62 (arcane-mage)
ns.GuideStore:RegisterSiteLoadouts(62, {
  source = "Icy Veins Arcane Mage talent guide, updated Aug 12, 2026 - 7:13 AM; Wowhead Arcane Mage talent guide, updated 2026/08/31",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Arcane Raid - Sunfury", string = "C4DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMDamZGAAAGAwMz0sssMDAgNAAAzMDbWmxMLzYMzMzMsxMmZmBAYAAAGgZGwMAYYmZA" },
    { site = "Icy Veins", label = "Arcane Mythic+ - Sunfury", string = "C4DAAAAAAAAAAAAAAAAAAAAAAMzwYZmZmFMzQzMzAAAwAAmZmmlllZAAsBAwGMzMsZZGzsMjxMzMzwGzYGzAAMAAADwMDMzAghZmB" },
    { site = "Icy Veins", label = "Arcane Delves - Sunfury", string = "C4DAAAAAAAAAAAAAAAAAAAAAAMzwYZGzsYzMDNzYGAAADAYmZaWWWmBAwGAAbwMzwmlZMzyMGzMzMDbMjZMDAwAAAMAzMwMDAGmZG" },
    { site = "Wowhead", label = "Spellslinger: Raid", string = "C4DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMDamZGAAAGAAEwMzMLLzMxCAAwMzMjNLzMzsMjxYmZwCzYmZGAgBAAYmZBAMDAGmZG" },
    { site = "Wowhead", label = "Spellslinger: Mythic+", string = "C4DAAAAAAAAAAAAAAAAAAAAAAMzwYZmZmFMzQzMGAAAGAAEwMzMLLzMxCAAbDmZG2sMjZMjxMzMzwCzMzMzAAMAAAzMbAADAGmZG" },
    { site = "Wowhead", label = "Sunfury: Raid", string = "C4DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMDamZGAAAGAwMz0sssMDAEbAAAmZG2sMjZWmxYmZmZYhZMzMDAwAAAMAzMgZAwwMzA" },
    { site = "Wowhead", label = "Sunfury: Mythic+", string = "C4DAAAAAAAAAAAAAAAAAAAAAAMzwYZmZmFMzQzMGAAAGAwMz0sssMDAEbAAsBzMDbWmxMLzYMzMzMswMzMzMAADAAwAMzAMAYYmZA" },
  },
})

-- MAGE 63 (fire-mage)
ns.GuideStore:RegisterSiteLoadouts(63, {
  source = "Icy Veins Fire Mage talent guide, updated Aug 10, 2026 - 7:20 PM; Wowhead Fire Mage talent guide, updated 2026/08/13",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Fire Raid - Sunfury", string = "C8DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMDZmZGAAAGAwMz0sstMDAwmZmx2MzMzYDAAAAAbmZMzAAgZMmZmZMzsMAMzAMGwMMGA" },
    { site = "Icy Veins", label = "Fire Mythic+ - Sunfury", string = "C8DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzsgZGZmZGAAAAAmZmmltlZAA2MzM2mZmZGbAAAAAYzMjZGAAMjxMzMjZmlBgZGMjxAmhxA" },
    { site = "Wowhead", label = "Sunfury: Raid", string = "C8DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMzIzMzAAAwAAmZmmlttZAA2MzM2mZmZGLAAAAAYxMjZAAgZMmZmZMzsMAMzQGjBMDjB" },
    { site = "Wowhead", label = "Sunfury: Mythic+", string = "C8DAAAAAAAAAAAAAAAAAAAAAAMzwYZmZmFMzIzMzMAAAGAwMz0sstNDAwmZmx2MzMzYDAAAAALmZmZAAgZMmZmZMzsMAMzQYMgZYMA" },
    { site = "Wowhead", label = "Sunfury: Delves", string = "C8DAAAAAAAAAAAAAAAAAAAAAAMzwMLzMzsgZGZmxAAAwAAmZmmlltZAA2MzM2GzMzYBAAAAA2MzMzMAAYMDjZmZmZbAYmhwYMYGG" },
    { site = "Wowhead", label = "Frostfire: Raid", string = "C8DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMzIzMzAAAwMLzYmZZWgAAAWMzw2MzMzYBAAAAALmZMDAAMzwMzMzMzsAMzAyYMGMYMA" },
    { site = "Wowhead", label = "Frostfire: Mythic+", string = "C8DAAAAAAAAAAAAAAAAAAAAAAMzwYZmZmFMzIzMzMAAAmZZGzMLzCEAAwiZG2mZmZGbAAAAAYxMzMDAAMzwMzMzMzsAMzACjxgBjB" },
    { site = "Wowhead", label = "Frostfire: Delves", string = "C8DAAAAAAAAAAAAAAAAAAAAAAMzwYZmZmFMzIzMzAAAwMLzYmZZWgAAAWMzM2mZmZmZDAAAAALmZmZAAgZMmZmZMzsAMzAyYMgBjB" },
  },
})

-- MAGE 64 (frost-mage)
ns.GuideStore:RegisterSiteLoadouts(64, {
  source = "Icy Veins Frost Mage talent guide, updated Aug 10, 2026 - 7:20 PM; Wowhead Frost Mage talent guide, updated 2026/08/21",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Frost Single Target", string = "CAEAAAAAAAAAAAAAAAAAAAAAAYGGLzMzsMmZmYmZGjZMziZmZmZMDAAAMzMzyyMTbAAAAAAwGAbbjZmZwsNPgxMsAAAwMbAzADYGMMA" },
    { site = "Icy Veins", label = "Frost Light Cleave/Raid", string = "CAEAAAAAAAAAAAAAAAAAAAAAAYGGLzMzsMmZmYmZGzMzMziZmZMjZAAAgZmZWWmZaDAAAAAA2AYbbMzMDmthxMsAAAwMbAzADYGMMA" },
    { site = "Icy Veins", label = "Frost AoE", string = "CAEAAAAAAAAAAAAAAAAAAAAAAYGGLzMzsMmZmYmZGzMzMWMzMzMzYmlZamZZWAAAgFAAAAAAYBgttxMzMY2mxMzYbBAAAMzgZgBMDwA" },
    { site = "Wowhead", label = "Spellslinger: Raid ST", string = "CAEAAAAAAAAAAAAAAAAAAAAAAYGGLzMzsMmZmYmZGjZMziZmZmZMDAAAMzMzyyMTbAAAAAAwGAbLjZmZgtZMzMsAAAwMbAzEGwADD" },
    { site = "Wowhead", label = "Spellslinger: Raid Cleave", string = "CAEAAAAAAAAAAAAAAAAAAAAAAYGGLzMzsMmZmYmZGzMzMziZmZMjZAAAgZmZWWmZaDAAAAAA2AYbZMzMDmthxMsAAAwMbAzEGwMYYA" },
    { site = "Wowhead", label = "Spellslinger: Mythic+", string = "CAEAAAAAAAAAAAAAAAAAAAAAAMzwYZmZmFMzEzMmZmZmZWMzMjZMDAAAMzMzyyMTbAAwCAAAYBgtlxMzMY2GGzwCAAAzsBMTGDYGMMA" },
    { site = "Wowhead", label = "Frostfire: Raid ST", string = "CAEAAAAAAAAAAAAAAAAAAAAAAYGGLzMzsMmZmYmZGjZMziZmZmxMzsMTzMLzCAAAaBAAAAAA2AYbZMzMDsNjxM2WAAAAzMYmwAGYYA" },
    { site = "Wowhead", label = "Frostfire: Raid Cleave", string = "CAEAAAAAAAAAAAAAAAAAAAAAAYGGLzMzsMmZmYmxYmZmZWMzMzMzMzsMTzMbzCAAAaBAAAAAAAw2yYmZGMbzYmZstAAAAmZwMZMgBwA" },
    { site = "Wowhead", label = "Frostfire: Mythic+", string = "CAEAAAAAAAAAAAAAAAAAAAAAAMzwYZmZmFMzEzMmZmZmZWMzMzMzMzsMTzMbzCAAAaBAAWAAAAAYbZMzMDmtZMzM2WAAAAzMYmMGwAYA" },
  },
})

-- WARLOCK 265 (affliction-warlock)
ns.GuideStore:RegisterSiteLoadouts(265, {
  source = "Icy Veins Affliction Warlock talent guide, updated Aug 31, 2026 - 7:41 PM; Wowhead Affliction Warlock talent guide, updated 2026/08/12",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Affliction Single-Target - Soul Harvester", string = "CkQAAAAAAAAAAAAAAAAAAAAAAwMzMzoZhhZmZmlBAAYmZZ2mZmlxAAjllBGwEMDbBG2GAAAmBAAwMDzMjBzwMzMzMGMzMzAAmBG" },
    { site = "Icy Veins", label = "Affliction AoE - Soul Harvester", string = "CkQAAAAAAAAAAAAAAAAAAAAAAwMjZGNLmxyMzYWGAAwMzsMLzMzyYAgx2yADYCmhtADbDAAAzAAAYmZMzwsxwYmZmZYYmZmBAMDMA" },
    { site = "Icy Veins", label = "Affliction Delves - Soul Harvester", string = "CkQAAAAAAAAAAAAAAAAAAAAAAwMjZGNLmxyMzYWGAAwMzsMLzMzyYAgxyyADYAzwWghtBAAgZAAAMzMmZY2GjZwMzMMMzMzAAmBG" },
    { site = "Wowhead", label = "Hellcaller: Raid", string = "CkQAAAAAAAAAAAAAAAAAAAAAAwMzMzoZhhZmZmlBAAYmZZWmZmlxAAWgBmFjGzAysAWGAAAmBAAmZAzMjhZGmZMzMGMzMzAAmBG" },
    { site = "Wowhead", label = "Hellcaller: Raid Cleave", string = "CkQAAAAAAAAAAAAAAAAAAAAAAwMmZGNbM2mZGzyAAAmZmlZxMzyYAALwAziRjZAZ2ALDAAAzAAAzMYMjZmtxwYmZmZYYmZGAgZgB" },
    { site = "Wowhead", label = "Hellcaller: Mythic+", string = "CkQAAAAAAAAAAAAAAAAAAAAAAwMegZGNbzM2mZGz2AAAmZmlZxMzyYAALwAziRjZAZ2ALDAAAzAAAzMYMjxsNGzYmZmZYYmZGAgBMA" },
    { site = "Wowhead", label = "Soul Harvester: Raid Cleave", string = "CkQAAAAAAAAAAAAAAAAAAAAAAwMmZGNbM2mZGzyAAAmZmlZxMzyYAgx2yADYCmhtADbDAAAzAAAYmZMjZmtxwYmZmZYYmZGAgZgB" },
    { site = "Wowhead", label = "Soul Harvester: Mythic+", string = "CkQAAAAAAAAAAAAAAAAAAAAAAwMjZGNbmx2MzYWGAAwMzsMLmZ2GDAM2WGYATwMsFYYbAAAYGAAAzMjZMzsNGzYMzMzYYmZGAgBMA" },
  },
})

-- WARLOCK 266 (demonology-warlock)
ns.GuideStore:RegisterSiteLoadouts(266, {
  source = "Icy Veins Demonology Warlock talent guide, updated Aug 11, 2026 - 7:59 PM; Wowhead Demonology Warlock talent guide, updated 2026/08/12",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Demonology Single-Target - Soul Harvester", string = "CoQAAAAAAAAAAAAAAAAAAAAAAwMzMzoZjhZmxsMAAAAAAAjtlBGwAmhtQGbmhZ2mlZmZMDAYMzMzAMzMmxMDAAwMzMzMjZYZAYA" },
    { site = "Icy Veins", label = "Demonology AoE - Diabolist", string = "CoQAAAAAAAAAAAAAAAAAAAAAAwMjZGNLmxmZGzyAAAAAAAAGzYYBGYb0CNsYMzYZ2mZmxMAwMjZGzMDwYmxMbAAgxMzMzww2MGwA" },
    { site = "Icy Veins", label = "Demonology Delves - Soul Harvester", string = "CoQAAAAAAAAAAAAAAAAAAAAAAwMjZGNLmxiZGzyAAAAAAAMWWGYADYG2CM2MmZsMmxMzMAwMzMGDwMzYmxMbAAgxMzMzYw2MDwA" },
    { site = "Wowhead", label = "Diabolist: Raid", string = "CoQAAAAAAAAAAAAAAAAAAAAAAYmZMzoZjhZmxsMAAAAAAAgxMGWgB2GtQDLGjxysMzMjZAgZGzMzMzAMzMmZAAAGzMzMDDLzYAD" },
    { site = "Wowhead", label = "Diabolist: Raid Cleave", string = "CoQAAAAAAAAAAAAAAAAAAAAAAYmhZGNbmx2MzYWGAAAAAAAwYGDLwAbj2ohFjZGLz2MzMmBAmZMmZmZAmZGmZDAAMmZmxwwyMGwA" },
    { site = "Wowhead", label = "Soul Harvester: Raid", string = "CoQAAAAAAAAAAAAAAAAAAAAAAYmZMzoZjhZmxsMAAAAAAAjllBGwAmhlQGbmhZ2mlZmZMDAYMzMzAMzMzMmZAAAmZmZmZMDLDAD" },
    { site = "Wowhead", label = "Soul Harvester: Raid Cleave", string = "CoQAAAAAAAAAAAAAAAAAAAAAAYmhZGNbmx2MzYWGAAAAAAgxyyADYAzwSIjNDGLz2MzMmBAmxMzMDwMzMzwMbAAgZmZmxMD2mBwA" },
    { site = "Wowhead", label = "Soul Harvester: Mythic+", string = "CoQAAAAAAAAAAAAAAAAAAAAAAYmhZGNbmx2MzYWGAAAAAAgxyyADYAzwSIjNDGLjZmZmZAgZMzYGgZmZmhZ2AAAzMzMjZGsNzAMA" },
  },
})

-- WARLOCK 267 (destruction-warlock)
ns.GuideStore:RegisterSiteLoadouts(267, {
  source = "Icy Veins Destruction Warlock talent guide, updated Aug 21, 2026 - 7:59 PM; Wowhead Destruction Warlock talent guide, updated 2026/08/29",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Destruction Single-Target - Hellcaller", string = "CsQAAAAAAAAAAAAAAAAAAAAAAwMmZGNLMzmZmZWmFzMzsYMWMDAAmZGzMziNYgZxoxMAmtYjBAAGDM2AAmZwYGzYDAAwMzMAAMGG" },
    { site = "Icy Veins", label = "Destruction AoE - Diabolist", string = "CsQAAAAAAAAAAAAAAAAAAAAAAwMjZGNLmxmZGzysNzYmFzYZZMAAYGjZmZBMmxwCMw2wCNWYAAgxMMsBgZGgxMjZ2AAAMzMzAAYMM" },
    { site = "Icy Veins", label = "Destruction Delves - Hellcaller", string = "CsQAAAAAAAAAAAAAAAAAAAAAAwMjZGNLmxmZGzysZGzsYYZZmBAAzMjZmZxCMwsY0YGAzG2YAAgxMAAAzMYMzMmNAAAzMzMAAMDD" },
    { site = "Wowhead", label = "Diabolist: Raid", string = "CsQAAAAAAAAAAAAAAAAAAAAAAwMzMzoZjhZmZmlZzMzMLGjFzAAgZmxMzsAGzYYhMw2wGNWYAAgxAjNAMzAYmxYAAAYmZmBAwYYA" },
    { site = "Wowhead", label = "Diabolist: Mythic+", string = "CsQAAAAAAAAAAAAAAAAAAAAAAwMjZGNbmZ2mZGzysZmZmFzMLLzDMAAYGjZmZBMmxwCZgthFaswAAAjZYAAmZAGzYMbAAAmZmBAAGG" },
    { site = "Wowhead", label = "Diabolist: Cleave", string = "CsQAAAAAAAAAAAAAAAAAAAAAAwMzMzoZjhZmxsMLzMzMLGz2iZAAwMGzMzCYMjhFyAbDb0YhBAAGDwCAmZAmZGjZDAAwMzMAAMGG" },
    { site = "Wowhead", label = "Hellcaller: Mythic+", string = "CsQAAAAAAAAAAAAAAAAAAAAAAwMjZGNLmxiZGzysNzMjFzYZZmBAAzgZmZxCMwsY0YGAzWsxAAAjZYAAwMDGzMmZDAAwMzMDAAzwA" },
    { site = "Wowhead", label = "Hellcaller: Cleave", string = "CsQAAAAAAAAAAAAAAAAAAAAAAwMmZGNLMzmZmZWmlZmZmFjZbxDMAAYGjZmZxGMwsY0YGAzWsxAAAjBGbAAzMYMjZsBAAYmZGAAGDD" },
  },
})

-- MONK 268 (brewmaster-monk)
ns.GuideStore:RegisterSiteLoadouts(268, {
  source = "Icy Veins Brewmaster Monk talent guide, updated Aug 10, 2026 - 7:20 PM; Wowhead Brewmaster Monk talent guide, updated 2026/08/13",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Brewmaster Raiding (Defensive) - Master of Harmony", string = "CwQAAAAAAAAAAAAAAAAAAAAAAAAAAgZbzYGPwYWM2mxMDAAAAAAALLYEmBmhxmZMmZmZMzywMmZZYZzy2sNMLAAwysMtMbzsMAAAAzwGYmBMNGAAwA" },
    { site = "Icy Veins", label = "Brewmaster Mythic+ (Standard) - Shado Pan", string = "CwQAAAAAAAAAAAAAAAAAAAAAAAAAAwMLbGDzwyM2MmZMAAAAAAALLgYmBmhBzgZmZGzsNMjZWGW2stNbzYWAAgNAAAwsNLNzMzGDbAMzw0YADAYA" },
    { site = "Icy Veins", label = "Brewmaster Delves/Open World - Master of Harmony", string = "CwQAAAAAAAAAAAAAAAAAAAAAAAAAAgZZzYGzwyM2MmZMAAAAAAALLgYmBmhBzgZmZGzsNMjZWGW2ssNbzYWAAglZZaZ2mZZAAAAMsBmZATjBMAgB" },
    { site = "Wowhead", label = "Shado-pan: Standard Raid", string = "CwQAAAAAAAAAAAAAAAAAAAAAAAAAAgZbzYGPwYWM2mxMDAAAAAAALLYEmBmhxmZMmZmZMzywMmZZYZzy2sNMLAAwGCAAwsNLNzMziZYDgZGmGDAAYA" },
    { site = "Wowhead", label = "Shado-pan: Mythic+", string = "CwQAAAAAAAAAAAAAAAAAAAAAAAAAAwMLbGDzwyM2MmZMAAAAAAALLgYmBmhBzgZmZGzsNMjZWGW2stNbzYWAAgNEAAgZbWamZmNG2AYmhpxAGAwA" },
    { site = "Wowhead", label = "Shado-pan: Delves", string = "CwQAAAAAAAAAAAAAAAAAAAAAAAAAAgZZzYGzwyM2MmZMAAAAAAALLgYmBmhBzgZmZGzsNMjZWGW2ssNbzYWAAgNEAAgZbWamZmFG2AYmhpxAGAwA" },
    { site = "Wowhead", label = "Master of Harmony: Standard Raid", string = "CwQAAAAAAAAAAAAAAAAAAAAAAAAAAgZbzYGPwYWM2mxMDAAAAAAALLYEmBmhxmZMmZmZMzywMmZZYZzy2sNMLAAwysMtMbzsMAAQAmhNwMDYaMAAgB" },
    { site = "Wowhead", label = "Master of Harmony: Mythic+", string = "CwQAAAAAAAAAAAAAAAAAAAAAAAAAAgZZzYGzwyM2MmZMAAAAAAALLgYmBmhBzgZmZGzsNMjZWGW2stNbzYWAAglZZaZ2mZZAAgAYYDMzAmGDYAAD" },
    { site = "Wowhead", label = "Master of Harmony: Delves", string = "CwQAAAAAAAAAAAAAAAAAAAAAAAAAAgZZzYGzwyM2MmZMAAAAAAALLgYmBmhBzgZmZGzsNMjZWGW2ssNbzYWAAglZZaZ2mZZAAgAYYDMzAmGDYAAD" },
  },
})

-- MONK 270 (mistweaver-monk)
ns.GuideStore:RegisterSiteLoadouts(270, {
  source = "Icy Veins Mistweaver Monk talent guide, updated Aug 18, 2026 - 6:30 PM; Wowhead Mistweaver Monk talent guide, updated 2026/08/28",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Mistweaver Raid - Conduit of the Celestials", string = "C4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAghx2YZYzixMzyyM2wYGmZZbbmxCzoZMDYwAsMzMzwsBDWmJAAAAAAYxyMLzyMDAAMgBYGwYYsMZMDA" },
    { site = "Icy Veins", label = "Mistweaver Mythic+ - Conduit of the Celestials", string = "C4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAghxyMLjZx2MmZsZstsNjZ2Mz22yMjFmRzYGwgBDmZmZY2GmhZ5BmAAAAAAgFLzsMLzMAAwAAMDYMwiMmBA" },
    { site = "Icy Veins", label = "Mistweaver Delves - Conduit of the Celestials", string = "C4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAghxyMLjZx2MzMz2G2sNjZ2Mz22yMjFmZaGzYBDGglZmZGmNYwyMBAAAAAALWmZZWmZAAAYAYGwAsMZMDA" },
    { site = "Wowhead", label = "Conduit of the Celestials: Raid", string = "C4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAghx2YZYzixMzyyM2wYGmZZZbmxCzoZMDYwgxYmZmhZbMGsYCAAAAgAsYZmlZbmBAAGwAMDYMMWkxMA" },
    { site = "Wowhead", label = "Conduit of the Celestials: Mythic+", string = "C4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAghxyMLjZx2MmZsZsZZGzs9AzstsMzYhhmxMgBDYWmZmZY2wMMLzEAAAAABYx2Mbz2MDAAMAAzAGDsIjZA" },
    { site = "Wowhead", label = "Conduit of the Celestials: Delves", string = "C4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMWmZZML2mxMjNDYMzmZ222mZswQzYGLYwAGzMzMMbDzwsMTAAAAAEgFbzsNbzMAAAwAMDYMMDZMDA" },
    { site = "Wowhead", label = "Master of Harmony: Raid", string = "C4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAghx2YZYzixMzyyM2wYGmZZZbmxCzoZMDYwgxYmZmhZbMGsYCAAAAMLTLz2MLzGAAAADYmZAgxwYRGA" },
    { site = "Wowhead", label = "Master of Harmony: Mythic+", string = "C4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAghxyMLjZx2MmZsZsZZGzs9AzstsMzYhhmxMgBDYWmZmZY2wMMLzEAAAAYWm2mtZWmNAAAAGgZGAYMwiMAA" },
    { site = "Wowhead", label = "Master of Harmony: Delves", string = "C4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMWmZZML2mxMjNDYMzmZ222mZswQzYGLYwAGzMzMMbDzwsMTAAAAgZZab2mZZ2AAAAAYmZAgxwMkBA" },
  },
})

-- MONK 269 (windwalker-monk)
ns.GuideStore:RegisterSiteLoadouts(269, {
  source = "Icy Veins Windwalker Monk talent guide, updated Aug 11, 2026 - 10:20 AM; Wowhead Windwalker Monk talent guide, updated 2026/08/13",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Windwalker Raids - Shado-Pan", string = "C0QAAAAAAAAAAAAAAAAAAAAAAMzYM2GmhlZGbzAAAAAAAAAAAAsMMCzwwAmZGmZmZY2GmhZZmAAWMz2MjZmZmBAwGAMLzSzMzsAgBmZAYsMAGwFA" },
    { site = "Icy Veins", label = "Windwalker Mythic+ - Conduit of the Celestials", string = "C0QAAAAAAAAAAAAAAAAAAAAAAMzYMgxYZmZ2mBAAAAAAAAAAAYZYEmhhBMjhZmZGmNMDzyMBAswsxMmZmZAAsYmlZZMBAAmZGAzAMWGDYmZ2M" },
    { site = "Wowhead", label = "Shado-pan: Raid - Single Target", string = "C0QAAAAAAAAAAAAAAAAAAAAAAMzYM2GmhlZGbzAAAAAAAAAAAAsMMCzwwAmZGmZmZY2GmhZZmAAWMz2MjZmZmBAwGAMLzSzMzsAgBmZAYsMQMgLA" },
    { site = "Wowhead", label = "Shado-pan: Raid - Cleave", string = "C0QAAAAAAAAAAAAAAAAAAAAAAMzYMYMYbmZ2mxAAAAAAAAAAAALDjwMMMgZMMzMzwsNMDzyMBAsYmtxwYmZAAsBAzys0MzMLADDMzAwYZMEDYA" },
    { site = "Wowhead", label = "Shado-pan: Mythic+", string = "C0QAAAAAAAAAAAAAAAAAAAAAAMzYAMGbzMz2MAAAAAAAAAAAALDzEmhhBMjhZmZGmNMDzyMBAsYmtZmxMzMDAgNAYWmlmZmZBgZgZGAYZMEDYA" },
    { site = "Wowhead", label = "Conduit of the Celestials: Raid - Single Target", string = "C0QAAAAAAAAAAAAAAAAAAAAAAMzYM2GmhlZmZbGAAAAAAAAAAAglhRYGGGwMzwMzMDz2wMMLzEAwiZ2mZMjZmBAwiZWmlxEEAAGAzAMWGImZmFXA" },
    { site = "Wowhead", label = "Conduit of the Celestials: Raid - Cleave", string = "C0QAAAAAAAAAAAAAAAAAAAAAAMzYMgxYZmx2MDAAAAAAAAAAAYZYEmhhBMzMMzMzwsNMDzyMBAsYmtxMGzMDAgFzsMLjJIAghBwMAjlBiZmZzA" },
    { site = "Wowhead", label = "Conduit of the Celestials: Mythic+", string = "C0QAAAAAAAAAAAAAAAAAAAAAAMzYMgxYZmZ2mBAAAAAAAAAAAYZYEmhhBMjhZmZGmNMDzyMBAswsxMmZmZAAsYmlZZMBBAMzMAmBYsMGiZmZzA" },
  },
})

-- DRUID 102 (balance-druid)
ns.GuideStore:RegisterSiteLoadouts(102, {
  source = "Icy Veins Balance Druid talent guide, updated Aug 10, 2026 - 7:20 PM; Wowhead Balance Druid talent guide, updated 2026/08/12",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Balance Druid Single-Target - Elune's", string = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNjxMD8AmFzMzMLMMMmZZGGzYhlZWmZMmZDDAGbLzMYMbDgJAAAALMzMzgNjZMmBAwMDWGA" },
    { site = "Icy Veins", label = "Balance Druid AoE - Elune's", string = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNjxMD8AmFzMzMLMMMmZZmFzMjFWmZZMmZsgBAjttZGMmtBwEAAAgFmZmZwmxMGzAAYmBGA" },
    { site = "Icy Veins", label = "Balance Druid Delves - Keeper", string = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNjxMD8AmlZmZmZDgZZmtZWmxMzGLzYMGzshBADw22YBTzMbDAAAA2MzMzMYzYGjBgZGAYA" },
    { site = "Icy Veins", label = "Keeper of the Grove Cleave Build", string = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNjxMDMmlZmZmBMDjZWmZZGzYhlZMmZmxCGAMALbjFMNzsMAAAAYjZmZGsZgxMAmZAgBA" },
    { site = "Wowhead", label = "Keeper of the Grove: Raid", string = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNjxMDMmlZmZmBMDWmZbGzYGLsMjZmZMzGGAMALbjFMNzsMCAAAwGzMzMYzAjZAMzAADA" },
    { site = "Wowhead", label = "Keeper of the Grove: Mythic+", string = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNMmZgxsMzMzMLMwDMbzsMWmxMWYZGjxMjFMAYAW2GLYamZZEAAAgNzMPwMD2MmxYGAzMAwA" },
    { site = "Wowhead", label = "Keeper of the Grove: Delves", string = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNMmZgxsMzMzMLMgZZmlx2MmxGLzYmZGmFMAYAW2GLYamZbEAAAgNmZmZwmxMGzAYmBAGA" },
    { site = "Wowhead", label = "Elune's Chosen: Raid", string = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNjxMDwsMzMzMYYGjZWmhxMWYZmlZGjZ2wAgx2yMDGz2IwEAAAgFzMzMD2MMGzAAYmBLDA" },
    { site = "Wowhead", label = "Elune's Chosen: Mythic+", string = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNMmZgxsMzMzMLMgxMLzsYmZswyMLjxMjNMAYstNzgxsNCMBAAAYhZmZGsZMjxAAwMDWGA" },
    { site = "Wowhead", label = "Elune's Chosen: Delves", string = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNMmZgxsMzMzMLMgxMLzsYMzswyMLjxMjNMAYstNzgxsNCMBAAAYhZmZGsZMjxAAwMDWGA" },
  },
})

-- DRUID 103 (feral-druid)
ns.GuideStore:RegisterSiteLoadouts(103, {
  source = "Icy Veins Feral Druid talent guide, updated Aug 10, 2026 - 7:20 PM; Wowhead Feral Druid talent guide, updated 2026/08/12",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Raid / Single Target - Wildstalker", string = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAwYMjxYmZMmtFWGbzMzYmZAAAAYLY2MMmZUzYWmZmZGjZMAAAAAAMwAAAAAAMbzs0sNzyGYmHAYxMYAAMzAgB" },
    { site = "Icy Veins", label = "Raid / Cleave - Wildstalker", string = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZMzGzMzMGz2yYZsNjZmHYmBAAAgtgZzwYmRNjZZmZmZMmxAAAAAAwADAAAAAwsNzSzyMLbgZeAgFzgBAwMDAGA" },
    { site = "Icy Veins", label = "AoE / Mythic+ - Druid of the Claw", string = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmZ2YmZmxY2MPw2YbGzMmZAAAAYLY2M8AmZUzYWMzMzsMmxAAAAAAwADAAAgmZZWmZmBAsAzMDwCDGAAAzshB" },
    { site = "Icy Veins", label = "Delves - Druid of the Claw", string = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjZYmxMzMzsZsNz2MmZegZGAAAA2CmNDPgZG1MmlxMzMLjZYAAAAAAMwAAAAoZWmlZmZAALwMzAswgBAAwMbYA" },
    { site = "Wowhead", label = "Druid of the Claw: Raid", string = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAwghxYmZmxsxDsMz2MzMmZGAAAAWCmNYMzomxswMzMGzMDAAAAAAgBAAAQzsMLzMzACsAmZAWMzwAAAYmNMA" },
    { site = "Wowhead", label = "Druid of the Claw: Mythic+", string = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmZ2YmZmxY2MPw2YbGzMmZAAAAYLY2MwMzUzYWMzMzsMmxAAAAAAwADAAAgmZZWmZmBEYBmZGgFGMAAAmZDD" },
    { site = "Wowhead", label = "Wildstalker: Raid", string = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAwYMjxYmZMmtFWGbzMzYmZAAAAYJY2gxMjaGzCzMzYMzMAAAAAAAGAAAABAz2MLNLzssBmZAWMzwAAYmBAD" },
    { site = "Wowhead", label = "Wildstalker: Mythic+", string = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmZ2YmZmxY2MPw2YbGzMmZAAAAYJY2gxMjaGzCzMzsMmZGAAAAAAADAAAgAgZbmlmlZW2AzMALMDDAgZGAMA" },
  },
})

-- DRUID 104 (guardian-druid)
ns.GuideStore:RegisterSiteLoadouts(104, {
  source = "Icy Veins Guardian Druid talent guide, updated Aug 10, 2026 - 7:20 PM; Wowhead Guardian Druid talent guide, updated 2026/08/28",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Guardian Single Target - Druid of the Claw", string = "CgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmxsMPwYMzmZZGMLLDMbwoJamZWmZmZGjZMDAAAAAYGLzAAAAgmZZWmZmBAwCmZAWMDGwmFDAmZDG" },
    { site = "Icy Veins", label = "Guardian AoE - Elunes Chosen", string = "CgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmZml5BmZMziZxwMLLDMbGGNRmZWmZmZmlxMGAAAAAgZsYAbbzMYMLDgJAAAgNMzAsYGMgNLAMzAYA" },
    { site = "Icy Veins", label = "Guardian Delves - Elunes Chosen", string = "CgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmxsMPwMjZWMLGmZZZgZzwoJyMzyMzMzsMmxAAAAAAMjlZALbzMYMLDgJAAAgNMzAsYGMgNLAMzAYA" },
    { site = "Wowhead", label = "Druid of the Claw: Raid", string = "CgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmxsMPwYMzmZZGMWGY2gRT0MzsMzMzMGzYGAAAAAwMWmBAAAgamlZZmZGAALYmBYxMYAbW2GAMzGMA" },
    { site = "Wowhead", label = "Druid of the Claw: Mythic+", string = "CgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmxsMmZMziZZGmZZZgZzwoJamZWmZmZmlxMMAAAAAgZsMDAAAA1MLzyMzMAAWwMPAwiZwA2sAAmZDG" },
    { site = "Wowhead", label = "Elune's Chosen: Raid", string = "CgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmxsYGjZ2MLGMLLDMbwoJamZWmZmZGjZMDAAAAAYGLzAW2mZwY2GATBAAA2wMDwiZwA2ssNAzMAG" },
    { site = "Wowhead", label = "Elune's Chosen: Mythic+", string = "CgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmZml5BmZMziZxwMLLDMbGGNRzMzyMzMzsMmBAAAAAgZsYAbbzMYMLDgpAAAAbYmBYxMYAbWAYmBwA" },
    { site = "Wowhead", label = "Elune's Chosen: Delves", string = "CgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmxsMzMjZWMLGMWGY2MjRT0MzsYmZmxYGGAAAAAwwyMgltZGMmlBwUAAAgNMzDMgFzgBjNLbAmZAMA" },
  },
})

-- DRUID 105 (restoration-druid)
ns.GuideStore:RegisterSiteLoadouts(105, {
  source = "Icy Veins Restoration Druid talent guide, updated Aug 10, 2026 - 7:20 PM; Wowhead Restoration Druid talent guide, updated 2026/08/12",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Wildstalker Raid", string = "CkGAAAAAAAAAAAAAAAAAAAAAAYMmZZmZMzMmthBzsZsNmBAAAAAAAAAAbDa2YMNzY4BMLzMzMDDzAAAAAAAAAAIAAgZbmlmtZ2sxYmZwMwoZAAmZAYA" },
    { site = "Icy Veins", label = "Wildstalker Mythic+", string = "CkGAAAAAAAAAAAAAAAAAAAAAAMMmZZMjZmxsNMMmlZsZbGAAAAAAAAAAsMoZzw0MjZwsYmZmZZGegZAAAAAAAwAAQAAAz2MbNbzsYjxMDMzCoZAAmZAYA" },
    { site = "Icy Veins", label = "Wildstalker Delves", string = "CkGAAAAAAAAAAAAAAAAAAAAAAMMmxYGzMjZbmZYYhZx2MAAAAAAAAAAYbQzmhpZMzYMLmZmZWmhxAAAAAAAYMAAEAAwsMzWzyML2gZeAMjFQzAAMzAwA" },
    { site = "Wowhead", label = "Keeper of the Grove: Raid", string = "CkGAAAAAAAAAAAAAAAAAAAAAAMjxMLzMjZmxsNMDmFjNmBAAAAAAAAAAbDa2YMNzY4BMLzMzMDDzAAAAAAAAAbbjFMNzsMAAABswYmZYmBGNDAmZAADA" },
    { site = "Wowhead", label = "Keeper of the Grove: Mythic+", string = "CkGAAAAAAAAAAAAAAAAAAAAAAMMmZZMjZmxsNMMmlZsZbGAAAAAAAAAAsMoZzw0MjZwsYmZmZZGGDAAAAAAAGw2yYBTzMLDAAQALMmZgZ2ANDAmZAADA" },
    { site = "Wowhead", label = "Keeper of the Grove: Mythic+ (2)", string = "CkGAAAAAAAAAAAAAAAAAAAAAAMMmZZMjZmxsNzMgFzsZbGAAAAAAAAAAsNoZzw0MmZMmFzMzMLzwYAAAAAAAwAAQAAAzyMbNLzsYDm5BwMWANDAwMDADA" },
    { site = "Wowhead", label = "Wildstalker: Raid", string = "CkGAAAAAAAAAAAAAAAAAAAAAAYMmZZmZMzMmthZwsZsNmBAAAAAAAAAAbDa2YMNzY4BMLzMzMDDzAAAAAAAAAAIAAgZbmlmtZ2sxYmZwMwoZAAmZAYA" },
    { site = "Wowhead", label = "Wildstalker: Mythic+", string = "CkGAAAAAAAAAAAAAAAAAAAAAAMMmZZMjZmxsNMMmlZsZbGAAAAAAAAAAsMoZzw0MjZwsYmZmZZGGDAAAAAAAGAACAAYWmZrZbmFbMmZgZ2ANDAwMDADA" },
  },
})

-- DEMONHUNTER 577 (havoc-demon-hunter)
ns.GuideStore:RegisterSiteLoadouts(577, {
  source = "Icy Veins Havoc Demon Hunter talent guide, updated Aug 30, 2026 - 2:00 AM; Wowhead Havoc Demon Hunter talent guide, updated 2026/08/22",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Raid / Cleave – Fel-Scarred", string = "CEkAAAAAAAAAAAAAAAAAAAAAAYgZmZMjZmZmxMZMzAAAAAAAmNjZbmxYmtZmxyMjZsMzwMLzsMDGGLbMhxMjhFAAAAAAAwMDwAAAAwA" },
    { site = "Icy Veins", label = "AoE / Mythic+ – Fel-Scarred", string = "CEkAAAAAAAAAAAAAAAAAAAAAAYmZGzMz2MmZmxYmMmZAAAAAAAzixsNDzMwMWmZmZYmBzyAbzmZMMbMNmZGzYDAAAYAAAAMzgBAAAgB" },
    { site = "Icy Veins", label = "Delves – Fel-Scarred", string = "CEkAAAAAAAAAAAAAAAAAAAAAAYmZGzMjZMzMjxMhZGAAAAAAwsYmhZMzAzYZmZmxyMDmlB2mNzYY2YaMzMzM2AAAAAAAAYmBDAAAAD" },
    { site = "Icy Veins", label = "High Mythic+ Keys - Aldrachi Reaver", string = "CEkAAAAAAAAAAAAAAAAAAAAAAYgZmZ2mxMzMGzkxMDAAAAAAYWMmtZYmZ2mZGLzMmxyMDzsMz2MYYssxEGzMmxCAAAAAAAYmBYAAAAYA" },
    { site = "Wowhead", label = "Fel-Scarred: Raid", string = "CEkAAAAAAAAAAAAAAAAAAAAAAYmZGzMzmxMzMmZmMmZAAAAAAAzyDMmtZYmBzMWmZMDzMGzyALziZMMbaaMzMG2AAAAAAAAYmBDAAAAD" },
    { site = "Wowhead", label = "Fel-Scarred: Mythic+", string = "CEkAAAAAAAAAAAAAAAAAAAAAAYmZGzMz2MmZmxYmMmZAAAAAAAzixsNDzMwMWmZmZYmBzyALzmZMMLaaMzMmxGAAAwAAAAYmBDAAAAD" },
    { site = "Wowhead", label = "Aldrachi Reaver: Raid", string = "CEkAAAAAAAAAAAAAAAAAAAAAAYgZmZ2MmZmxMzkxMDAAAAAAYWegxsNDzMz2MzYZmxMWmZYmlZ2mBDjlNmkxMjhFAAAAAAAwMDwAAAAwA" },
    { site = "Wowhead", label = "Aldrachi Reaver: Mythic+", string = "CEkAAAAAAAAAAAAAAAAAAAAAAYGMzMz2MmZmxYmMmZAAAAAAAzixsNDzMz2MzYZmxMMzwMLzsNDGGbbMJjZGzYBAAAAAAAMzAMAAAAM" },
  },
})

-- DEMONHUNTER 581 (vengeance-demon-hunter)
ns.GuideStore:RegisterSiteLoadouts(581, {
  source = "Icy Veins Vengeance Demon Hunter talent guide, updated Aug 10, 2026 - 7:20 PM; Wowhead Vengeance Demon Hunter talent guide, updated 2026/08/12",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Vengeance Single Target", string = "CUkAAAAAAAAAAAAAAAAAAAAAAAAMjZmZMzMjMzMYWMzMDMjZGzYGzMDzMzM2GzsNGAAAAAAAAwMzYDAAAADGzMzMbtNzMDAAAAAwA" },
    { site = "Icy Veins", label = "Vengeance AoE", string = "CUkAAAAAAAAAAAAAAAAAAAAAAAAMjZmZMMzkZmBWMjZwMjZGzMzMzYwMzM2YmtxwAAAAAAAAwMzMbAAAAYgZmZmZrtZmZAgBAAAwA" },
    { site = "Wowhead", label = "Aldrachi Reaver: Raid", string = "CUkAAAAAAAAAAAAAAAAAAAAAAAAYMzMjZmZkZmZY2MzMjhZMzYGzYmZYGmx2MzYMAAAAgZbGMMW2YCDzMjFAAAAMYAIAzMADAAAgB" },
    { site = "Wowhead", label = "Aldrachi Reaver: Mythic+", string = "CUkAAAAAAAAAAAAAAAAAAAAAAAAYMzMjhZkZmBWMjZwMjZGz8AzMzYYmZmx2YGjxMAAAAMbzghxyGTYYmZsAAAAgBGABYmBMDAAAgB" },
    { site = "Wowhead", label = "Aldrachi Reaver: Cleave", string = "CUkAAAAAAAAAAAAAAAAAAAAAAAAYMzMjZmZkZmZYYmZGDzYmxMmxMmxMmZsNzMGDAAAAY2mBDjlNmwwMzYBAAAADGACwMDwAAAAYA" },
    { site = "Wowhead", label = "Aldrachi Reaver: Delves", string = "CUkAAAAAAAAAAAAAAAAAAAAAAAAYMzMjxMjMzMwmZMDmZMzYmHYGzYMzMzM2GzgxMAAAAMbzghxyGTYYmZsAAAAgBzAIAzMADAAAgB" },
    { site = "Wowhead", label = "Annihilator: Raid", string = "CUkAAAAAAAAAAAAAAAAAAAAAAAAYMzMjZmZkZmZY2MzMjhZMzYGzYmZYGmx2MzYMAAAAAAAQAzMjNAAAAMYMzMzs02MzMAwAAAAYA" },
    { site = "Wowhead", label = "Annihilator: Mythic+", string = "CUkAAAAAAAAAAAAAAAAAAAAAAAAYMzMjhZkZmBWMjZwMjZGz8AzMzYYmZmx2YGjxMAAAAAAACYmZsBAAAgBmZmZml2mZmBAzAAAAYA" },
    { site = "Wowhead", label = "Annihilator: Cleave", string = "CUkAAAAAAAAAAAAAAAAAAAAAAAAYMzMjZmZkZmZYWMzMzMMjZGzYGzYYGmx2MzYMAAAAAAAQAzMjNAAAAMYMzMzs02MzMAwAAAAYA" },
    { site = "Wowhead", label = "Annihilator: Delves", string = "CUkAAAAAAAAAAAAAAAAAAAAAAAAYMzMjxMjMzMwmZMDmZMzYmHYGzYMzMzM2GzgxMAAAAAAACYmZsBAAAgBzMzMzs02MzMAwAAAAYA" },
  },
})

-- DEMONHUNTER 1480 (devourer-demon-hunter)
ns.GuideStore:RegisterSiteLoadouts(1480, {
  source = "Icy Veins Devourer Demon Hunter talent guide, updated Aug 17, 2026 - 6:47 PM; Wowhead Devourer Demon Hunter talent guide, updated 2026/08/17",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Devourer Single Target - Void-Scarred", string = "CgcBAAAAAAAAAAAAAAAAAAAAAAAWMzMzMzMjBmBAAAAAAY5BGz2gZAAAAAAAAYGzw8AzMzMzMzMjZ2mZM202CACYAMmZmtZmpZbmlZmxYGA" },
    { site = "Icy Veins", label = "Devourer AoE - Void-Scarred", string = "CgcBAAAAAAAAAAAAAAAAAAAAAAAWMzMzMzYMGmBAAAAAAY5BGz2gZAAAAAAAAYGzw8AzMzMzMzMjZ2mZM202CACYAMmZmtZmpZZmlZmhZGA" },
    { site = "Icy Veins", label = "Devourer Delves - Void-Scarred", string = "CgcBAAAAAAAAAAAAAAAAAAAAAAA2MzMzMzMjxwMAAAAAAAmxAmBAAAAAAAgZMDzDMzMzMzMzMmZbmxYTbbAIgBwMzMz2Mz0sNz2MzwMDA" },
    { site = "Wowhead", label = "Void-Scarred: Raid ST", string = "CgcBAAAAAAAAAAAAAAAAAAAAAAA2MmZmZmZmxwMAAAAAAAegxsNYGAAAAAAAAmxMMmZmZMzMzYmtZGjNttAgAGgZMzMbzMTz2MLzMjZMA" },
    { site = "Wowhead", label = "Void-Scarred: Raid Cleave", string = "CgcBAAAAAAAAAAAAAAAAAAAAAAAWMmZmZmZmBmBAAAAAAY7BGz2gZAAAAAAAAYGzwYmZmZmZmZMz2Mjxm2WAQADwDMmZmtZmpZbmlZmxYGA" },
    { site = "Wowhead", label = "Void-Scarred: Mythic+", string = "CgcBAAAAAAAAAAAAAAAAAAAAAAAWmZmZmZGjxwMAAAAAAALGz2gZAAAAAAAAYGzw8AzMzMzMzMMz2MjxmsAgAGgZMzMbzMTzyMLzMDzMA" },
    { site = "Wowhead", label = "Annihilator: Raid ST", string = "CgcBAAAAAAAAAAAAAAAAAAAAAAA2MmZmZmZmxwMAAAAAAAegxsNYGAAAAAAAAmxMMzMzMjZmZGzsYGjFtswMzMzWbzMzAYGDABMGMmB" },
    { site = "Wowhead", label = "Annihilator: Raid Cleave", string = "CgcBAAAAAAAAAAAAAAAAAAAAAAA2MmZmZmZmxwMAAAAAAAegxsNYGAAAAAAAAmxMMzMzMzMzMDzsYGjFtswMzMzWbzMzAYGDABMGMmB" },
    { site = "Wowhead", label = "Annihilator: Mythic+", string = "CgcBAAAAAAAAAAAAAAAAAAAAAAA2mxMzMzMzMGmBAAAAAAYxY2GMDAAAAAAAAzYwMzMzMzMzMjZWMjxiWWYmZmZrtZmZAMMAEwYwYGA" },
    { site = "Wowhead", label = "Annihilator: Delves", string = "CgcBAAAAAAAAAAAAAAAAAAAAAAA2MmZmZmZmxwMAAAAAAAmxAmBAAAAAAAgZMDzMzMzMzMzwMbmxYRLbMzMzs1yMzMAmZGACYMYMD" },
  },
})

-- EVOKER 1467 (devastation-evoker)
ns.GuideStore:RegisterSiteLoadouts(1467, {
  source = "Icy Veins Devastation Evoker talent guide, updated Aug 10, 2026 - 7:20 PM; Wowhead Devastation Evoker talent guide, updated 2026/08/12",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Scalecommander Raid/Delves", string = "CsbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjZgZYGzMgBjZamZmpZmx2MMzMzMzMzAmxMGzMLzMDMwYwGsMGN2GAzAwGGYmBDD" },
    { site = "Icy Veins", label = "Scalecommander Mythic+", string = "CsbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjZAMzwMwMYMTjZmpZmZ2mhZmZmZmZGwMzMGzMLzMDMwYwGsMGN2GAzAwGGYmBDD" },
    { site = "Wowhead", label = "Scalecommander: Raid", string = "CsbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjZgZYGzMgBjZamZmpZM2mxMzMzMzMzAmxMGzMLzMDMwYwGsMGN2GQmBBbYgZGMMA" },
    { site = "Wowhead", label = "Scalecommander: Mythic+", string = "CsbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjZAMzwMwAjZaMzMNjZ2mxMzMzMzMzAmZmZGzMLzMDMwYwGsMGN2GQmBBbYGMzghB" },
    { site = "Wowhead", label = "Scalecommander: Delves", string = "CsbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwMjZgZYmhBGGjZaMzMNjxyMmZmZmZmZGwMzYYmZZmZgBYwGsMGN2GQmBBbYgZGMjB" },
    { site = "Wowhead", label = "Flameshaper: Raid", string = "CsbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmZwMDGMgBjZamZmJjxyMzMzwMzMzAmxMzYmZZmZwMwMmB2ALgZYCsFsMMAmZGG" },
    { site = "Wowhead", label = "Flameshaper: Mythic+", string = "CsbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjZwMjZGzMwMGDTDzMZM2mZmZGGzMzAmZmxYmZbmZwMwMmBWAbgZYCsFsMMDwMzwA" },
    { site = "Wowhead", label = "Flameshaper: Delves", string = "CsbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZMDmZMzYmBmxYYaYmJjx2MzMzwYmZGwMzMGzMmZGMDMjZgFwGYGmAbBLDzAMzMMA" },
  },
})

-- EVOKER 1468 (preservation-evoker)
ns.GuideStore:RegisterSiteLoadouts(1468, {
  source = "Icy Veins Preservation Evoker talent guide, updated Aug 28, 2026 - 6:30 AM; Wowhead Preservation Evoker talent guide, updated 2026/08/12",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Flameshaper Raiding - Flameshaper", string = "CwbBAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMDmZMYGzmhZmZbAAAMjZMYGzIzMDAAAwMzMZmZmxsNzMAYGzALgFwMMB2MsZYAMzMGA" },
    { site = "Icy Veins", label = "Flameshaper Mythic+ - Flameshaper", string = "CwbBAAAAAAAAAAAAAAAAAAAAAAAAAAAmZmZ2WmZGDjxsZGw2wAAAzYGzMjhZiZmBAAAMzMTGzMjxMzAAjZgFwCYGmAbM2MMAmZGD" },
    { site = "Icy Veins", label = "Chronowarden Raiding - Chronowarden", string = "CwbBAAAAAAAAAAAAAAAAAAAAAAAAAAAmZmZwMjBzY2MMzMbYAAgZMjBzYGZmZAAAAmZmJzYmxsNzMAYgxM2YBGYGGawYBGzMAjB" },
    { site = "Icy Veins", label = "Chronowarden Mythic+ - Chronowarden", string = "CwbBAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMz2yAzYmxsZGjx2wAAAzYGzghZyMzMAAAw2MzMNjZmZGjZAAYMjFWgBmhhGGWgxMDAD" },
    { site = "Wowhead", label = "Flameshaper: Mythic+", string = "CwbBAAAAAAAAAAAAAAAAAAAAAAAAAAAmZmZ2WmZGDjxsZGw2wAAAzYmZmZMMTMmBAAAMzMTGzMzMGzAAjZgFwGYGmQ2YsZYGgZGGA" },
    { site = "Wowhead", label = "Flameshaper: Delves", string = "CwbBAAAAAAAAAAAAAAAAAAAAAAAAAAAmZmZ2MwYmZGMzMDbAAAYYMDzYGZmZAAAALzMz0MGzMjZmBAGzAbgNwMMhsxYzwAYmZmB" },
    { site = "Wowhead", label = "Chronowarden: Raid", string = "CwbBAAAAAAAAAAAAAAAAAAAAAAAAAAAYmZ2WmHADzMmNjZmZWmxAAAzYGDmxMyMzAAAAMzMTmxMjZbmZAwAjZsxCMwMaoBsAjZGgxA" },
    { site = "Wowhead", label = "Chronowarden: Mythic+", string = "CwbBAAAAAAAAAAAAAAAAAAAAAAAAAAAegZmZ2WGYYmxsZGjx2wAAAzYmZmZMMTMmBAAA2mZmJjZmZGjZAAYMjNWgBmRDNMsAzMzAwA" },
    { site = "Wowhead", label = "Chronowarden: Delves", string = "CwbBAAAAAAAAAAAAAAAAAAAAAAAAAAAmZmZ2MwYmZGMzMDbAAAYYMDzYGZmZAAAALzMz0MGzMjZmBAgxM2YDGYGN0gxCMmZAmZA" },
  },
})

-- EVOKER 1473 (augmentation-evoker)
ns.GuideStore:RegisterSiteLoadouts(1473, {
  source = "Icy Veins Augmentation Evoker talent guide, updated Aug 10, 2026 - 7:20 PM; Wowhead Augmentation Evoker talent guide, updated 2026/08/12",
  patch = "12.1",
  builds = {
    { site = "Icy Veins", label = "Raiding Build - Chronowarden", string = "CEcBAAAAAAAAAAAAAAAAAAAAAMMzMbzMzgZYmZZGzMjZ2AAAAAAAAYmhxMYM1YmZGAAAAMjZMmZWGzMwMMwYGLsADMDDNwCGjZGAYA" },
    { site = "Icy Veins", label = "Weekly Mythic+ Build - Scalecommander", string = "CEcBAAAAAAAAAAAAAAAAAAAAAMMzMbjZmxyMYmtZMzMmBAAAAAAAAmhHYGYM1YmZGAAAAMzMjxMz2YmBmZzYwCsMGGbDgZQshxMYmBDG" },
    { site = "Icy Veins", label = "High Key Mythic+ Build - Chronowarden", string = "CEcBAAAAAAAAAAAAAAAAAAAAAMMzMbzMzgZYmZZGzMjZ2AAAAAAAAYmhZGYM1YmZGAAAAMjZMmZWGzMwMMwYGLsADMDDNwCGzMzAAD" },
    { site = "Wowhead", label = "Chronowarden: Raid", string = "CEcBAAAAAAAAAAAAAAAAAAAAAMMzMbzMzgZYmZZGzMjZ2AAAAAAAAYmhxMYM1YmZGAAAAMjZMmZWGzMwMMwYGLsADMDDNiFMGzMAwA" },
    { site = "Wowhead", label = "Chronowarden: Mythic+", string = "CEcBAAAAAAAAAAAAAAAAAAAAAMMzMbzMzgZYmZZGzMjZ2AAAAAAAAwMMzAjpGzMzAAAAgZmZMmZ2GzMwMMwYGLsADMDDNiFMmZmBAG" },
    { site = "Wowhead", label = "Chronowarden: Delves", string = "CEcBAAAAAAAAAAAAAAAAAAAAAMMzMbjZmxyMYmlZMzMmBAAAAAAAAmhZGYM1YmZGAAAAMzMjxMzyYmBmZzAjZswCMwMM0IWwYmZGAYA" },
    { site = "Wowhead", label = "Scalecommander: Raid", string = "CEcBAAAAAAAAAAAAAAAAAAAAAMMzMbzMzgZYmZZGzMjZ2AAAAAAAAYmhxMYM1YmZGAAAAMjZMmZWGzMwMMGsALjhx2AYmI2wYgZGAD" },
    { site = "Wowhead", label = "Scalecommander: Mythic+", string = "CEcBAAAAAAAAAAAAAAAAAAAAAMMzMbjZGMDzMLzYmZMzGAAAAAAAAmhZGYM1YmZGAAAAMzMjxMz2YmBmZzYwCsMGGbDgZiYDjZwMDgB" },
    { site = "Wowhead", label = "Scalecommander: Delves", string = "CEcBAAAAAAAAAAAAAAAAAAAAAMMzMbjZmxyMYmlZMzMmBAAAAAAAAmhZGYM1YmZGAAAAMzMjxMzyYmBmZzYwCsMGGbDgZiYDjZwMDgB" },
  },
})
