#!/usr/bin/env python3
"""Regenerates SpecSage/Data/BiS.lua from Icy Veins' per-spec Best in Slot tables.

Each Icy Veins gear guide carries a "Best in Slot" block with one tab per
context (Overall, then Mythic+ and/or Raid where the guide splits them);
every entry is a .bis_item div with the item's wowhead ID, name, slot and
drop source. This turns that into one RegisterBiS(specID, ...) call per
spec: a list per tab, one row per slot, every row a concrete itemID the
Codex renders as a clickable item link. Wowhead's guide pages are rendered
client-side and refuse plain HTTP clients, so only Icy Veins is read.

Run from the repo root:  python3 tools/fetch_bis.py
"""
import datetime
import html
import re
import sys
import time

sys.path.insert(0, "tools")
from specs import SPECS, fetch, lua_str, icy_veins_updated  # noqa: E402

# Icy Veins slot labels -> the Data/API.lua 14-slot vocabulary.
SLOT_MAP = {
    "head": "Head", "helm": "Head", "neck": "Neck", "shoulder": "Shoulder", "shoulders": "Shoulder",
    "back": "Back", "cloak": "Back", "chest": "Chest", "wrist": "Wrist", "wrists": "Wrist",
    "bracers": "Wrist", "hands": "Hands", "gloves": "Hands", "waist": "Waist", "belt": "Waist",
    "legs": "Legs", "feet": "Feet", "boots": "Feet", "ring": "Ring", "ring 1": "Ring", "ring 2": "Ring",
    "finger": "Ring", "trinket": "Trinket", "trinket 1": "Trinket", "trinket 2": "Trinket",
    "main hand": "Weapon", "main-hand": "Weapon", "weapon": "Weapon", "two-hand": "Weapon",
    "two hand": "Weapon", "2h weapon": "Weapon", "ranged": "Weapon", "off hand": "Off-hand",
    "off-hand": "Off-hand", "offhand": "Off-hand", "shield": "Off-hand",
}


def strip_tags(s):
    return html.unescape(re.sub(r"<[^>]+>", "", s)).strip()


def parse_bis(body):
    """Returns [ { title, rows: [ {slot, itemID, name, from} ] } ] or None."""
    i = body.find('class="image_block best_in_slot"')
    if i < 0:
        return None
    block = body[i:]
    # The block runs to the first <h2> after its last .bis_item - the FAQ
    # dropdowns inside the block's own description carry heading markup of
    # their own, so cutting at the first heading cut the items off entirely.
    last_item = max((m.start() for m in re.finditer(r'class="bis_item', block)), default=-1)
    if last_item < 0:
        return None
    end = block.find("<h2 ", last_item)
    block = block[:end] if end > 0 else block

    titles = dict(re.findall(r'id="(bis_\d+_\d+)_button">([^<]+)<', block))
    tabs = []
    for m in re.finditer(r'<div class="image_block_content" id="(bis_\d+_\d+)">', block):
        tab_id = m.group(1)
        start = m.end()
        nxt = re.search(r'<div class="image_block_content" id="bis_', block[start:])
        seg = block[start:start + nxt.start()] if nxt else block[start:]
        rows = []
        for item in re.split(r'<div class="bis_item[ "]', seg)[1:]:
            im = re.search(r'data-wowhead="item=(\d+)[^"]*"[^>]*>\s*<img[^>]*>\s*<span[^>]*>([^<]+)<', item)
            if not im:
                im = re.search(r'data-wowhead="item=(\d+)[^"]*"[^>]*>([^<]+)<', item)
            if not im:
                continue
            sm = re.search(r'class="bis_item_slot">([^<]+)<', item)
            slot_raw = strip_tags(sm.group(1)).lower() if sm else ""
            slot = SLOT_MAP.get(slot_raw)
            if not slot:
                # "Ring 1" / "Trinket 2" / "Main Hand" variants
                base = re.sub(r"\s*\d$", "", slot_raw)
                slot = SLOT_MAP.get(base)
            if not slot:
                print("  unmapped slot %r" % slot_raw, file=sys.stderr)
                continue
            dm = re.search(r'class="bis_item_drop">(.*?)</span>', item, re.S)
            rows.append({
                "slot": slot, "itemID": int(im.group(1)),
                "name": html.unescape(im.group(2)).strip(),
                "from": strip_tags(dm.group(1)) if dm else "",
            })
        title = titles.get(tab_id, tab_id)
        # Some guides repeat the whole block (Discipline's page carries it
        # twice); the first list under a given title wins.
        if rows and not any(t["title"] == title for t in tabs):
            tabs.append({"title": title, "rows": rows})
    return tabs or None


def main():
    out = [
        "-- Data/BiS.lua",
        "-- GENERATED by tools/fetch_bis.py - do not hand-edit; re-run the script.",
        "--",
        "-- Per-spec Best in Slot lists from Icy Veins' gear guides: one list per",
        "-- context the guide offers (Overall, Mythic+, Raid), one row per slot, every",
        "-- row a concrete itemID the Codex shows as a clickable item link. This is",
        "-- one site's editorial BiS at the time the script ran - it goes stale every",
        "-- patch, and the Codex says so - not a claim of the single best item for",
        "-- your character. See DESIGN.md's \"Linked BiS lists\".",
        "-- Generated: %s UTC" % datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M"),
        "",
        "local ADDON, ns = ...",
        "if not ns.GuideStore then return end",
        "",
    ]
    ok_count = 0
    for classToken, specID, _, ivSlug, ivRole in SPECS:
        url = "https://www.icy-veins.com/wow/%s-pve-%s-gear-best-in-slot" % (ivSlug, ivRole)
        tabs, updated = None, None
        try:
            body = fetch(url)
            tabs, updated = parse_bis(body), icy_veins_updated(body)
        except Exception as exc:
            print("  %s: %s" % (url, exc), file=sys.stderr)
        time.sleep(0.5)
        out.append("-- %s %d (%s)" % (classToken, specID, ivSlug))
        if not tabs:
            print("%-12s %5d %-24s NO BIS TABLE" % (classToken, specID, ivSlug))
            out.append("")
            continue
        out.append("ns.GuideStore:RegisterBiS(%d, {" % specID)
        out.append("  source = %s," % lua_str("Icy Veins %s gear guide, updated %s"
                                               % (ivSlug.replace("-", " ").title(), updated or "?")))
        out.append('  patch = "12.1",')
        out.append("  lists = {")
        for tab in tabs:
            out.append("    { title = %s, list = {" % lua_str(tab["title"]))
            for r in tab["rows"]:
                out.append("      { slot = %s, itemID = %d, name = %s, from = %s }," % (
                    lua_str(r["slot"]), r["itemID"], lua_str(r["name"]), lua_str(r["from"])))
            out.append("    }},")
        out.append("  },")
        out.append("})")
        out.append("")
        ok_count += 1
        print("%-12s %5d %-24s %s" % (classToken, specID, ivSlug,
              ", ".join("%s:%d" % (t["title"], len(t["rows"])) for t in tabs)))
    path = "SpecSage/Data/BiS.lua"
    with open(path, "w") as f:
        f.write("\n".join(out))
    print("wrote %s: %d specs" % (path, ok_count))


if __name__ == "__main__":
    main()
