#!/usr/bin/env python3
"""Regenerates SpecSage/Data/StatPriority.lua from tools/wowhead_stats.json.

Wowhead publishes a stat priority per hero talent tree on each spec's
stat-priority guide page. Roughly two thirds of those pages carry the
priority as a plain ordered list that tools/wowhead_harvest.js's
__harvestStats can read straight off the page; the rest write it as free
text inside the list items ("Mastery to 1200 rating", "Haste (~700 Haste)",
"Crit = Mastery") or as prose, which no parser should be trusted to turn
into a ranking on its own. tools/wowhead_stats.json is therefore the
reviewed transcription of all 40 pages, and this script only turns that
into one RegisterStatPriority(specID, ...) call per spec.

Run from the repo root:  python3 tools/fetch_stats.py
"""
import datetime
import json
import os
import sys

sys.path.insert(0, "tools")
from specs import SPECS, lua_str  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))


def main():
    data = json.load(open(os.path.join(HERE, "wowhead_stats.json")))["specs"]
    out = [
        "-- Data/StatPriority.lua",
        "-- GENERATED by tools/fetch_stats.py - do not hand-edit; edit",
        "-- tools/wowhead_stats.json and re-run the script.",
        "--",
        "-- Per-spec stat priorities from Wowhead's own stat-priority guide page for",
        "-- each spec, one list per hero talent tree. Where Wowhead splits the",
        "-- priority by something other than the hero tree - a tank's survivability",
        "-- vs DPS goal, a healer's raid vs Mythic+ content - the list title names",
        "-- both hero trees, so every hero spec is covered explicitly rather than",
        "-- silently dropped. Anything Wowhead ranks that is not a character stat",
        "-- (item level, weapon damage) is carried in the list's note instead of",
        "-- being invented into the order. This is Wowhead's editorial priority at",
        "-- the time each page was read - it goes stale every patch, and the Codex",
        "-- says so - not a sim of your character. See DESIGN.md's \"Stat priority\".",
        "-- Generated: %s UTC" % datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M"),
        "",
        "local ADDON, ns = ...",
        "if not ns.GuideStore then return end",
        "",
    ]
    count = 0
    for classToken, specID, _, ivSlug, _ in SPECS:
        rec = data.get(str(specID))
        if not rec:
            print("%-12s %5d %-24s NO STAT DATA" % (classToken, specID, ivSlug), file=sys.stderr)
            continue
        name = ivSlug.replace("-", " ").title()
        out.append("-- %s %d (%s)" % (classToken, specID, ivSlug))
        out.append("ns.GuideStore:RegisterStatPriority(%d, {" % specID)
        out.append("  source = %s," % lua_str(
            "Wowhead %s stat priority guide, updated %s" % (name, rec.get("updated") or "?")))
        out.append("  url = %s," % lua_str(rec["url"]))
        out.append('  patch = "12.1",')
        out.append("  heroSplit = %s," % ("true" if rec.get("heroSplit") else "false"))
        out.append("  lists = {")
        for var in rec["variants"]:
            out.append("    { title = %s," % lua_str(var["title"]))
            if var.get("note"):
                out.append("      note = %s," % lua_str(var["note"]))
            out.append("      list = { %s }," % ", ".join(
                "{ stat = %s }" % lua_str(s) for s in var["stats"]))
            out.append("    },")
        out.append("  },")
        out.append("})")
        out.append("")
        count += 1
        print("%-12s %5d %-24s %s" % (classToken, specID, ivSlug,
                                      ", ".join(v["title"] for v in rec["variants"])))
    path = "SpecSage/Data/StatPriority.lua"
    with open(path, "w") as f:
        f.write("\n".join(out))
    print("wrote %s: %d specs" % (path, count))


if __name__ == "__main__":
    main()
