#!/usr/bin/env python3
"""Regenerates SpecSage/Data/SiteLoadouts.lua from Icy Veins' talent-build pages.

Each Icy Veins "Spec Builds & Talents" page carries its recommended builds
as export-string blocks (a title such as "Raid / Cleave - Fel-Scarred" and
the exact Blizzard talent export string). Talent strings are opaque, so they
are read from the raw HTML, never summarised, and every string is decoded
far enough to confirm it encodes the spec it is filed under (the export
format's first 8 bits are the serialization version, the next 16 the
specID) - a string for the wrong spec is dropped with a warning rather than
shipped. Wowhead's guide pages render client-side and refuse plain HTTP
clients, so only Icy Veins is read.

Run from the repo root:  python3 tools/fetch_talents.py
"""
import datetime
import html
import re
import sys
import time

sys.path.insert(0, "tools")
from specs import SPECS, fetch, lua_str, icy_veins_updated  # noqa: E402
import wowhead  # noqa: E402

ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"


def decode_header(code):
    """Returns (version, specID) from a Blizzard talent export string."""
    bits = []
    for ch in code:
        v = ALPHABET.index(ch)
        bits.extend((v >> b) & 1 for b in range(6))

    def read(pos, n):
        return sum(bits[pos + k] << k for k in range(n))

    return read(0, 8), read(8, 16)


def parse_builds(body):
    builds = []
    for title, code in re.findall(
            r'export-string__title">(.*?)</span>.*?export-string__code">\s*([A-Za-z0-9+/]+)', body, re.S):
        label = html.unescape(re.sub(r"<[^>]+>", "", title))
        label = re.sub(r"\s+", " ", label).strip()          # titles wrap across lines on some pages
        label = re.sub(r"\s*[-\u2013]\s*$", "", label)        # "Scalecommander Raid/Delves -" (missing suffix)
        builds.append({"label": label, "string": code.strip()})
    return builds


def main():
    out = [
        "-- Data/SiteLoadouts.lua",
        "-- GENERATED by tools/fetch_talents.py - do not hand-edit; re-run the script.",
        "--",
        "-- Recommended talent builds from Icy Veins' and Wowhead's per-spec talent pages",
        "-- (Wowhead via tools/wowhead_harvest.js + tools/wowhead_dump.json), as exact",
        "-- Blizzard export strings, each verified to decode to the spec it is filed",
        "-- under. One site's picks at the time the script ran, alongside (not",
        "-- replacing) the SimC-default and live-top-player builds the guides carry.",
        "-- See DESIGN.md's \"Guide-site talent builds\".",
        "-- Generated: %s UTC" % datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M"),
        "",
        "local ADDON, ns = ...",
        "if not ns.GuideStore then return end",
        "",
    ]
    total = 0
    dump = wowhead.load()
    for classToken, specID, _, ivSlug, ivRole in SPECS:
        url = "https://www.icy-veins.com/wow/%s-pve-%s-spec-builds-talents" % (ivSlug, ivRole)
        builds, updated = [], None
        try:
            body = fetch(url)
            builds, updated = parse_builds(body), icy_veins_updated(body)
        except Exception as exc:
            print("  %s: %s" % (url, exc), file=sys.stderr)
        time.sleep(0.5)

        kept, seen = [], set()
        for b in builds:
            try:
                version, spec = decode_header(b["string"])
            except (ValueError, IndexError):
                print("  %s: undecodable string for %r" % (ivSlug, b["label"]), file=sys.stderr)
                continue
            if spec != specID:
                print("  %s: %r decodes to spec %d, expected %d - dropped" % (ivSlug, b["label"], spec, specID),
                      file=sys.stderr)
                continue
            if b["string"] in seen:
                continue
            seen.add(b["string"])
            kept.append(b)

        for b in kept:
            b["site"] = "Icy Veins"
        wh_kept = []
        for b in wowhead.builds(dump, specID):
            try:
                version, spec = decode_header(b["string"])
            except (ValueError, IndexError):
                print("  wowhead %s: undecodable string for %r" % (ivSlug, b["label"]), file=sys.stderr)
                continue
            if spec != specID:
                print("  wowhead %s: %r decodes to spec %d, expected %d - dropped" % (ivSlug, b["label"], spec, specID),
                      file=sys.stderr)
                continue
            if b["string"] in seen:
                continue
            seen.add(b["string"])
            b["site"] = "Wowhead"
            wh_kept.append(b)

        out.append("-- %s %d (%s)" % (classToken, specID, ivSlug))
        if not kept and not wh_kept:
            print("%-12s %5d %-24s NO BUILDS" % (classToken, specID, ivSlug))
            out.append("")
            continue
        sources = []
        if kept:
            sources.append("Icy Veins %s talent guide, updated %s" % (ivSlug.replace("-", " ").title(), updated or "?"))
        if wh_kept:
            sources.append("Wowhead %s talent guide, updated %s" % (ivSlug.replace("-", " ").title(),
                                                                   wowhead.updated(dump, specID, "talentUpdated") or "?"))
        out.append("ns.GuideStore:RegisterSiteLoadouts(%d, {" % specID)
        out.append("  source = %s," % lua_str("; ".join(sources)))
        out.append('  patch = "12.1",')
        out.append("  builds = {")
        for b in kept + wh_kept:
            out.append("    { site = %s, label = %s, string = %s }," % (lua_str(b["site"]), lua_str(b["label"]), lua_str(b["string"])))
        out.append("  },")
        out.append("})")
        out.append("")
        total += len(kept) + len(wh_kept)
        print("%-12s %5d %-24s IV %d + WH %d build(s)" % (classToken, specID, ivSlug, len(kept), len(wh_kept)))
    path = "SpecSage/Data/SiteLoadouts.lua"
    with open(path, "w") as f:
        f.write("\n".join(out))
    print("wrote %s: %d builds" % (path, total))


if __name__ == "__main__":
    main()
